### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by PKMadPhantom** [Levak/warfacebot#100]
![image](https://user-images.githubusercontent.com/30567330/28752061-293864c6-74ed-11e7-98c6-2e3df64df48e.png)

**Comment by Levak** [comment]
Hi,
You need to install `curl` using your packet manager or download it and put it next to `wb` (or `wb.exe` on Windows).

**Comment by PKMadPhantom** [comment]
link?

**Comment by Levak** [comment]
Pick whatever suits you:
https://curl.haxx.se/download.html

For instance, for Windows:
https://dl.uxnr.de/build/curl/curl_winssl_msys2_mingw32_stc/curl-7.53.1/curl-7.53.1.zip

**Comment by PKMadPhantom** [comment]
Do you have any links to this action?
