### ISSUE TITLE
<warface-failure> on login

### ISSUE THREAD

**Issue by ElezClub** [Levak/warfacebot#102]
Hello, Levak.

Do you know why bot sometimes fails to login with `<warface-failure>Unexpected error: not enough values to unpack (expected 3, got 2)</warface-failure>`? Sometimes it takes up to 4-5 relogins in order to finally launch a bot.

**Comment by Levak** [comment]
Hi,

I assume you are referring to RU version, and I am aware of it.
Although, I cannot give a logical explanation as to why this happens or how to fix it.
You can try adding a `sleep 5` before launching warfacebot in `wb.sh`, but AFAIR, it didn't help when I tested.
