### ISSUE TITLE
[TR] Cannot run bot since update

### ISSUE THREAD

**Issue by dexter2408** [Levak/warfacebot#103]
do not run bots on Turkey make corrections

**Comment by Levak** [comment]
Try adding this to `cfg/server/tr.cfg` and tell me if it works

```
game_crypt_key = 189,184,201,246,92,180,9,98,9,132,118,99,134,159,190,117,59,242,36,40,167,102,177,97,49,63,155,178,189,90,91,248
```

**Comment by Deadfail** [comment]
Levak, No
![screenshot_2](https://user-images.githubusercontent.com/30199368/28908777-11f43ecc-782e-11e7-8a2d-7d7c016d7636.png)

**Comment by Levak** [comment]
You didn't update bot to the latest version, which means `game_crypt_key` is not recognized as a valid CVar.

**Comment by Deadfail** [comment]
Good

**Comment by Phenixxxxx** [comment]
Same issue 

http://prntscr.com/g4nlmu

Added this line as mentioned above but not working at all
game_crypt_key = 189,184,201,246,92,180,9,98,9,132,118,99,134,159,190,117,59,242,36,40,167,102,177,97,49,63,155,178,189,90,91,248

**Comment by Levak** [comment]
> Same issue

Same answer, you're not using 1.0.10 and the cvar is not recognized.

**Comment by Phenixxxxx** [comment]
Could you explain what I need to do and how ?
