### ISSUE TITLE
[RU] bot does not work after update

### ISSUE THREAD

**Issue by franchesko1437** [Levak/warfacebot#106]
Levak. I changed the client version in files. But the bot still does not start. Stuck on cmd. Will you fix this?
Bots do not work after updating to RU server

**Comment by Levak** [comment]
Since a recent update, you cannot update your bots yourself anymore.
You need to update these 2 cvars manually, and once of them requires reverse-engineering of the game binary: `game_version` and `game_crypt_key`.

I see that RU just had an update, here are the new ones:
```
game_version = 1.15400.1410.41200
game_crypt_key = 38,134,243,4,73,252,59,166,18,115,75,164,173,227,108,254,101,51,34,9,102,189,146,230,212,254,55,121,233,46,128,2
```

**Comment by franchesko1437** [comment]
And with what is it connected that I can not update the bots anymore ?.
Did the game developers do it ?.
What is game crypt and what is it for?
Will Warfacebot not work soon? Its fics?

**Comment by Levak** [comment]
> And with what is it connected that I can not update the bots anymore ?.

Because it requires reverse-engineering of the game binary. If you can do that, then you can retrieve the key.

> Did the game developers do it ?.

They did change the encryption key formula that was based in the past only on the game version.
See https://github.com/Levak/warfacebot/blob/master/src/stream/crypt.c#L67 for more information on what I mean here.

> What is game crypt and what is it for?

It is a statically compiled key that makes game versions between publishers unable to connect on another publisher (because they use different crypt key), like game version.

> Will Warfacebot not work soon? Its fics?

It is just that the era where non-IT users were able to update themselves the bot config without my help, is over. Warfacebot still works fine, as of today.

**Comment by franchesko1437** [comment]
![16](https://user-images.githubusercontent.com/29465298/29130585-fed22c6e-7d32-11e7-9572-89ae6538808b.JPG)
Correctly did I need to change these files?
![15](https://user-images.githubusercontent.com/29465298/29130565-f09957e4-7d32-11e7-95f5-1066fff8aba9.JPG)

**Comment by Levak** [comment]
> Correctly did I need to change these files?

Yes, exactly.
I also updated repository, see ed8a30b3f2c97383aeb49f2faf3e1abb5d27f016

**Comment by franchesko1437** [comment]
If it's right, then why bot. Stiffened by cmd?

**Comment by Levak** [comment]
> If it's right, then why bot. froze by cmd?

It works fine on my side.
You probably didn't update bot to 1.0.10 to support `game_crypt_key`
https://github.com/Levak/warfacebot/releases/tag/1.0.10

**Comment by franchesko1437** [comment]
А точно. не обновил. у меня 1.0.08

**Comment by franchesko1437** [comment]
Very strange. The boat takes off in 5 seconds. Before this was not
![12 2](https://user-images.githubusercontent.com/29465298/29131251-fbdced4e-7d34-11e7-82ee-c117cea5a71c.JPG)

**Comment by Levak** [comment]
> Very strange. The b0t takes off in 5 seconds. Before this was not

You need to set `game_hwid` to a valid HWID, otherwise, server kicks you. After that you'll have 4min spare, before MRAC will kick the bot.

See #20

**Comment by franchesko1437** [comment]
I know about hwid. I left the file wb.cfg from my old bot. But still fly. Can you write an example of what kind of hwid is needed?
