### ISSUE TITLE
Bot auto-restart

### ISSUE THREAD

**Issue by franchesko1437** [Levak/warfacebot#107]

**Comment by Viktor20217** [comment]
Is it difficult for you to press the button to enter?

**Comment by franchesko1437** [comment]
Виктор, мне не трудно, но для удобства без моего непосредственного участия в фарме, эта функция необходима.

**Comment by Viktor20217** [comment]
Вообще можно привязать программу к консоли, чтобы она читала текст и после строки, выход с сервера, нажать еще раз кнопку зайти)

**Comment by franchesko1437** [comment]
А если не умею? есть какой-нибудь видеоурок для данного случая?

**Comment by Viktor20217** [comment]
@franchesko1437  я очень далек от программирования, по-этому тебе нужно самому найти и изучить.
