### ISSUE TITLE
[RU] Warface Bot break down after connect

### ISSUE THREAD

**Issue by gefort** [Levak/warfacebot#111]
I have this error after bot started. I try connect to RU server.

```Starting TLS connection...
done.
JID: 655068500@warface/GameClient
Channel: pve_050_r1
...
Rating points: 0
Money: 100
Crowns: 0
Kredits: 0
read: End of stream (5)
Closed readstream
Closed sendstream
CMD# ^C

Closed idle
Warface Bot closed!
CMD#

**Comment by Viktor20217** [comment]
Поддерживаю

**Comment by vectorjust** [comment]
Поддерживаю, так же все плохо.

**Comment by Deadfail** [comment]
+

**Comment by Levak** [comment]
You have to set `game_hwid` to a valid value, for instance in `wb.cfg`, like it is said in `README.md`.
Mecraft configures warfacebolt with probably a random one.

**Comment by Viktor20217** [comment]
Decision
Game_hwid xxxxxxxxx
(xxxxxxxx 
9 number)

**Comment by faceIess** [comment]
Viktor20217 Русский?

**Comment by Viktor20217** [comment]
Русский

**Comment by faceIess** [comment]
Viktor20217 теперь пожалуйста объясни где и что заменить)))

**Comment by Deadfail** [comment]
У всех домен яндекс не запускает?

**Comment by Viktor20217** [comment]
Осталось символы починить нам(мой друг починил, но он буржуй не рассказывает как)

**Comment by faceIess** [comment]
Вот здесь?
![17-08-2017 111312](https://user-images.githubusercontent.com/30307140/29395741-3fda5aaa-833d-11e7-8f88-44d504bcc093.jpg)

**Comment by Viktor20217** [comment]
В файле wb.cfg

**Comment by Deadfail** [comment]
faceIess, wb.cfg

**Comment by Deadfail** [comment]
![screenshot_1](https://user-images.githubusercontent.com/30199368/29395761-e98eae1a-831b-11e7-961f-513633d51d61.png)
Руснул)

**Comment by Viktor20217** [comment]
Подробнее как :D

**Comment by Levak** [comment]
Use a real text editor, like notepad++. MS notepad doesn't support standard line-breaks properly.

**Comment by Deadfail** [comment]
В командной строке нужно активировать c:>chcp 65001

**Comment by Viktor20217** [comment]
![image](https://user-images.githubusercontent.com/31064630/29395841-73d8e548-8346-11e7-960a-a31d577ed443.png)

**Comment by Levak** [comment]
@Viktor20217 try to mark the first console as default, and restart the bot.
Anyway, see #66 for more info.

**Comment by Deadfail** [comment]
Viktor20217, также в wb_launcher.hta изменить строчку на скрине
![screenshot_2](https://user-images.githubusercontent.com/30199368/29395917-16880e56-831d-11e7-9ebe-6c4aae051163.png)
На это
WshShell.Run("cmd /c chcp 65001 & wb.exe -t " + token + " -i " + userid + " -f ./cfg/server/" + server + ".cfg " + options);

**Comment by Viktor20217** [comment]
вот где была моя ошибка, я забыл этот символ &

**Comment by Viktor20217** [comment]
@Levak 
Can you tell us how to get game_crypt_key without your help?

**Comment by Levak** [comment]
> Can you tell us how to get game_crypt_key without your help?

From a casual user perspective, there is no way to do so.

**Comment by faceIess** [comment]
Viktor20217 дружище можешь мне свою рабочую версию скинуть , а то че то все я запутался((

**Comment by Viktor20217** [comment]
@faceIess https://github.com/Viktor20217/warfacebot

**Comment by faceIess** [comment]
Viktor2021 спасибо большое все работает, я хоть нашел свою ошибку

**Comment by franchesko1437** [comment]
Deadfail, у меня все равно крякозыба. Бред

**Comment by Viktor20217** [comment]
@Franchesko1437 скачай мою версию

**Comment by franchesko1437** [comment]
Твою версию и скачал.
