### ISSUE TITLE
Colors are not being shown correctly.

### ISSUE THREAD

**Issue by nathan130200** [Levak/warfacebot#112]
I'm using without debug mode. And git bash to run the warfacebot (mingw build from releases) 
![screenshot_20](https://user-images.githubusercontent.com/14365254/29425424-97633d16-8359-11e7-8fb8-e5b043b6b363.png)

Note: Using the launcher.hta says "wb.exe not found" 

:\

**Comment by Viktor20217** [comment]
> Использование launcher.hta говорит: «wb.exe not found»
For Windows users, you can also download it from binary [releases.](https://github.com/Levak/warfacebot/releases)

**Comment by nathan130200** [comment]
@Viktor20217 i'm using windows binary release.

**Comment by Viktor20217** [comment]
And what is the problem then)?
