### ISSUE TITLE
Sight in sight

### ISSUE THREAD

**Issue by franchesko1437** [Levak/warfacebot#114]
https://www.youtube.com/watch?v=YjNlDlusZ9M
Levak. Tell me how to make the display of the sight in the sight, as is done on video

**Comment by Levak** [comment]
This has nothing to do with Warfacebot.
Closing

**Comment by Viktor20217** [comment]
Привет, я автор видео :D

**Comment by franchesko1437** [comment]
Хех. кек.  Куда вписывать то?

**Comment by Viktor20217** [comment]
@franchesko1437 это настройка игры .-.

**Comment by franchesko1437** [comment]
В папке профиля?

**Comment by Viktor20217** [comment]
В game.cfg

**Comment by franchesko1437** [comment]
У меня он зашифрован.

**Comment by Viktor20217** [comment]
Зайди в профиль gamek01

**Comment by franchesko1437** [comment]
Такого нет

**Comment by Viktor20217** [comment]
[game.zip](https://github.com/Levak/warfacebot/files/1236304/game.zip)

**Comment by franchesko1437** [comment]
Благодарочка. чуть позже опробую. Такой вопрос именно к тебе, а ты случаем не некко?)

**Comment by Viktor20217** [comment]
@franchesko1437  кто это?

**Comment by franchesko1437** [comment]
У вас даже рабочие столы похожие по размеру, а в чате на одном из его видео кто-то писал типа "Виктор__Сми привет"
