### ISSUE TITLE
WarfaceBR

### ISSUE THREAD

**Issue by walvering** [Levak/warfacebot#116]
Had an att in the connection plugin of warfacebr ... they kind of changed the connection link with the game ... and the program no longer connects would have to solve ... I leave the update link that I had in the game
http://warface.uol.com.br/noticias/comunicados/atualizacao-programada-para-21-08

**Comment by nathan130200** [comment]
👍 Up!

**Comment by nathan130200** [comment]
They removed only server

**Comment by walvering** [comment]
Bom e agora como faço pra atualizar,para q o warfacebot volte a funcionar

**Comment by Levak** [comment]
@walvering try to apply #115 and  #117

**Comment by nathan130200** [comment]
@walvering só baixar normalmente cara, a única coisa que "mudou" com essa atualização foi que eles removeram algumas coisas do jogo.

**Comment by Levak** [comment]
Leave a comment
