### ISSUE TITLE
UTF-8 Not working (Colors)

### ISSUE THREAD

**Issue by nathan130200** [Levak/warfacebot#118]
![screenshot_38](https://user-images.githubusercontent.com/14365254/29617492-710c1cbe-87eb-11e7-9f0b-f3e4f96c1825.png)
![screenshot_39](https://user-images.githubusercontent.com/14365254/29617493-71181410-87eb-11e7-9136-27dad23e8684.png)

Also in CMD and WB.EXE (CodePage to UTF-8)

![screenshot_40](https://user-images.githubusercontent.com/14365254/29617521-8ea1c238-87eb-11e7-8f15-73f926cbceaf.png)
![screenshot_41](https://user-images.githubusercontent.com/14365254/29617522-8ea5520e-87eb-11e7-9b8e-8c5b3fa2adb2.png)

**Comment by Levak** [comment]
Colors are not supported by MS CMD. It's not about UTF-8.
Warfacebot outputs colors for Unix terminals.

**Comment by nathan130200** [comment]
Thanks. I Used Cygwin and colors are working fine 👍
