### ISSUE TITLE
How to enable the debug mode?

### ISSUE THREAD

**Issue by CuBnIcK** [Levak/warfacebot#123]
Hello Levak, I had a question, can I somehow enable the debug mode in version 1.0.10 (release)?

**Comment by Levak** [comment]
You need to compile it from sources with `make clean debug-wb`.
If you are referring to the binary release for mingw, nope.

**Comment by CuBnIcK** [comment]
And how it can be done without Linux? For using https://git-scm.com/ he writes that there is no command "make"

**Comment by CuBnIcK** [comment]
What to do?


> C:\ESD\warfacebot-master>mingw32-make debug-wb
> "uname" не является внутренней или внешней
> командой, исполняемой программой или пакетным файлом.
> "uname" не является внутренней или внешней
> командой, исполняемой программой или пакетным файлом.
> "uname" не является внутренней или внешней
> командой, исполняемой программой или пакетным файлом.
> Системе не удается найти указанный путь.
> Системе не удается найти указанный путь.
> echo   > .opt
> "test" не является внутренней или внешней
> командой, исполняемой программой или пакетным файлом.
> gcc -Wall -Wextra -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -O2 -MMD -Iinclude -Ithird_party -DZLIB -DUSE_TLS  -O0 -ggdb3 -g -DDEBUG   -c -o src/cmd/cmd_quit.o src/cmd/cmd_quit.c
> In file included from src/cmd/cmd_quit.c:20:0:
> include/wb_threads.h:22:22: fatal error: pthread.h: No such file or directory
>  # include <pthread.h>
>                       ^
> compilation terminated.
> <builtin>: recipe for target 'src/cmd/cmd_quit.o' failed
> mingw32-make: *** [src/cmd/cmd_quit.o] Error 1
> 
> C:\ESD\warfacebot-master>

**Comment by Levak** [comment]
You need a build system, either emulating GNU/Linux environment (e.g. Cygwin) or abstracting it (e.g. mingw). Either ways, I don't give support regarding compilation environment, it is specific to everyone.

Take a look at `.travis.yml` regarding how the automatic binary release cross-compilation for mingw works.

**Comment by nathan130200** [comment]
@CuBnIcK Use http://cygwin.com to build warfacebot in windows

**Comment by nathan130200** [comment]
Don't use git bash to compile, him don't support make, cmake and don't have package manager.

**Comment by CuBnIcK** [comment]
says the same error associated with include <pthread.h>

**Comment by nathan130200** [comment]
Replace \r\n windows for \r (Unix)

**Comment by nathan130200** [comment]
17
down vote
accepted
In the latest versions of gcc compiler require that libraries follow the object or source files.

So to compile this it should be:

gcc pthread_sample.c -lpthread
Normally though pthread code is compiled this way:

gcc -pthread pthread_sample.c

**Comment by CuBnIcK** [comment]
Maybe my hands are made of assholes, but I can not do it, can you throw me a worker with a debugger?

**Comment by nathan130200** [comment]
If you have 64 bits OS you need install 64 bits cygwin.

**Comment by CuBnIcK** [comment]
@nathan130200, i have 64 bit, but nothing has changed

**Comment by nathan130200** [comment]
Try make clean install of 64 bits cygwin

**Comment by nathan130200** [comment]
I Used following command `make debug-wb -j 4` (4 cores processor)

**Comment by CuBnIcK** [comment]
Spent the whole day and does not work =(

**Comment by nathan130200** [comment]
Check if pthread package are installed on cygwin

**Comment by nathan130200** [comment]
Cygwin x64 latest installer.

[setup-cygwin-x64.zip](https://github.com/Levak/warfacebot/files/1270053/setup-cygwin-x64.zip)

**Comment by alexalok** [comment]
> Your cygwin installation are compromised, pthread is part of basic install of cygwin.

I believe he has MinGW in his PATH, or is running MinGW's terminal.

**Comment by CuBnIcK** [comment]
@alexalok , fixed the MinGw in PATH, and set cygwin path, and:
src/stream/tls.c: 34: 26: fatal error: openssl/ssl.h: No such file or directory
  #include <openssl/ssl.h>

**Comment by CuBnIcK** [comment]
![](https://pp.userapi.com/c841137/v841137540/1911d/RSlPeagH8ws.jpg)

**Comment by nathan130200** [comment]
@CuBnIcK install openssl-devel in cygwin

**Comment by nathan130200** [comment]
@alexalok yes!
