### ISSUE TITLE
Say message in (InGame) chat room colored.

### ISSUE THREAD

**Issue by nathan130200** [Levak/warfacebot#124]
I execute `say <font color="#00ffff">follow me</font>` it displayed in game chat (warface br sync same message with lobby and ga
me) and it appear in `color aqua` i tried alternatives color:

![image](https://user-images.githubusercontent.com/14365254/29896726-8743bf2c-8db4-11e7-9b59-e68963f1b3c8.png)

Same as italic `<i>boa</i>`

![image](https://user-images.githubusercontent.com/14365254/29896735-95070a74-8db4-11e7-9d97-6654ed98b89a.png)

Green: `<font color="#00ff00">Checkpoint</font>` 
![image](https://user-images.githubusercontent.com/14365254/29896745-9e7eeb12-8db4-11e7-87f3-196a7f4d7099.png)

I do not know if it's really a bug, but since the players in Brazil are all told it's risky to report it as cheating (and probably the chance is 8/10 to take a ban after all LevelUp does not want to investigate if it's really cheating) . At least I'm using a fake account.

In Lobby only raw text:
![image](https://user-images.githubusercontent.com/14365254/29896949-49689a0a-8db5-11e7-9ca0-dba046ed48ea.png)

**Comment by Levak** [comment]
Forwarded to Crytek.
