### ISSUE TITLE
Authorization WF TR login and password

### ISSUE THREAD

**Issue by Deadfail** [Levak/warfacebot#125]
Hello.
Can make bot to the server  WF TR via the login and password?

**Comment by Levak** [comment]
Not possible due to the captcha.
You need to login separately and feed in the session token to the launcher.
There is no other way possible.

**Comment by Deadfail** [comment]
Seen this function 
MechCraft Bot

**Comment by Levak** [comment]
> Seen this function
> MechCraft Bot

Then ask them how they do it, if they want to contribute to the AGPLv3 project they are using.
