### ISSUE TITLE
Error in launcher on login

### ISSUE THREAD

**Issue by franchesko1437** [Levak/warfacebot#127]

**Comment by franchesko1437** [comment]
Levak? ignore?

**Comment by Levak** [comment]
I don't understand the error message as I do not know Russian.

**Comment by franchesko1437** [comment]
it is written there

Operation timed out

**Comment by Levak** [comment]
Is it working now?
Because on my side I have no issue.

**Comment by franchesko1437** [comment]
The program works, but occasionally this error occurs
