### ISSUE TITLE
com faço pra atualizar a versao do jogo no warfacebot

### ISSUE THREAD

**Issue by tutorhacks** [Levak/warfacebot#128]
olá, jogo no warface br, e nao estou conseguino usar o progama.
![warbot](https://user-images.githubusercontent.com/31813310/30250583-2d9d9f62-9627-11e7-92b5-3eb3aaca793d.png)

**Comment by ptaking** [comment]
Update your game version in `cfg/server/br.cfg` to the lastest version.

**Comment by nathan130200** [comment]
Já está atualizado só você clonar o repositório que já vai vir o `br.cfg` atualizado ou compilar do código fonte.

**Comment by nathan130200** [comment]
Provavelmente o seu  `br.cfg` não está na versão `1.15400.805.21500`

**Comment by Levak** [comment]
Hi @tutorhacks 
Has the question/issue been answered?

**Comment by Warpricee** [comment]
ola como faço para atualizar a versao dos bot pq o jogo atualizou hoje

**Comment by nathan130200** [comment]
@Warpricee não da ban, isso não é nenhum programa de trapaça, é so um emulador do warface para ajudar a iniciar partida solo.

**Comment by tutorhacks** [comment]
obg galera!!

**Comment by eddybanca** [comment]
the codes to start the match battleroyale pripyat / mojave does not work! help..
