### ISSUE TITLE
How to update game_crypt_key?

### ISSUE THREAD

**Issue by Viktor20217** [Levak/warfacebot#130]
How to get game_crypt_key without your update?

**Comment by Levak** [comment]
By decompiling and reverse engineering the game.

**Comment by Viktor20217** [comment]
That is, it's in the gaming client

**Comment by Viktor20217** [comment]
Russian game client updated.

**Comment by Viktor20217** [comment]
Can I have an approximate code location?

**Comment by Levak** [comment]
> Russian game client updated.

See #131

**Comment by Viktor20217** [comment]
Can you provide an approximate code location? Access to the game code is there I can not find
