### ISSUE TITLE
ALGUEM ME AJUDA PF ATUALIZAR A VERSAO 

### ISSUE THREAD

**Issue by Warpricee** [Levak/warfacebot#132]
ola como faço para atualizar a versao dos bot pq o jogo atualizou hoje no warface BR 
esse programa da BAN na minha conta ??

**Comment by nathan130200** [comment]
Respondendo suas questões:
1: Eu vou fazer commit da versão mais recente.
2: Não da ban, esse programa é pra ajudar jogadores a iniciar partidas sozinho, ele não usa nenhum arquivo do jogo nem injeta nada no jogo, ele é uma aplicação totalmente separada (é um emulador do warface).

Observação: Você pode atualizar manualmente a sua versão automaticamente no arquivo `/cfg/server/br.cfg` a versão mais recente você encontra no Game.log dentro da pasta do warface.

Outra coisa não use Capslock isso é irritante.

**Comment by Warpricee** [comment]
mas pra mim esta dando game version diferent eu estava usando ontem antes da att como atualizo pode me ajudar

**Comment by Warpricee** [comment]
esta dando game versao mismatch

**Comment by nathan130200** [comment]
Coloque essa versão na configuração: `1.15400.806.21500`

**Comment by nathan130200** [comment]
Corrigido em #133 e #134
