### ISSUE TITLE
game versao

### ISSUE THREAD

**Issue by Warpricee** [Levak/warfacebot#133]
ola esta dando game versao mismatch como faço para att ?  eu fiz oq vc disse entrar na pasta mas que versao eu ponho ? 

![sem titulo](https://user-images.githubusercontent.com/31254943/30454743-c57340f4-9973-11e7-949f-8f373892656a.png)

**Comment by nathan130200** [comment]
@Warpricee Voce precisa atualizar o seu br.cfg (na pasta  `<pasta do warfacebot>/cfg/server/br.cfg`) para a versão mais recente.

**Comment by Warpricee** [comment]
qual e a versao mais recente voce pode me ajudar para conseguir fazer isso ? mandar pra mim

**Comment by Warpricee** [comment]
e essa pasta que tem mexer ?

![sem titulo](https://user-images.githubusercontent.com/31254943/30455709-51d855fe-9977-11e7-8004-49fab4d14ab0.png)

**Comment by nathan130200** [comment]
Sim, abra ela e tem o arquivo br.cfg edite com o notepad++ e procure por game_version, logo após altere o que tem depois do igual para 1.15400.806.21500

**Comment by Warpricee** [comment]
ai o meu so tem isso dentro da pasta faço oq vc disse ?  

![xx](https://user-images.githubusercontent.com/31254943/30455805-a464398c-9977-11e7-9dac-f03fbab1bd0a.png)

**Comment by Warpricee** [comment]
agora foi mt obg :)

**Comment by nathan130200** [comment]
Sim é o arquivo `br`

**Comment by Warpricee** [comment]
mt obg vlw mesmo :)

**Comment by nathan130200** [comment]
De nada 👍
