### ISSUE TITLE
duvida

### ISSUE THREAD

**Issue by Warpricee** [Levak/warfacebot#135]
ola boa noite sera que teria como eu deixar tipo assim os bot logado e ficar iniciando sozinho a sala com minha conta pra pegar vitoria ?

**Comment by nathan130200** [comment]
Respondendo suas questões:

1: Não é possível iniciar automaticamente ele, só se você criar um programa que faça isso pra você.
2: Não o a conta bot não pega vitória pois essa conta não conecta no servidor dedicado e não participa da partida, só fica na sala, lembrando a conta bot é pra você conseguir iniciar uma sala sozinho.
