### ISSUE TITLE
WF RU hwid

### ISSUE THREAD

**Issue by Deadfail** [Levak/warfacebot#137]
Hello.
It is possible to make HWID changed itself randomly?

**Comment by Levak** [comment]
Why would you want to change HWID randomly at every launch?
It would be like changing PC on every logon, but on the same IP.

That being said, you can generate yourself a `wb.cfg` yourself before every launch. It's just a text file (e.g. open with notepad++).

```
echo 'game_hwid='$(cat /dev/urandom | tr -dc '0-9' | head -c9) >> wb.cfg
```

**Comment by Deadfail** [comment]
On one HWID first bot crashes

**Comment by Levak** [comment]
> bot crashes

This is expected behavior on RU/EU/NA where MRAC is there. Only 4 minutes of usage before disconnect.

**Comment by Deadfail** [comment]
Immediately crashes after launch second window(
![screenshot_1](https://user-images.githubusercontent.com/30199368/30515039-41ec4ca6-9b4b-11e7-8af1-75b0de16ca95.png)

**Comment by Deadfail** [comment]
After changing the HWID, you can run multiple bots

**Comment by Levak** [comment]
Interesting.
Can you launch 2 Warface games on the same computer with a sandbox? Or does it has the same effect?

> After changing the HWID, you can run multiple bots

You mean, giving 1 HWID per bot, or giving a new HWID identical for both bots?

**Comment by Deadfail** [comment]
For each bot your HWID

**Comment by Deadfail** [comment]
@Levak Video error https://youtu.be/Eavb6GS62Kk

**Comment by Viktor20217** [comment]
![image](https://user-images.githubusercontent.com/31064630/30518883-33c9f4fe-9bbc-11e7-8f81-701c14ab4910.png)

**Comment by franchesko1437** [comment]
@Levak SO?
![45](https://user-images.githubusercontent.com/29465298/31409669-629c7db8-ae15-11e7-8cab-71066c6c26c7.JPG)
