### ISSUE TITLE
how to view the source code wb.exe

### ISSUE THREAD

**Issue by franchesko1437** [Levak/warfacebot#138]
how to view the source code wb.exe
?

**Comment by Levak** [comment]
Where did you download `wb.exe`?
 - If you downloaded it from here, github, the sources were shipped with it, in the `src` folder.
 - If you downloaded it from third-party sources, like Mechcraft, you should ask _them_ the sources of it. If they refuse, they are violating AGPLv3 license of Warfacebot.

**Comment by franchesko1437** [comment]
Thank you, I found it. the question can be closed
