### ISSUE TITLE
gameroom_get

### ISSUE THREAD

**Issue by Viktor20217** [Levak/warfacebot#139]
How to use the bot to get information about rooms on all channels or on an active one?

**Comment by franchesko1437** [comment]
zamer skilla ejji

**Comment by Viktor20217** [comment]
@franchesko1437 вери велл инглишь .-.

**Comment by franchesko1437** [comment]
Левак игнорит почему-то(

**Comment by Levak** [comment]
This feature is not implemented for safety reasons.
