### ISSUE TITLE
@follow_accepted  follow not work

### ISSUE THREAD

**Issue by Viktor20217** [Levak/warfacebot#140]
![image](https://user-images.githubusercontent.com/31064630/30751068-d691bc9e-9fea-11e7-921b-aac825c02447.png)
The follow command does not work normally
@follow_accepted and the bot is closed

**Comment by Levak** [comment]
Sounds like a segmentation fault (crash).
Is it constant? Or random?
Can you send me via email the unmodified (full) screenshot, I would like to check the fields received from the server.

**Comment by Viktor20217** [comment]
Constantly
![image](https://user-images.githubusercontent.com/31064630/31046357-986fcf42-a629-11e7-8f06-df20b44de03b.png)

**Comment by Viktor20217** [comment]
The problem was solved in a strange way: I changed the language back to English. Some magic

**Comment by Viktor20217** [comment]
The problem was solved in a strange way: I changed the language back to English. Some magic

**Comment by Levak** [comment]
Found the root cause issue.
There was an invalid `free()` made on a constant string when a lang entry was missing.
Just added a string copy on that specific case, and it should work fine now.
