### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by franchesko1437** [Levak/warfacebot#146]

**Comment by Levak** [comment]
You need to compile Warfacebot first, using `make`.
If you are under Windows, you can download binary releases directly from here
https://github.com/Levak/warfacebot/releases

**Comment by franchesko1437** [comment]
curl installed, but the bug still remains

**Comment by Levak** [comment]
Type `curl` in your shell.
If it says "command not found" then it's not installed))

**Comment by franchesko1437** [comment]
Why is everything so difficult?
In the end, you just need to compile wb.exe for debug mod, but I do not understand what commands to use in cygwin, and what files to take from the src folder
