### ISSUE TITLE
no DLL 

### ISSUE THREAD

**Issue by VasekTryba4eB** [Levak/warfacebot#147]
Hi. 
I can't run this app.  Got DLL ERROR. 
http://prntscr.com/gtaqsc
http://prntscr.com/gtarg8
http://prntscr.com/gtarmb
http://prntscr.com/gtarzi
How to fix it?
I try to install Cygwin. But it not help. What exact  Packages i need to install ? Google it lot of time not help.

**Comment by Levak** [comment]
If you have compiled warfacebot using Cygwin, you need to copy all the DLLs it asks from Cygwin install dir to warfacebot directory (where `wb.exe` is).

**Comment by VasekTryba4eB** [comment]
Thank you mate. It work. Now Im stock on this screen ....  http://prntscr.com/gtck1f
Nothing happen just disconnected after some time

**Comment by Levak** [comment]
Did you download it "today"?
I've tested on Cygwin when releasing 1.0.11 few days ago, it worked fine (actually better than Mingw)

**Comment by VasekTryba4eB** [comment]
You mean warfacebot? No it was downloaded couple days ago

**Comment by Levak** [comment]
Then recompile in debug mode:
```
make clean debug-wb
```

And tell me where it gets stuck.

**Comment by VasekTryba4eB** [comment]
http://prntscr.com/gtcpun

I do something wrong i suppose

**Comment by VasekTryba4eB** [comment]
make - not found ;(

**Comment by Levak** [comment]
How did you compile warfacebot then?

**Comment by VasekTryba4eB** [comment]
I did it 6 month ago, just download new version from this site and rewrite

**Comment by VasekTryba4eB** [comment]
Any way i found easy solution for me https://github.com/Levak/warfacebot/releases
It work fin now . Thank you for this app mate. Very helpful thing ;)
