### ISSUE TITLE
quickplay invite  (bug)

### ISSUE THREAD

**Issue by Viktor20217** [Levak/warfacebot#149]
The quickplay invite does not work properly. The bot does not invite

No invites
![image](https://user-images.githubusercontent.com/31064630/31223413-d8a3ca06-a9fc-11e7-8cec-cf30a24a0bfa.png)

**Comment by KosmoSt4r** [comment]
Привет , есть вк?

**Comment by Viktor20217** [comment]
https://vk.com/viktorlol14

**Comment by Levak** [comment]
Should be fixed in d2e8acbeee2d6d021268e51b5d6e5c1063f993e3
New release: https://github.com/Levak/warfacebot/releases/tag/1.0.16
