### ISSUE TITLE
Lock Buddy list?

### ISSUE THREAD

**Issue by Deadfail** [Levak/warfacebot#151]
Hello.
It is possible to make that could not add bots to the list of friends?

**Comment by Levak** [comment]
https://github.com/Levak/warfacebot/blob/master/README.md#warfacebot-related-variables

**Comment by NKVDDDDD** [comment]
Ответь на почте, что за игнор?

**Comment by Deadfail** [comment]
wb_accept_friend_requests = 0
Replace by 1?

**Comment by Levak** [comment]
> Replace by 1?

No, set it to 0 in `wb.cfg`

**Comment by Deadfail** [comment]
@Levak Thank you)
