### ISSUE TITLE
Long comes into play

### ISSUE THREAD

**Issue by franchesko1437** [Levak/warfacebot#153]
Levak, please check. On a Russian server, the bot takes a long time to get into the game. and enters the room for a long time

**Comment by Levak** [comment]
You mean, on the loading screen the bot doesn't load and after 1 minute disappears?
This is an expected behavior if you set the `wb_leave_on_room_start` to `0`. If you really want it to stay in the room but not join the game session, in its console you can type `unready`.

**Comment by Viktor20217** [comment]
@Levak  Some teams are done for a long time

**Comment by Levak** [comment]
@Viktor20217 I don't understand your point, or I don't understand the main question.

What do you mean by "teams are done", like, some players are done loading? Yes, as I said, the game server will wait til all players are done loading, and having bots in the room in no-leaving-state prevents the game session from starting, until the timeout of 1 min comes into play.

**Comment by Viktor20217** [comment]
For example, I enter "ready" and it only works after 5-10 seconds

**Comment by Levak** [comment]
> For example, I enter "ready" and it only works after 5-10 seconds

Ah, then I am not aware of that problem, and is likely to be a server-side issue, IMHO.
Doesn't it do the same between players? When one player presses `Ready`, other players are notified only later?

FYI the room "status" are updated by the server-side once in a while. It used to be updated every time someone sent a new status, and would send the differences with the old state. Maybe as some sort of optimisation, they added a timer instead, like, "Gather updates for 5 seconds, if there is an update, send it".

**Comment by Viktor20217** [comment]
#149 Please note please

**Comment by franchesko1437** [comment]
Levak. the bot comes into play for a long time. about 25-30 seconds, and before that it was 3-4 seconds. It started on 07.10.17 at 17:00 Moscow time. This problem is observed in many people.

**Comment by Levak** [comment]
> Levak. the bot comes into play for a long time. about 25-30 seconds

You mean that the bot _connects_ into the game lobby (friendlist) only after a delay?

**Comment by franchesko1437** [comment]
no. entrance to the gaming client

**Comment by Levak** [comment]
> no. entrance to the gaming client

But bots do not join game sessions. They only operate in lobby.

**Comment by franchesko1437** [comment]
I'll add a video. wait 5 minutes

**Comment by franchesko1437** [comment]
@Levak https://cloud.mail.ru/public/B4gi/bm2tbE6Gd

**Comment by Levak** [comment]
I .... don't see anything wrong there?
It is just the latency between you and the lobby server.
Can't be faster unless you have better latency, or that lobby servers are less overloaded.

**Comment by franchesko1437** [comment]
This is problem. 6.08 they entered the game immediately after 3-4 seconds, and now they are loaded for a long time (displayed in the video). At the moment, they work better, in the morning it was 30 seconds

**Comment by Levak** [comment]
> At the moment, they work better, in the morning it was 30 seconds

As I said, this is directly linked with your latency to lobby server OR load of lobby server. There is nothing that can be done in warfacebot to speed the server :>

**Comment by franchesko1437** [comment]
This problem is observed in all my friends who use the bot. long entry into the game began at the same time.

Likely. This problem is from )m(fail.ru
