### ISSUE TITLE
[TR] Use login and password instead of token?

### ISSUE THREAD

**Issue by Deadfail** [Levak/warfacebot#154]
Hello.
Can make bot to the server WF TR via the login and password?
No captcha)
![screenshot_1](https://user-images.githubusercontent.com/30199368/31350300-da009c60-ad50-11e7-9c10-26a24f767c96.png)

**Comment by Levak** [comment]
AFAIR, when you try to login there, it will ask for your captcha, always.

**Comment by Deadfail** [comment]
The site removed captcha.
During authorization
https://www.warface.com.tr/en

**Comment by Levak** [comment]
I cannot display the page, it says the .tr domain has expired.

**Comment by Deadfail** [comment]
They have today with the website problems.

**Comment by Deadfail** [comment]
Değerli Oyuncularımız, Websitemizdeki ve Başlatıcımızdaki Sorunun Farkındayız; En Kısa Zamanda Sitemiz Yeniden Hizmete Girecektir! Anlayışınız İçin Teşekkür Ederiz.
![screenshot_2](https://user-images.githubusercontent.com/30199368/31354662-4a1a6570-ad61-11e7-880c-b66d8b271ea6.png)

**Comment by Deadfail** [comment]
@Levak The site has earned.
No captcha)
![screenshot_1](https://user-images.githubusercontent.com/30199368/31394636-012f7aa0-ae09-11e7-8bdd-4d9daff7f75b.png)

**Comment by Levak** [comment]
Okay, the captcha code is still there, but it seems unused.
Not sure if this is intentional or not, nonetheless I pushed the revert to go back to email+pass.

**Comment by Deadfail** [comment]
@Levak 
![screenshot_1](https://user-images.githubusercontent.com/30199368/31427157-89be41d0-ae90-11e7-8a69-32512dbb329f.png)
Invalid URL-adres
