### ISSUE TITLE
ola como faço pra atualizar minha versao 

### ISSUE THREAD

**Issue by Warpricee** [Levak/warfacebot#156]
ola o game att hoje aqui no br como eu faço pra att a versao do bot pra mim poder usar ??

**Comment by nathan130200** [comment]
@Warpricee Segue o mesmo em #132

**Comment by BrenoDh** [comment]
Entra na pasta do seu warface,Abra um arquivo  chamado  "Game.log" em algum editor de texto e procura uma linha que está escrito "FileVersion" logo a frente vai estar o número da versão. Em seguida na pasta de seu bot abra a pasta cfg em seguida server, dentro vai ter um arquivo chamado br.cfg. Logo a frente de game_version você cola a versão que você copiou do arquivo "Game.log".
