### ISSUE TITLE
How do I change a mission with a command?

### ISSUE THREAD

**Issue by franchesko1437** [Levak/warfacebot#157]
How do I change a mission with a command?

**Comment by Viktor20217** [comment]
#143

**Comment by franchesko1437** [comment]
Там нету команды для смены миссии. Только команда для ее создания

**Comment by Viktor20217** [comment]
Ты эту команду написал шапке вопроса.

**Comment by franchesko1437** [comment]
тю. это как со сменой карт на пвп?
change tdm_anubiseasy2 ?
