### ISSUE TITLE
Update ru server 25/10

### ISSUE THREAD

**Issue by franchesko1437** [Levak/warfacebot#162]
Hi Levak. Russian server updated. Could you make a new game crypt key?

**Comment by nevyvoz** [comment]
Чекай патчноут к обнове: 

> Устранена группа критических уязвимостей сервера.

**Comment by franchesko1437** [comment]
Речь идет о других уязвимостях. если что

**Comment by 1bot1** [comment]
I join the request to update the Russian Warface.
At the moment this is the Halloween version of the game 1.16100.1456.41200
Thank you in advance for your work and your time.

**Comment by Levak** [comment]
Updated in 4d6d561

**Comment by franchesko1437** [comment]
Thanks Levak. many thanks

**Comment by franchesko1437** [comment]
Thanks Levak. Many thanks
