### ISSUE TITLE
Game update ru

### ISSUE THREAD

**Issue by Lemon5** [Levak/warfacebot#164]
Hello to you. When will the update game_crypt_key ?
![2017-10-27_121032](https://user-images.githubusercontent.com/33143851/32088811-698321a6-bb10-11e7-88ea-d2214d12ee08.png)

**Comment by Levak** [comment]
See #162

**Comment by Lemon5** [comment]
Sorry for my inattention

**Comment by Lemon5** [comment]
Changed the version of the game- game_crypt_key.
![2017-10-30_133852](https://user-images.githubusercontent.com/33143851/32157757-1db3aca4-bd78-11e7-92f5-8eb7a8843f36.png)

**Comment by Levak** [comment]
Fixed in 36de0418b33ff337c8a038861e24e1c8643c7ce7
