### ISSUE TITLE
WF-TR Error running

### ISSUE THREAD

**Issue by Deadfail** [Levak/warfacebot#168]
Hello.
Error running OS Win-7 ultimate.
![screenshot_1](https://user-images.githubusercontent.com/30199368/32299364-f4bad09a-bf87-11e7-8e84-04caca15f850.png)

**Comment by franchesko1437** [comment]
I had a similar problem, when the Internet worked badly. Check the connection quality

**Comment by Deadfail** [comment]
Internet connection is good

**Comment by franchesko1437** [comment]
If the Internet is slow, then it happens. For your eye, such interference is not noticeable, but for the program yes

**Comment by Deadfail** [comment]
On Windows 10 works

**Comment by Levak** [comment]
Well, I can't help you guys much other than telling you to use the older version;
https://raw.githubusercontent.com/Levak/warfacebot/1d61d920baf8dcb16ed3b845cb6d75001e740e50/wb_launcher.hta


Error -2147012891 is Error_Internet_Invalid_URL.
Further debugging is required from your side.
I confirm it to be working fine on Win10.
