### ISSUE TITLE
bot pvp quickplay

### ISSUE THREAD

**Issue by Deadfail** [Levak/warfacebot#169]
![screenshot_2](https://user-images.githubusercontent.com/30199368/32414047-017df570-c251-11e7-87a1-ec57dd270ffe.png)

No bot, no such error.

**Comment by Levak** [comment]
I am aware of this, just never pushed the fix.
They changed the Quickplay logic couple updates ago.

Simple fix: Don't use preinvite with a bot.

**Comment by Deadfail** [comment]
@Levak Will the hotfix?

**Comment by Levak** [comment]
Should be fixed in d2e8acbeee2d6d021268e51b5d6e5c1063f993e3
New release: https://github.com/Levak/warfacebot/releases/tag/1.0.16
