### ISSUE TITLE
Running bot in hong kong server (EU)

### ISSUE THREAD

**Issue by mdn522** [Levak/warfacebot#176]
How can i run the bot in hong kong server?

**Comment by Levak** [comment]
There is no Hong Kong "server". There is a regional dedicated server in HK for EU and NA. There is a private server for China. There is a server in Thailand.

Which one are you talking about?

**Comment by mdn522** [comment]
yeah im talking about dedicated region

**Comment by Levak** [comment]
Then simply use `online_region_id`:

```
$ ./wb.sh -donline_region_id=hongkong
```

List of supported regions are in `QueryCache/get_configs.xml` (after a first successful connection to a lobby server)
