### ISSUE TITLE
Can't connect on Ubuntu

### ISSUE THREAD

**Issue by coolnickname** [Levak/warfacebot#177]
I followed your step by step guide to building and running the bot, but when I try to run the bot I get this error:
```
duck@611gntxx:/games/wf/warfacebot$ sh ./wb.sh eu
Login: [redacted]
./wb.sh: 25: read: Illegal option -s

Connecting...<?xml version="1.0" encoding="UTF-8"?><Error Status="200" ErrorCode="2" MinVersion="140"/>
failed

```

The first time logging in is fine, but the second time I get this.
Also note how I did not get the option to enter my password.

EDIT: Update error.

**Comment by coolnickname** [comment]
It seems to be caused by the `-s` argument in the password promt. I just hardcoded the passwords for now.

**Comment by coolnickname** [comment]
So I got this new issue: I get kicked after a small while, similar to #111 but on EU. However I don't understand what the solution is since most of it is in Russian.

**Comment by Levak** [comment]
Option `-s` is silent mode.
Error=3 (the first you had) is wrong email or password. Not sure about Error=2.
Regarding the kick after 10sec, you need to set `game_hwid` and this is undocumented. Kick after 4min is MRAC heartbeat (unimplemented for obvious reasons).

**Comment by Levak** [comment]
Is this issue (not about MRAC, but about the `-s` thing) still happening?
Else, I close this issue.
