### ISSUE TITLE
Russian client updated the game to version 1.16300.1477.41200

### ISSUE THREAD

**Issue by 1bot1** [Levak/warfacebot#178]
Hi.
Again, the standard request - update the key data for the new version of the game, Russian.

**Comment by Levak** [comment]
Perhaps you forgot a "please"? :)

**Comment by 1bot1** [comment]
PLEASE.
It's not a problem   ;-)

**Comment by franchesko1437** [comment]
Levak. big please. post a new one game crypt key

**Comment by Levak** [comment]
Updated in effec1c

**Comment by franchesko1437** [comment]
Thanks
