### ISSUE TITLE
como mudar pros bot poder aceitar convite

### ISSUE THREAD

**Issue by Warpricee** [Levak/warfacebot#182]
como faço pra fazer aceitar os bot sem eles ficar recusando

**Comment by Levak** [comment]
By default, bots should accept all friend/clan requsts.

Edit `wb.cfg` to your needs:

```
wb_accept_friend_requests 1
wb_postpone_friend_requests 0
wb_accept_clan_invites 1
wb_postpone_clan_invites 0
```

**Comment by Warpricee** [comment]
ei tem como eu deixar eles tipo pra ficar na sala automatico ele inicia e volta pro looby pra mim pegar vitoria mais rapido  ?

**Comment by Warpricee** [comment]
tipo eles entrar na sala e quitar sem precisa desarmar a bomb pra poder pegar vitoria ?

**Comment by Levak** [comment]
Bots do not join the game room.
Bots are only used for lobby actions, not cheating/farming in game.

**Comment by Warpricee** [comment]
mas tem como eu deixar tipo assim automatico pra mim  n poder ficar convidando eles ?     e pegar vitoria rapido ?

**Comment by nathan130200** [comment]
@Warpricee esse bot so serve pra você iniciar partida sozinho.
