### ISSUE TITLE
EU login failed with last windows binaries

### ISSUE THREAD

**Issue by albatror** [Levak/warfacebot#183]
just download your last windows binaries release from here, (pc updated/account veryfied/firewall opened) and trying to login with EU server but authentication failed. Can yu tell me what is wrong ?

**Comment by Levak** [comment]
By "authentification failed", do you mean the launcher popup, or the bot console error when it tries to connect (after launcher logged you in successfully)?

In the first case, I would say you have entered the credentials wrong, or have special characters in either email or password which might cause issues (I know it happened in the past, and had to fix it).

The second case looks like a blocked (banned) account. Are you able to log in the game up to lobby server using the official launcher and game client?

**Comment by albatror** [comment]
sry my bad because not explain, with a screen you will see more clearly. Yea first popup lauchned but it seem not find a file when try to login.
https://img15.hostingpics.net/pics/801926warfacebotwindows.png
Account is clean mean not banned or suspicious, no special characters with email or password.

**Comment by Levak** [comment]
> sry my bad because not explain, with a screen you will see more clearly. Yea first popup lauchned but it seem not find a file when try to login.

This is another error. You need to download binary releases, not source code.
e.g. https://github.com/Levak/warfacebot/releases/tag/1.0.11

From there, you'll probably have to update server configuration, with the up to date files (non-binary):
https://github.com/Levak/warfacebot/tree/master/cfg/server

**Comment by Levak** [comment]
No answer. Closing
