### ISSUE TITLE
Trying to compile and start it on debian 9

### ISSUE THREAD

**Issue by albatror** [Levak/warfacebot#184]
```
$ make
echo   -DHAVE_STRNDUP > .opt
gcc -Wall -Wextra -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -O2 -MMD -Iinclude -Ithird_party -DZLIB -DUSE_TLS -pthread -DHAVE_STRNDUP   -c -o src/threads/thread_readline.o src/threads/thread_readline.c
src/threads/thread_readline.c:29:31: fatal error: readline/readline.h: No such file or directory
 #include <readline/readline.h>
                               ^
compilation terminated.
<builtin>: recipe for target 'src/threads/thread_readline.o' failed
make: *** [src/threads/thread_readline.o] Error 1
```

after:
```
 ./wb.sh eu
login: *******
password: *******
./wb.sh: line 231: ./wb: No such file or directory
```
any suggestion?

**Comment by albatror** [comment]
after ./wb.sh eu
login: *******
password: ******* 
./wb.sh: line 231: ./wb: No such file or directory
any help?

**Comment by Levak** [comment]
As the compilation error says, you are missing development headers for `libreadline`, and probably for others too, like `libssl` and `libzip`.
Depending on your GNU/Linux distribution, something like this will work:
```
$ sudo apt-get install libreadline6-dev libssl-dev libzip-dev
```

Using synaptic might help to find the proper packages names.

Regarding the second error, as it says, you didn't compile warfacebot, hence the final binary cannot be found.

**Comment by albatror** [comment]
In advance thanks for yur quick answer. after installed install libreadline6-dev libssl-dev libzip-dev. Everything is ok and files are compiled.
Started ./wb.sh eu
`Connecting...done
g_language = english
game_hwid = 1
wb_accept_friend_requests = 1
wb_postpone_friend_requests = 0
wb_accept_clan_invites = 1
wb_postpone_clan_invites = 0
wb_enable_invite = 1
online_server = eu-comm.wf.my.com
game_manual_profile_creation = 1
game_server_name = eu
game_version = 1.16300.214.34300
game_crypt_iv = 834724096,29884556,849283813,14157667,779975000,969872986,327122214,893084885
game_crypt_key = 1400692902,3297832865,928379896,818598317,45804195,3507950025,1035613402,2645663840,4198482958,866859536,4277418528,727224620,3073710074,1550630899,1444536919,3261713156,2333538813,228825682,2504045629,1350593890,847558553,2624482135,3134498838,2058089070,2317994029,429922131,1320769451,2488371340,140759811,2576300383,3196323222,2443192743
Required option: `--id`
USAGE: ./wb  -i|--id <online_id>
             -t|--token <token>
            [-d|--define <name=value>]
            [-f|--load-file <path>]
            [-h|--help]

`
then it close.
Do i need to do a special command ? (regarding to your readme file, sry to ask)

**Comment by Levak** [comment]
> Do i need to do a special command ? (regarding to your readme file, sry to ask)

As you posted in the first post, you need to use launch `./wb.sh eu` and not `./wb eu` :)
`wb` is the binary, while `wb.sh` is the Bash launcher.

**Comment by Levak** [comment]
Any news on your problem? Where you able to figure it out, find the source of it, or gave up?
