### ISSUE TITLE
problem with start program

### ISSUE THREAD

**Issue by tokentroken** [Levak/warfacebot#189]
hallo lev.
i  have a problem with your program.if i start the program next come failed window.here u can see:
i have win 10 64b

https://cdn.discordapp.com/attachments/354211298764128256/390168539488714772/unknown.png

**Comment by tokentroken** [comment]
at start of the program there is a mistake :unable to find/excute wb.exe

**Comment by Levak** [comment]
> at start of the program there is a mistake :unable to find/excute wb.exe

This error shows up because you need to compile warfacebot, or download the binary releases.

**Comment by tokentroken** [comment]
at start of the program there is a mistake :unable to find/excute wb.exe

**Comment by tokentroken** [comment]
how can i download where is link pls give me link

**Comment by tokentroken** [comment]
i have download warface-master and i have starting wb_launcher.hta --- i give email and passw next come mistake unable to find/excute wb.exe

**Comment by 0x23F435D** [comment]
You need "wb.exe" 
Download WB - http://rgho.st/7Qm274mwB (Press СКАЧАТЬ)

**Comment by 0x23F435D** [comment]
And add WB.exe to bot files

**Comment by tokentroken** [comment]
warfacebot-mingw-1.0.11 there is a folder in which there are all files including wb.exe and wb_launcher.hta
i start wb_launcher.hta give  email and pass next come mistake .to what folder it is necessary to move wb.exe?

**Comment by Levak** [comment]
Did you extract the `warfacebot-mingw-1.0.11.zip` before launching `wb_launcher.hta`? Otherwise, it won't work, yes.

**Comment by tokentroken** [comment]
well of course I have taken all files and have pressed start wb_launcher.hta then I have set mail and the password фтв in several seconds there is the same mistake

**Comment by Levak** [comment]
No answer, closing.
