### ISSUE TITLE
Not work on  Windows 7x64

### ISSUE THREAD

**Issue by 0x23F435D** [Levak/warfacebot#190]
Not work on Windows 7 x64, there is a window with an error at startup, and on windows 8 or 10 everything works. Levak please make an assembly for windows 7
Screenshot : https://prnt.sc/hmjvqn

**Comment by 0x23F435D** [comment]
when you open the launcher error appears "script  error"

**Comment by 0x23F435D** [comment]
The error only on Windows 7, with 10-8 problems is not present, you can itself try for Windows 7, and to correct errors

**Comment by Levak** [comment]
> The error only on Windows 7, with 10-8 problems is not present, you can itself try for Windows 7, and to correct errors

Thing being, I do not have Windows 7 anymore, so I cannot reproduce what you're experiencing.

**Comment by 0x23F435D** [comment]
You can use a virtual machine to fix errors

**Comment by Levak** [comment]
> You can use a virtual machine to fix errors

I do not have Windows 7, why would a VM help if I don't have a key for it?
You are welcome to contribute.

**Comment by 0x23F435D** [comment]
I'm poorly pliziruyus in programming, but in order to install Windows 7 does not necessarily have a key, ok I understood you Levak, thanks for the chat

**Comment by franchesko1437** [comment]
Если ты не понимаешь, значит оно тебе не нужно (с) levak
Приобрети мечкрафт и спи спокойно

**Comment by Levak** [comment]
Try this updating Internet Explorer:
https://www.microsoft.com/en-us/download/internet-explorer-11-for-windows-7-details.aspx(edited)

**Comment by Levak** [comment]
No answer, closing.
