### ISSUE TITLE
client RU 1.16500.1501.41200

### ISSUE THREAD

**Issue by 1bot1** [Levak/warfacebot#194]
Good afternoon.
You can easily update the version for the Russian client?
Update has been released 1.16500.1501.41200
Thank in advance.

**Comment by franchesko1437** [comment]
Levak forgot about the update(

**Comment by Lemon5** [comment]
Thanks Levak, the Russian audience is always waiting for your current update.
It's good to be an intelligent person, + to you in karma.
_Eh translit does not convey the joy that you bring. All the same, the English language is stingy on emotions and in Russian mate))_

**Comment by 1bot1** [comment]
Thanks for the update. Very timely.
