### ISSUE TITLE
Arx Warface does not start

### ISSUE THREAD

**Issue by MrKra6s** [Levak/warfacebot#196]
arx does not start warface most likely have updated the keys
77.220.184.171 this is a new address server may be need
![default](https://user-images.githubusercontent.com/35267039/34729415-a6da28a0-f56d-11e7-91b5-383044c1194f.jpg)

**Comment by MrKra6s** [comment]
77.220.184.171 this is a new address server may be need

**Comment by Levak** [comment]
Hi,

Technically speaking, ARX is not supported by Warfacebot, as the message suggests "unimplemented".
The "technical" reason being, that there is no launcher for it (`wb.sh` or `wb_launcher.hta`).

From your message, it may sounds like you have made the necessary modifications to the launcher to launch it? If so, contributions are always welcome.

**Comment by Levak** [comment]
No answer, closing.
