### ISSUE TITLE
warface bot k/d

### ISSUE THREAD

**Issue by furkanp34477** [Levak/warfacebot#198]
kill / death 
is it OK ?
oto space is death
dead person, space press?
bad english sorry man
exsample:
K/D:1.300

**Comment by Levak** [comment]
I have no idea what you are asking for.

That the bot joins in the game room so that you can farm it? Not possible
That the bot displays the K/D of other players? Possible but not implemented.

**Comment by furkanp34477** [comment]
Bot killed

**Comment by Levak** [comment]
> Kd yes

> Bot killed

Nothing of what you say makes sense.
Closing.
