### ISSUE TITLE
levak tr error help me

### ISSUE THREAD

**Issue by furkanp34477** [Levak/warfacebot#200]
CHANNEL ERROR İNVALİD TOKEN OR USERİD HELP ME

**Comment by furkanp34477** [comment]
LEVAK HELP ME TR DON'T WORK
authentication failed
closed dispatch
closed ping
read:end of stream
closed readstream
cmd# 

help me @Levak

**Comment by Levak** [comment]
I cannot reproduce, since TR is region-blocked. Are you still having this issue?
