### ISSUE TITLE
Possible license violation

### ISSUE THREAD

**Issue by ElezClub** [Levak/warfacebot#208]
Hello, Levak. I'd like to inform you that an active community user [LacosS](https://github.com/Levak/warfacebot/issues?utf8=✓&q=author%3ALakosS) has made a fork of your bot without providing any source code - for his launcher (C#) nor for his modifications to original wb code. 
You can find a topic about his bot [there](https://chitachok.ru/threads/54949/), where he openly says that his work is based on your bot, yet no info about license compliance is mentioned.
If you need any assistance contacting the author by means other than his GitHub, as well as help in translation, feel free to contact me.
He also uses a crapware installer to profit from downloads.

**Comment by Levak** [comment]
Hi,
Thanks for the notice.
I guess you are referring to that post[1] where he mention what he "did" in addition to warfacebot.

My main questions to him:
 - Has he recompiled the binary that is there[2]
 - If no, then he is fine with simple mentions.
 - If yes, has he modified the source code?
 - If no, then he is fine with simple mentions.
 - If yes, has he released the modified sources under the AGPLv3 terms?
 - If no, then he should do it ASAP so that I can merge his work here.

In any case, his C# launcher can stay closed source, as long as the `wb.exe` file is left standalone.

"Modified sources" includes all files visible on the repository[3], especially:
 - The `cfg/lang/` folder;
 - The `src/` and `include` folders;

[1]: https://chitachok.ru/threads/54949/page-7#post-395875
[2]: https://github.com/Levak/warfacebot/releases/tag/1.0.11
[3]: https://github.com/Levak/warfacebot

**Comment by ElezClub** [comment]
> Has he recompiled the binary that is there
Yes, he also provides an ability to obtain a special version where a predefined user profile is scrambled (as far as i understand, he recompiles the source per each such request).

> If yes, has he released the modified sources under the AGPLv3 terms?
He released no sources - even for a version without scrambles

> The cfg/lang/ folder
He changes these files extensively so that they work with his custom updater (which is distributed with crapware as well)

He also mentioned a new custom function that he will be releasing soon - that is spam in global chat, which I suppose required source code modification as well.

**Comment by LakosS** [comment]
Hi, I removed the unnecessary, do not change the source code, and wrote a launcher in c#. Which only runs your bot to change the language. The license is yours software free. I made an addition that came in Russian, and changed the translation. + added support for windows 7.

The license is yours - and I only created a launcher updated the wb.exe(nothing changed), added the language(fixed some bugs your - ru) and all.

**Comment by LakosS** [comment]
Spam in the General chat will not. I did the automatic update from github (your warfacebot). I myself am Russian, and I respect you.

**Comment by LakosS** [comment]
Your source code, I added "cmd" , "translation" , "translation .hta" and all. The rest is yours. Yes , I can do under the order(free) the change of the profile. But again, your license is not violated. When you start , spell your license.

**Comment by LakosS** [comment]
Sincerely, #Lako.

**Comment by Levak** [comment]
> The license is yours - and I only created a launcher updated the wb.exe(nothing changed), added the language(fixed some bugs your - ru) and all

Is the LICENSE file shipped with wb.exe?
If not, you should.

> , I added "cmd" , "translation" 

You.... Added things to wb.exe?
It is hard to understand if the files wb.exe and cfg/lang/" are different than the ones in Release 1.0.11.
"removed the unnecessary", like?

> Spam in the General chat will not

I reported the flaw to crytek anyway.

**Comment by LakosS** [comment]
I don't want spam in the General chat. The license file is, as in wb.exe.

**Comment by LakosS** [comment]
Is it possible to release the software next? It's free, and the license file has the license to wb.exe is, in hta - is.
[I myself am Russian, and I write with translator.]

**Comment by LakosS** [comment]
Spam is only possible in private messages or anywhere else. I would be glad if you allowed me to continue to develop "free software" with an indication of your authorship. I do prefer, for the sake of people.

**Comment by Levak** [comment]
> Is it possible to release the software next? It's free, and the license file has the license to wb.exe is

Unmodified wb.exe along with its LICENSE file next to it, is ok.

Regarding the mistakes you mention in cfg/lang/, I'll be happy to merge them.
Same goes for what you mention as "fix for windows 7".

**Comment by LakosS** [comment]
I found a bug in Internet Exploler on Windows 7. Only need install Internet Exploler v11 and all. + I support "Fan Bot's" and help people with errors.
I will be glad to continue to develop a "Fan Bot's' for your approval.
:)

**Comment by LakosS** [comment]
Can I continue to develop Fan Bot's?

**Comment by ElezClub** [comment]
> Can I continue to develop Fan Bot's?

This is by no means an official answer, but as long as you provide full source code for your modifications (as a separate download or as a project fork) and ship LICENSE file with your package, you should be able to develop/distribute your modification.

> Yes , I can do under the order(free) the change of the profile. But again, your license is not violated. 

It is violated, since no source code for modified wb.exe binary provided (checked by hash sum)

> Can I continue to develop Fan Bot's?

What's the point in asking, if you just released another version without waiting for a statement from Levak?

> You can download(I'm on 1.8 give a link(rg.host)) to see all functions.

On rg.host you provide a text file containing links to malicious websites that package crapware with the installer. The reason why you do that is because those websites are banned by youtube and other social networks so that you cannot link them directly.

**Comment by LakosS** [comment]
Levak, let me gather "wb.exe" and I will invest in "Fun Bots", then everything will be OK? I changed only wb.cfg.

**Comment by ElezClub** [comment]
Author has provided sources for his modification, which can be obtained here: http://rgho.st/8sD5d6cL2 (.rar file).

**Comment by Levak** [comment]
@ElezClub Thank you.

I have performed a diff to understand what was modified:

 - `src/wb.c` to add "Modified by Lako, 2018"
 - `wb_launcher.hta` to add #66, translate it to Russian, and remove AGPLv3 license header
 - `cfg/lang/russian.cfg` to add missing entries and change some other fields (some are insults/jokes)
 - `wb.cfg` to change the language to `[RU] by #Lako` and HWID to a static one (one per folder), which suggests why "custom builds" are a thing. Just changing the HWID.
 - Removal of `README.md`

What was added:
 - Files from Cygwin runtime, which suggests @LakosS recompiled it using Cygwin
 - `command/` folder, to put additional cfg files, e.g. stats
 - `s-*.cmd` a batch script to start `wb_launch.hta` for the bot
 - `#Lako.dll` which is ... a base64 encoded message to say "hello lucky" in Russian and some nice words to me, I guess.

I've integrated in 84a18af some of the changes made to `cfg/lang/russiang.cfg` and `wb_launcher.hta`.

@LakosS in the future, you can work with just 1 copy of the warfacebot folder if you the only thing you want to change is the HWID. `wb.cfg` is just the default configuration file. You can give it a new one by adding `-f bot_1.cfg` to the `wb.exe` command line.

@LakosS In the future, you need to understand:
 - Modifying sources of an open source project (here under AGPLv3) is ok, distributing the modified program is ok, but you have to provide a way where to download the sources of your modifications (like you ended up doing). APGLv3 also requires that server-sided modification hidden behind a service provide modified sources and mention the license/program/authors;
 - You are allowed to continue your work, under the AGPLv3 terms, which I have summarized on the previous point.

Case closed.
