### ISSUE TITLE
Stuck at <starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'/> 

### ISSUE THREAD

**Issue by alexalok** [Levak/warfacebot#21]
For reference: http://www.unknowncheats.me/forum/1510679-post553.html

Whoever is here from google: this bug is known and is being investigated.

**Comment by Levak** [comment]
A temporary fix has been added on branch `fix-race-condition-tls` 02bdb979e0d6b48a543ef56ab060b355a2b2f93f.
If you happen to test it and confirm you don't have anymore the issue I will gradually integrate it with other reworks involving the Readline thread later.

Thanks.

**Comment by alexalok** [comment]
I can confirm that the fix resolves the issue.
Tested on cygwin, fedora, centos and debian (all x64, last versions).

**Comment by Levak** [comment]
Another fix is deployed in adfc5ba7b7fe1021a8b23cebc0ba7ef9c4e9dd28
Once you confirm you have no more issue on your side, I will close the issue.

**Comment by alexalok** [comment]
I've ran tests on all configurations mentioned in my previous post and I can confirm that after 1 hour of running bots with constant restarts every 2 minutes, there wasn't a single issue. 
We can assume the matter resolved now. Hooray! :D

**Comment by Levak** [comment]
Good, thanks.
