### ISSUE TITLE
Add TR translation

### ISSUE THREAD

**Issue by furkanp34477** [Levak/warfacebot#210]
wb.exe "Starting TLS Connection."
"done."
turkish
"TLS Baglantisini Baslatma."
"Tamam."
would you ? change ?
and 
Warfacebot Copyright levak borak ..... ..... .....
all remove ? 
make wb.exe share ? (Turkey)

Given to 2 days Turkish.cfg (langue)

**Comment by Levak** [comment]
You cannot remove the copyright notice.
If you want to recompile and redistribute warface bot, you need to provide **full** source code.

**Comment by furkanp34477** [comment]
[turkish.zip](https://github.com/Levak/warfacebot/files/1672925/turkish.zip)


@Levak  turkish.cfg :)

add :)
@Levak 
BUT
"Starting TLS Connection."
"done."

Change is Failed :(

**Comment by furkanp34477** [comment]
@Levak 
visiual studio open you project
error #include <wb_log.h> help 
can you give your project with a .sln extension?

**Comment by furkanp34477** [comment]
Ha?

**Comment by Levak** [comment]
I've added your `turkish.cfg` to the repository. Thanks 👍
