### ISSUE TITLE
Bot not online on console

### ISSUE THREAD

**Issue by Fett244** [Levak/warfacebot#211]
Hi Levak,

i just install all the package, run and get the console that pop like this, but bot still not online.
I have refresh cfg directory ... 
[ bot account is up, lvl 7 ]
![wfbot issue](https://user-images.githubusercontent.com/36049397/35695538-188dd036-0785-11e8-9477-39aad55ca708.jpg)
Thx for help

**Comment by Levak** [comment]
Which version did you download?
Because I don't see in the logs of the console the `game_crypt_key` showing as defined in here:
https://github.com/Levak/warfacebot/blob/master/cfg/server/eu.cfg

Make sure to use at least 1.0.11
https://github.com/Levak/warfacebot/releases/tag/1.0.11

**Comment by Fett244** [comment]
hi,

i just download the last version and recompil the whole project and it just work fine ....
Thx for help.
