### ISSUE TITLE
How to check my skill level using your bot?

### ISSUE THREAD

**Issue by AzizjanT** [Levak/warfacebot#212]
Hi! Some people on RU server use your bot to check skill level (pvp-quickplay) - ![image](https://user-images.githubusercontent.com/14912415/35765548-c7ac2ee2-08e7-11e8-8ebb-0f9a451aa955.png)

But they don't want to say how to do it. So, can you help to know how can I see my skill-level using your bot?

And one issue - when I type whois command to bot it crashes, how can fix it?

**Comment by Levak** [comment]
Hi,
Skill level is a parameter used for the Matchmaking in Quickplay PvP. What we call "HMMR" (Hidden Match Making Rank).
Toput it shortly, the value is based on the consecutive number of wins/loses in Quickplay PvP using a positively skewed distribution to determine what is the difference to add to the current skill value. In a perfect world, it represents the skill, but in Warface, well it is highly influenced by follows/invites in some scenarios I will not details: One can have a skill value of 15k and a KDR of 3, but still be a noob and terrible teammate :D 

Now that you know that this value is meaningless, and is as accurate as KD is (that is, very inaccurate), Warfacebot can be used to get that value if you recompile it in debug mode `make -B debug-wb`. Then you need to follow yourself in a quickplay room with the bot, and dump the `<gameroom_sync>` query content, look for your name, and you'll see your skill value.

Again, skill value is as worthless as KDR.
