### ISSUE TITLE
Help with a quick game

### ISSUE THREAD

**Issue by franchesko1437** [Levak/warfacebot#214]
How do I start a specific map search in a fast game? let's say a general team battle.
I entered the command, but gives out errors and does not want to search.
In order for the bot to stay in the room I write a command "Stay"
Please write a command to search for a fast game. do not link to readme
In the same mechcraft it is implemented by one command

**Comment by Levak** [comment]
> How do I start a specific map search in a fast game?

Everything is written in the README.md

>  In order for the bot to stay in the room I write a command "Stay"

In Quickplay, "stay" is usually a bad idea, since the rooms auto start. Rather use in the console or configuration `wb_leave_on_start = 0` (owner only).

>  In the same mechcraft it is implemented by one command

Then use mechcraft if you're not happy with Warfacebot. Mechcraft is a wrapper of Warfacebot violating its AGPLv3 license. Have fun.

**Comment by furkanp34477** [comment]
turkey @Levak 
the invitation was canceled due to connection timeout. 
error

**Comment by Levak** [comment]
>  the invitation was canceled due to connection timeout.

See #169

**Comment by franchesko1437** [comment]
@Levak 
quickplay open tdm
Such a team?
-------------
I enter this command, something happens in the console, but the bot does not enter the fast game room

**Comment by franchesko1437** [comment]
Nice levak
You sent me to readme, but your bot does not work in a fast game. The fast game was initially disabled in the code of the program.
no words

**Comment by Levak** [comment]
>  You sent me to readme, but your bot does not work in a fast game. The fast game was initially disabled in the code of the program.

Quickplay works, it's just that the feature to invite other players has been broken by a game update. Just don't pre-invite players. Regarding the match making, there is no difference between you pre-inviting the bot and the bot pre-inviting you.
