### ISSUE TITLE
Login game

### ISSUE THREAD

**Issue by furkanp34477** [Levak/warfacebot#215]
Game is Login 20 second is and lobby you do

And 
Turkey warface archivement teammatch and enter the game and lobby in 2 seconds

But archivement teammatch not open 
Quickplay archivement not open

Bad english

**Comment by Levak** [comment]
Warfacebot has not been designed to join the game sessions.
It will, at most, only stay in the game room, waiting for the session to end, but will never join the other players in game.

> Bad english

Yes, your tickets are very painful to read.
