### ISSUE TITLE
detected (?)!

### ISSUE THREAD

**Issue by rasalgoel** [Levak/warfacebot#222]
Levak, i'm writing this for you: When i launch a game with bots, i get connection to server lost and when i come back i get the debugger error in game (protection system has found a running debugger program)
(i can assure you i didn't launch any debugger program on my own)

**Comment by Levak** [comment]
Yes, I am aware of this.
warfacebot got blacklisted like IDA, Visual Studio, CheatEngine etc, hence the message about "debugger".
Easy fix is to launch it in a VM/SB or simply on another computer/dedicated server like it was meant to be used.

**Comment by rasalgoel** [comment]
ah ok :)

**Comment by 1bot1** [comment]
If I correctly understood that to avoid "Loss of connection with the server" it is possible launching bots on other computer or in the virtual machine?

**Comment by Levak** [comment]
> If I correctly understood that to avoid "Loss of connection with the server" it is possible launching bots on other computer or in the virtual machine?

Of the heavy game client, yes. Of the bot, no, it will always get DC after 4min no matter what.

**Comment by 1bot1** [comment]
Something does not work.
Installed VMware® Workstation 12 Pro 12.5.7 build-5813279
And the Windows on it. After launching the bot, a message pops up: WinHTTP returned error: -2147012867
Could not connect to the server.

On the computer, these bots are launched without any problems.

**Comment by Levak** [comment]
> And the Windows on it. After launching the bot, a message pops up: WinHTTP returned error: -2147012867

AFAIR, you need an up to date Internet Explorer version, like IE11 or something.

**Comment by 1bot1** [comment]
I updated the OS of the virtual machine, but it did not help.
The problem is that I play through VPN. And to start the game I change IP. And if you change the system and the virtual machine, the bots do not start. They only work if you change IP in a virtual machine.
I tried to disable VPN, run bots and turn it on again. It helped, but often a communication failure if a long mission.
Are there any other solutions to this problem?

**Comment by Levak** [comment]
> Are there any other solutions to this problem?

I believe just recompiling the bot would work )

**Comment by 1bot1** [comment]
Sorry, but I'm not strong at all. ((
Explain how to do this recompilation? Or are you working on it and will be updating?
P.S. I run from three to six bots.

**Comment by Levak** [comment]
I pushed a 1.0.12 update, since they "just" blacklist a signature, hf while it lasts.
