### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by furkanp34477** [Levak/warfacebot#225]
Hi guy!
We need new update.
WFBOT join screen need add register form.
after register and automatic join.
Do it?, please, thx.

**Comment by Levak** [comment]
I have a hard time understanding what your problem/request is.
I see no update for Wf TR.

You talk about "register", but on TR, accounts are automatically created on the first login, which is implemented.
On EU/NA/RU, accounts are created with the `create <nick>` command, which is implemented too.

What is your problem/request?

**Comment by Levak** [comment]
What is your problem/request?
