### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by AresShift** [Levak/warfacebot#228]
So I've been updating basically just the NA server file after every update. However, after this latest update, whenever I start up a room, I eventually get a "Connection Lost" error. Upon relog, there's another message going on about how a "debugger" was detected. While I have found a way to get past this issue by launching the program from a different computer, I was wondering if it would be possible to get some insight as to why this is happening. Again, basically I soley update the NA server file, so maybe that's the problem. I just don't know what else needs to be updated.

**Comment by Levak** [comment]
See #222

PS: There is a 1.0.13 as of today, if even this one is "blacklisted" then recompile it yourself :D
