### ISSUE TITLE
How to compile in debug mode?

### ISSUE THREAD

**Issue by franchesko1437** [Levak/warfacebot#231]

**Comment by Levak** [comment]
just wb.exe ?

**Comment by franchesko1437** [comment]
Who?

**Comment by Levak** [comment]
https://github.com/Levak/warfacebot/releases/tag/1.0.13

**Comment by franchesko1437** [comment]
I realized that the new version is fixed, but the file names for this fix

**Comment by Levak** [comment]
I do not understand a word what you are saying.

**Comment by franchesko1437** [comment]
Какие файлы нужно перенести из версии 1.13, чтобы заработало правильное отображение

**Comment by Levak** [comment]
just wb.exe

**Comment by franchesko1437** [comment]
1 minute do not leave I try.

**Comment by franchesko1437** [comment]
Does not work(
Can I move files from the src folder?

**Comment by Levak** [comment]
> Does not work(
> Can I move files from the src folder?

Then I have no idea what your problem is. Do you have a screenshot perhaps?

**Comment by franchesko1437** [comment]
I have a debug version 1.11.
How can I correct the display of pvp matches, but do not break the launcher myself?

**Comment by franchesko1437** [comment]
![image](https://user-images.githubusercontent.com/29465298/37930501-9692ab38-314b-11e8-99e9-edfa04017ba5.png)

**Comment by Levak** [comment]
Then copy the DLLs shipped with the wb.exe file.

**Comment by franchesko1437** [comment]
Launcher earned, but there is no debug mode.
Is it possible to fix the debug of the mode without removing it?

**Comment by Levak** [comment]
> Launcher earned, but there is no debug mode.
> Is it possible to fix the debug of the mode without removing it?

If you have debug mode, it means you compiled the bot yourself.
Download the latest sources and compile it again.

Public releases do not include debug mode.

**Comment by franchesko1437** [comment]
When compiling version 1.13, the debugging mode does not work (see screenshot)
![image](https://user-images.githubusercontent.com/29465298/37930758-5cc03c58-314c-11e8-98b6-52553ce52fb3.png)

**Comment by Levak** [comment]
Still no screenshot of what you mean by "not working"?

**Comment by franchesko1437** [comment]
![image](https://user-images.githubusercontent.com/29465298/38043088-c21a4454-32be-11e8-8601-ba66508102ec.png)
1 screenshot. working old version
------------------------------------------------
![image](https://user-images.githubusercontent.com/29465298/38043192-176d83b2-32bf-11e8-811b-4264dcc754e1.png)
2 screenshot. non-working new version. It is identical to the usual no compiled version

**Comment by Levak** [comment]
> 1 screenshot. working old version
> 2 screenshot. non-working new version. It is identical to the usual no compiled version

You didn't compile in debug mode. I believe the compilation yield and error and you didn't see it. Delete wb.exe, and then recompile. If you are missing wb.exe it means the compilation failed. Read the errors in the console.

**Comment by franchesko1437** [comment]
The second compilation used the same thing as the first compilation. Perhaps an error in your files?
