### ISSUE TITLE
Update Warface-RU [27.03.2018]

### ISSUE THREAD

**Issue by LakosS** [Levak/warfacebot#232]
Levak please update Warface RU.
Thank you in advance.
:)

**Comment by 1bot1** [comment]
I join the request.
The version became such as and at you was on PTS
1.17000.1556.41200

**Comment by Levak** [comment]
Have you tried the PTS crypt key?
https://github.com/Levak/warfacebot/commit/3c0db34493aa6478062687e71b29f9426a89f802

Can't do it ATM, you'll have to wait tonight.

**Comment by 1bot1** [comment]
I did it first.
The key does not fit. Only the same version of the .exe-file.

**Comment by 1bot1** [comment]
Although not, in a virtual machine the bots started with this key.
