### ISSUE TITLE
compressedData help

### ISSUE THREAD

**Issue by mdn522** [Levak/warfacebot#234]
What is compressedData attribute in "/src/xmpp_wf/get/xmpp_iq_gameroom_join.c"?
https://prnt.sc/iyuovl

**Comment by Levak** [comment]
A Game room.
Comment: https://github.com/Levak/warfacebot/blob/master/src/xmpp_wf/result/xmpp_iq_gameroom_sync.c#L110
Parser: https://github.com/Levak/warfacebot/blob/master/src/gameroom.c
