### ISSUE TITLE
totally new to programming and stuff

### ISSUE THREAD

**Issue by The-Poltergeist** [Levak/warfacebot#236]
beginner here. so this thing when i open with cmd the '$' mark won't get recognised. so i used git bash and used the "cd warfacebot" but it says "no such file or directory". so i further went on and right click the filed and pressued use gitbash here. then i tried the "make" option. but it wont get recognied too. so i  am literally confused. anyone who could help?

**Comment by franchesko1437** [comment]
Если ты не можешь это сделать - это значит, что тебе это не нужно (с) левак

**Comment by Chihabk** [comment]
when i try to login, the CMD show and go faster, it dosen work for me

**Comment by nathan130200** [comment]
🤦‍♂️

**Comment by eletrofss** [comment]
Yeah you forgot the damn readline5 library, that's a fking pain to compile on ubuntu arm, i´m using a chroot environment on my android phone trough Linux Deploy
