### ISSUE TITLE
Update RU-PTS [07.04.18]

### ISSUE THREAD

**Issue by LakosS** [Levak/warfacebot#238]
Levak please update cfg ru-pts.
Thank you in advance.

:)

**Comment by franchesko1437** [comment]
Не пиши никогда заранее потому, что птс постоянно обновляется и писать нужно только тогда, когда он уже подходит ближе к лайву (1-2 дня). Левак если нужно сам увидит и выпустит обновление, а так только отвлекаешь человека.
