### ISSUE TITLE
tr update

### ISSUE THREAD

**Issue by furkanp34477** [Levak/warfacebot#249]
tr update please

**Comment by Levak** [comment]
I do not see any update for TR.
Latest version: 1.16500.4134.17500 already updated 2 months ago: 
https://github.com/Levak/warfacebot/blob/master/cfg/server/tr.cfg

**Comment by furkanp34477** [comment]
not working

**Comment by Levak** [comment]
> not working

Care to explain what you are trying to do, what it does (screenshot), etc. ?

Because, as I said, TR didn't get any update in 2 months.
TR is region blocked to TR only, so if you don't have a TR IP, don't expect to connect on it.

**Comment by furkanp34477** [comment]
version update :
Warfacebot Copyright (C) 2015-2017 Levak Borok
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see AGPLv3 Terms for details.


CMD#

**Comment by Levak** [comment]
Can you provide a screenshot of the full console? Like, where it's showing the `game_crypt_key`.

**Comment by furkanp34477** [comment]
http://prntscr.com/jdthvg

**Comment by Levak** [comment]
Everything seems correct.
Are you using a Turkish IP?

e.g. Can you ping the server?

```
ping com-tr.wfw.warface.com.tr
ping 212.68.32.82
```

**Comment by Levak** [comment]
The update happened after your first message.
I checked if I had any update on your first message, there was none.
So, maybe they were just under maintenance and you thought warfacebot was outdated.

Now I see the update, it will take some time, and then I will push the new keys here.

Next time, be more specific, explicit, and give more details to avoid any misunderstanding.

**Comment by Levak** [comment]
See d9ae9f7
