### ISSUE TITLE
update ru 1.17400.1590.41200

### ISSUE THREAD

**Issue by franchesko1437** [Levak/warfacebot#252]
hi levak.
Please update the keys for the Russian server

**Comment by franchesko1437** [comment]
Levak, where are you?

**Comment by Levak** [comment]
> Levaaaaaaaaak, where are you?

I have a life too. Not h24 in front of my computer, nor at home.

See 5d3f473

**Comment by 1bot1** [comment]
Looks busy, personal life.
The version of the game for PTS was different, probably a new crypt_key needed.
We wait.

**Comment by Levak** [comment]
> The version of the game for PTS was different, probably a new crypt_key needed.

I just updated both on my computer. They are at the exact same version and using the same key.

**Comment by franchesko1437** [comment]
Levak, tell me how to get the keys without your participation. It would be useful.
And what programs you need to use for this.

**Comment by Levak** [comment]
> Levak, tell me how to get the keys without your participation. It would be useful.

No.

**Comment by franchesko1437** [comment]
PAIN
