### ISSUE TITLE
startup problem

### ISSUE THREAD

**Issue by FonHaar** [Levak/warfacebot#253]
How to fix it?

![screen shot 05-20-18 at 10 13 am](https://user-images.githubusercontent.com/29449546/40275963-529b5532-5c17-11e8-98c1-0fe8dd53784a.PNG)

**Comment by LakosS** [comment]
1 wb.cfg?
1 wb.exe?
No...
1 wb.cfg - 1 bot.  2 wb.cfg - 2 bot.
- Yes!
Each time you run hwid_game-should change, each time you start a new bot. In warfacebot levak there is no such, but you can download my modification to warfacebot - Fan-Bot's.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
And maybe it's simple, you can use "Fan-Bot's", if you know Russian.
Download: http://rgho.st/6WN9HxG6F 
Pass: W-LAKO-JACE 

Don't forget to update the bots, via the button "ОБНОВЛЕНИЕ БОТОВ".
[The source wb.exe is, the code is not closed, everyone can look.]
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
