### ISSUE TITLE
Update RU - 1.17400.1604.22400

### ISSUE THREAD

**Issue by LakosS** [Levak/warfacebot#256]
Version: 1.17400.1604.22400
Server: RU
Update: 07.06.2018

Levak pls update RU-SERVER.
Thanks.

**Comment by MrSDoomS** [comment]
New Fix pls

**Comment by 1bot1** [comment]
These asses with mail.ru again updated the game version. Help us with the new key. Thank you.

**Comment by Lemon5** [comment]
I maintain the product of the above-mentioned. Without the game, we (the Russians) begin to drink vodka and ask the bear to play on balalaque katyusha)))

**Comment by Levak** [comment]
See 3c91aeb
