### ISSUE TITLE
Wrong difficulties in cmd_missions

### ISSUE THREAD

**Issue by alexalok** [Levak/warfacebot#26]
When whispering _missions_ to a bot, he sends a list of missions with wrong difficulty types.
**Normal** shows up as **easy**
**Hard** shows up as **normal**
**Insane** shows up as **hard**

**Comment by Levak** [comment]
Those are the raw values sent from server.
There is no will to change the display of it unless a multi-langage support is added and configured to do so.

See #25

FYI, these raw values were in line with game display prior to the game update that changed it in ~May 2015 IIRC;
