### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by franchesko1437** [Levak/warfacebot#262]
![image](https://user-images.githubusercontent.com/29465298/41548327-5388d188-732b-11e8-9fb1-9c8cc34347f6.png)
Levak. please update the file pvp_maps.c

**Comment by Levak** [comment]
1. Was there as `tdm_oildepot_e16`, now it's `tdm_oildepot_wc18`, will add it.
2. I forgot it in 2016, will add it.
3. Already there, `tdm_ghost_town`

**Comment by Levak** [comment]
See b3f704f

**Comment by franchesko1437** [comment]
Thanks
