### ISSUE TITLE
Warface RU

### ISSUE THREAD

**Issue by tiuningaslt** [Levak/warfacebot#273]
Hi guys, I have issues in RU servers with using more then 1 bot a time. I starting first bot and after just going to second one its closing first one.. 
Can you try to to check what's wrong with it Tnx

**Comment by Levak** [comment]
Give a unique HWID to each bot.
If you are using the windows version you'll have to copy paste the main folder.

**Comment by tiuningaslt** [comment]
What folder you mean bro?

**Comment by franchesko1437** [comment]
Читай readme или покупай мечкрафт

**Comment by tiuningaslt** [comment]
мечкрафт nurabotaut!

**Comment by tiuningaslt** [comment]
![desktop_180804_1402](https://user-images.githubusercontent.com/42081944/43676760-20e3c470-97ef-11e8-95c3-c79ad95fd5b4.jpg)
nurabotaut

**Comment by tiuningaslt** [comment]
Tnx Levak, I found! 
just got downloaded notepad++ and all sorted :)
