### ISSUE TITLE
Keys for pvp-maps

### ISSUE THREAD

**Issue by LakosS** [Levak/warfacebot#275]
Hello Levak, where are the keys for pvp maps?
Thanks.

**Comment by LakosS** [comment]
I found it in Gamedata.
You can close the question.

**Comment by Levak** [comment]
I don't really understand why you want the keys for LMS maps, those need 16 or so players to start.

**Comment by LakosS** [comment]
But you cannot change the minimum\maximum number of players so that you can run?

**Comment by Levak** [comment]
> But you cannot change the minimum\maximum number of players so that you can run?

No you can't. The minimum allowed for LMS maps is (was) 16 players. Maybe since the update it's even 32, didn't check yet.
