### ISSUE TITLE
Inconsistent problems when trying to start bot

### ISSUE THREAD

**Issue by MrRollton** [Levak/warfacebot#276]
Hello Levak and other maintainers. I've got some issues with wfbot. When trying to launch bot with a wb_launcher.hta (the Windows one) it just goes nowhere after pressing the "Login" button (command line appears for a split second and closes itself right away). However I've built a launcher for Linux and am trying to launch it with Windows subsystem for Linux. The issue is, sometimes it works, and sometimes it doesn't. If it doesn't, terminal can show one of two errors:
1). SZError Code="434" Reason="Token mismatch"
2). GCAuth ErrorCode="411"
Here's an example of a successful login after a series of failed attempts:

```
yakov@DESKTOP-8L538I1:~$ ./start_wfbot_3.sh
Connecting...<?xml version="1.0" encoding="UTF-8"?><SZError Code="434" Reason="token mismatch" />
failed

yakov@DESKTOP-8L538I1:~$ ./start_wfbot_3.sh
Connecting...<?xml version="1.0" encoding="UTF-8"?><GcAuth ErrorCode="411" />
failed

yakov@DESKTOP-8L538I1:~$ ./start_wfbot_3.sh
Connecting...<?xml version="1.0" encoding="UTF-8"?><GcAuth ErrorCode="411" />
failed

yakov@DESKTOP-8L538I1:~$ ./start_wfbot_3.sh
Connecting...done
g_language = english
game_hwid = 5
online_pvp_rank = 20
wb_accept_friend_requests = 1
wb_postpone_friend_requests = 0
wb_accept_clan_invites = 1
wb_postpone_clan_invites = 0
wb_enable_invite = 1
online_server = s1.warface.ru
game_manual_profile_creation = 1
game_server_name = ru-bravo
game_version = 1.17600.1632.22400
game_crypt_iv = 834724096,29884556,849283813,14157667,779975000,969872986,327122214,893084885
game_crypt_key = 3839877799,2044819422,1567648553,2482327799,3957672608,513131926,1943806143,1989780038,1213987527,1156558826,513352996,3852382041,3426490282,874007219,1035388528,3358934247,3919495048,848174001,680030764,3118993243,2609616660,1740258233,601899950,3659381002,2367855487,887335714,2590080856,170871869,3651120015,3635730687,1731453234,1866379965
Warfacebot Copyright (C) 2015-2017 Levak Borok
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see AGPLv3 Terms for details.
Starting TLS connection...
done.
JID: xxxxxx@warface/GameClient
Channel: pve_001_r2
Profile ID: xxxxxx
Nickname: xxxxxx
Joined channel pve_001_r2 (pve)
Experience: xxxxxx
Rating points: 0
Money: 11501
Crowns: 50
Kredits: 0
Unlocked items: 5/120
xxxxxx accepted the friend request
Friend: xxxxxx
Friend: xxxxxx
Friend: xxxxxx
Friend: xxxxxx
Friends: 4/50
Multipliers: x1.0 WFD | x1.0 XP | x1.0 VP | x1.0 Crowns
CMD#
```

I am playing on a Russian server, as you can see.
Any help would be much appreciated.

**Comment by Levak** [comment]
1. As for the `wb_launcher.hta` (coming from the binary releases for Windows), it is most likely a problem with non updated encryption keys. The repository itself is almost always up to date (just need to open an issue and usually by the evening the new keys are out). On the other hand, binary releases are only rolled out per tags, and the last tag is from several months ago. Encryption keys change after each game updates. They are stored in the `cfg/server/` folder.

2. As for the inconsistent login, it's kind of a tricky part for me too. I put that on my non understanding of the login chain for RU servers. Sometimes it just works without any problems, and sometimes it takes me a dozen tries too.

3. PS, stick to linux subsystem.

**Comment by Levak** [comment]
> About the wb_launcher - I've downloaded it earlier today just to be sure that everything is fresh,

`wb_launcher.hta` is just the launcher. The encryption keys are in `cfg/server/`. And since you mentioned being on Windows I doubt you recompiled it, so I assumed you downloaded the binary releases, which contain old encryption keys for you to replace.

> Well, if I'm the only one who has this problem, I don't care about it that much. Thanks for your reply.

Depends what problem you are talking about. 1. Is a common problem but not a bug, just lack of communication/documentation/updates, but with the proper information, it's easy to come up with it. 2. It's a known issue and will happen to everyone I guess.

> I guess, issue can be closed, then?

I'll be keeping the issue open for the MailRU launcher part.

**Comment by bakedbeans3** [comment]
Im having same issue - but i did do this copy of the code to the na.cfg file. Still all i get is a flash of the cmd screen and it dont work either

**Comment by bakedbeans3** [comment]
???????????
