### ISSUE TITLE
Bot timing out after a few seconds

### ISSUE THREAD

**Issue by dDrma** [Levak/warfacebot#277]
When i start the bot, its all fine. I can do whatever i want to do. But after a short amount of time (around 30-90 seconds) the bot kinda "times out".

OUTPUT:
   read: End of stream (5)
   Closed readstream
   Closed sendstream
   CMD#

   Closed idle
   Warface Bot closed!

Dunno if its a issue or wanted. Maybe I'm doing something wrong.
I'm running on linux base.

Greetz

**Comment by Levak** [comment]
On EU/NA/RU this is caused by MRAC kick.
Maximum time given is 5min when `game_hwid` is set. Nothing more.

Bypassing this would bypass MRAC completely.
