### ISSUE TITLE
RU-update game_version = 1.18000.1656.22400

### ISSUE THREAD

**Issue by 1bot1** [Levak/warfacebot#284]
Hi. Update the key for the Russian version

**Comment by tiuningaslt** [comment]
yes please, thanks

**Comment by mracking** [comment]
С нетерпеньем ждём))

**Comment by Viktor20217** [comment]
Ждемс

**Comment by mracking** [comment]
> привет. Обновление ключа для русской версии

Будет обновление ключей?

**Comment by Levak** [comment]
See 1ab21e84384c679b56fb5cee393d89035e654d8d
