### ISSUE TITLE
Unable to find/execute wb.exe

### ISSUE THREAD

**Issue by DACHAA** [Levak/warfacebot#29]
I downloaded warface bot from this site,and i started launcher wb_launcher.hta and took EU server and put my email and password of my Warface account and pressed ,,Log In,, and it says ,,Unable to find/execute wb.exe,, .What should i do?

**Comment by Levak** [comment]
You should compile it yourself first, or grab a compiled version out of the automatic builds from the https://github.com/Levak/warfacebot/releases tab.

**Comment by DACHAA** [comment]
Ok,i will try.Thanks anyway.

**Comment by DACHAA** [comment]
It still don't work!Can you please tell me step by step what to do?

**Comment by Levak** [comment]
> It still don't work!

Saying it doesn't work won't lead you anywhere.
There are billions of reasons why something would not work.

Please note that the latest release will not be able to connect on the EU/NA/TR servers out of the box because of the wrong game version. You'll need to update the `cfg/servers/*.cfg` files accordingly.

**Comment by DACHAA** [comment]
Maybe im anoying but sorry,how to update it ?

**Comment by Levak** [comment]
> how to update it ?

It's a text file. For instance:
https://github.com/Levak/warfacebot/blob/master/cfg/server/eu.cfg

**Comment by DACHAA** [comment]
Still can't do anytghing :( I don't know what is happening.

**Comment by Levak** [comment]
> Because when i start wb.exe it says ,,missing readline5.dll,,.

That DLL should be provided in the release package....

**Comment by DACHAA** [comment]
Levak,can you somehow add me bots ? Because i don't know what's wrong with this.Everytime i start Warface bot there is some problem :(
