### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by FlareNetwork** [Levak/warfacebot#292]
gcc -Wall -Wextra -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -O2 -MMD -Iinclude -Ithird_party -DZLIB -DUSE_TLS -pthread -DHAVE_STRNDUP   -c -o src/offer.o src/offer.c
gcc -Wall -Wextra -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -O2 -MMD -Iinclude -Ithird_party -DZLIB -DUSE_TLS -pthread -DHAVE_STRNDUP   -c -o src/option.o src/option.c
gcc -Wall -Wextra -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -O2 -MMD -Iinclude -Ithird_party -DZLIB -DUSE_TLS -pthread -DHAVE_STRNDUP   -c -o src/masterserver.o src/masterse                                                           rver.c
gcc -Wall -Wextra -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -O2 -MMD -Iinclude -Ithird_party -DZLIB -DUSE_TLS -pthread -DHAVE_STRNDUP   -c -o src/mission.o src/mission.c
gcc -Wall -Wextra -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -O2 -MMD -Iinclude -Ithird_party -DZLIB -DUSE_TLS -pthread -DHAVE_STRNDUP   -c -o src/querycache.o src/querycache                                                           .c
gcc -Wall -Wextra -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -O2 -MMD -Iinclude -Ithird_party -DZLIB -DUSE_TLS -pthread -DHAVE_STRNDUP   -c -o src/querydump.o src/querydump.c
gcc -Wall -Wextra -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -O2 -MMD -Iinclude -Ithird_party -DZLIB -DUSE_TLS -pthread -DHAVE_STRNDUP   -c -o src/quickplay.o src/quickplay.c
gcc -Wall -Wextra -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -O2 -MMD -Iinclude -Ithird_party -DZLIB -DUSE_TLS -pthread -DHAVE_STRNDUP   -c -o src/pvp_maps.o src/pvp_maps.c
gcc -Wall -Wextra -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -O2 -MMD -Iinclude -Ithird_party -DZLIB -DUSE_TLS -pthread -DHAVE_STRNDUP   -c -o src/session.o src/session.c
gcc -Wall -Wextra -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -O2 -MMD -Iinclude -Ithird_party -DZLIB -DUSE_TLS -pthread -DHAVE_STRNDUP   -c -o src/status.o src/status.c
gcc -Wall -Wextra -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -O2 -MMD -Iinclude -Ithird_party -DZLIB -DUSE_TLS -pthread -DHAVE_STRNDUP   -c -o src/stream/connect.o src/stream                                                           /connect.c
gcc -Wall -Wextra -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -O2 -MMD -Iinclude -Ithird_party -DZLIB -DUSE_TLS -pthread -DHAVE_STRNDUP   -c -o src/stream/crypt.o src/stream/c                                                           rypt.c
gcc -Wall -Wextra -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -O2 -MMD -Iinclude -Ithird_party -DZLIB -DUSE_TLS -pthread -DHAVE_STRNDUP   -c -o src/stream/recv.o src/stream/re                                                           cv.c
gcc -Wall -Wextra -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -O2 -MMD -Iinclude -Ithird_party -DZLIB -DUSE_TLS -pthread -DHAVE_STRNDUP   -c -o src/stream/send.o src/stream/se                                                           nd.c
gcc -Wall -Wextra -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -O2 -MMD -Iinclude -Ithird_party -DZLIB -DUSE_TLS -pthread -DHAVE_STRNDUP   -c -o src/stream/tls.o src/stream/tls                                                           .c
gcc -Wall -Wextra -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -O2 -MMD -Iinclude -Ithird_party -DZLIB -DUSE_TLS -pthread -DHAVE_STRNDUP   -c -o src/threads/threads.o src/threa                                                           ds/threads.c
src/threads/threads.c:130:13: warning: ‘sigint_handler’ defined but not used [-Wunused-function]
 static void sigint_handler(int signum)
             ^
gcc -Wall -Wextra -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -O2 -MMD -Iinclude -Ithird_party -DZLIB -DUSE_TLS -pthread -DHAVE_STRNDUP   -c -o src/threads/thread_dispatch.o s                                                           rc/threads/thread_dispatch.c
gcc -Wall -Wextra -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -O2 -MMD -Iinclude -Ithird_party -DZLIB -DUSE_TLS -pthread -DHAVE_STRNDUP   -c -o src/threads/thread_ping.o src/t                                                           hreads/thread_ping.c
gcc -Wall -Wextra -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -O2 -MMD -Iinclude -Ithird_party -DZLIB -DUSE_TLS -pthread -DHAVE_STRNDUP   -c -o src/threads/thread_sendstream.o                                                            src/threads/thread_sendstream.c
src/threads/thread_sendstream.c: In function ‘thread_sendstream_close’:
src/threads/thread_sendstream.c:87:20: warning: unused variable ‘t’ [-Wunused-variable]
     struct thread *t = (struct thread *) vargs;
                    ^
gcc -Wall -Wextra -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -O2 -MMD -Iinclude -Ithird_party -DZLIB -DUSE_TLS -pthread -DHAVE_STRNDUP   -c -o src/threads/thread_readstream.o                                                            src/threads/thread_readstream.c
gcc -Wall -Wextra -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -O2 -MMD -Iinclude -Ithird_party -DZLIB -DUSE_TLS -pthread -DHAVE_STRNDUP   -c -o src/threads/thread_readline.o s                                                           rc/threads/thread_readline.c
src/threads/thread_readline.c:29:31: fatal error: readline/readline.h: No such file or directory
 #include <readline/readline.h>
                               ^
compilation terminated.
<builtin>: recipe for target 'src/threads/thread_readline.o' failed
make: *** [src/threads/thread_readline.o] Error 1

Using Debian 8 64x

**Comment by Levak** [comment]
As the error suggests, you need to install `libreadline-dev` on your system.

See the list of dependencies here:
https://github.com/Levak/warfacebot#step-by-step

**Comment by FlareNetwork** [comment]
Trying the EU Server but it says: Please use the localised Version.
