### ISSUE TITLE
Localised Version EU Error

### ISSUE THREAD

**Issue by FlareNetwork** [Levak/warfacebot#293]
In order to play the game you can use the localised version for your region.

./wb.sh eu

**Comment by franchesko1437** [comment]
Use file wb.hta

**Comment by Levak** [comment]
> In order to play the game you can use the localised version for your region.

In EU/NA server, VPS are blacklisted to prevent the use of VPN. You need to find a non blacklisted VPS.

> Use file wb_launcher.hta

Will change nothing.

**Comment by FlareNetwork** [comment]
Found a not Blacklisted Hoster :D
