### ISSUE TITLE
Обновление версии игры RU 1.18800.1734.41200

### ISSUE THREAD

**Issue by mracking** [Levak/warfacebot#302]
Здравствуйте Левак! Обновите пожалуйста ключи до версии игры RU 1.18800.1734.41200
За ранее спасибо!

**Comment by AzizjanT** [comment]
He don't speak Russian, please write in English.

For levak: TS wants new crypt-keys for RU-update.

**Comment by mracking** [comment]
> Он не говорит по-русски, пожалуйста, пишите по-английски.
> 
> Для levak: TS нужны новые crypt-ключи для RU-update.

Браузер переведет на нужный язык

**Comment by Levak** [comment]
See fcca20a
