### ISSUE TITLE
commands in client

### ISSUE THREAD

**Issue by Marsel0000** [Levak/warfacebot#304]
Hello, As I understand, command "follow" allows to join any person on a nickname. May I use it in the client without use of warfacebot? That is, is available
 whether some console where I can enter command "follow" into warface and join the person as I do it through cygwin

**Comment by eletrofss** [comment]
theoretically you could set up a proxy in the middle of the connection then inject packets as if someone invited you to their room, you should download ZED proxy attack, proxifier,  unpack the executable, change the tls key on the original game via binary way, then send a packet to your game with the invitation.
Yeah, not easy, but not too difficult if you know the mentioned way. Levak probably did use the same setup.

**Comment by eletrofss** [comment]
you could try something in kali, but i'm not exactly sure how far goes the rabbit hole.... especially when you're here asking stuff.
