### ISSUE TITLE
Suggestion - Android CHROOT version?

### ISSUE THREAD

**Issue by eletrofss** [Levak/warfacebot#305]
It would be nice to have a compiled version of the warfacebot compiled for armhf smartphones, right now i'm trying to compile the warfacebot in a CHROOT environment of Linux Deploy, after the compilation the application binary should work on android, then it becomes easy to make a gui.
Thanks, i'll report later on my success/share the binaries, right now i'm kinda fked trying to compile the readline5 library (that nobody fking mentioned should be readline5 instead of readline).

**Comment by seanwlk** [comment]
Running this setup since years already on my Kali chroot. All the libs are available and working.

**Comment by eletrofss** [comment]
Sweet, nice to know, i was trying debian, i might as well install kali, i was going to do that eventually.
