### ISSUE TITLE
Обновите ключи до RU версии 1.19000.1750.41200

### ISSUE THREAD

**Issue by mracking** [Levak/warfacebot#307]
Доброго времени суток Левак. За ранее спасибо

**Comment by Lemon5** [comment]
Уже второй запрос по поводу обновы.
Если он в Америке живет то там глубокая ночь, если в Европе то уже утро.
Good morning! Poor Russians welcome you and are waiting for your mercy to show us respect and update your best program.

**Comment by Levak** [comment]
See #306

**Comment by mracking** [comment]
> Уже второй запрос по поводу обновы.
> Если он в Америке живет то там глубокая ночь, если в Европе то уже утро.
> Доброе утро! Бедные русские приветствуют вас и ждут вашей милости, чтобы показать нам уважение и обновить вашу лучшую программу.

Нужно понятнее запросы делать
