### ISSUE TITLE
how to change region

### ISSUE THREAD

**Issue by darkevil1102** [Levak/warfacebot#308]
i want change to hongkong
how to do?

**Comment by Levak** [comment]
`online_region_id`. Either on launch (e.g. with `-D` or in `wb.cfg`) or live in the command line (requires to change channel at least once for it to be taken into account).

Refer to the region IDs in `QueryCache/get_config.xml` at the end. For EU server, should be one of:
 - `global`
 - `hongkong`
 - `singapore`
