### ISSUE TITLE
Обновление ключей RU сервер до версии 1.19200.1766.41200

### ISSUE THREAD

**Issue by mracking** [Levak/warfacebot#311]
Здравствуйте Лувак. Обновите пожалуйста RU сервер до версии игры 1.19200.1766.41200
За ранее спасибо!

**Comment by Levak** [comment]
Duplicate, already done:

https://github.com/Levak/warfacebot/blob/master/cfg/server/ru-alpha.cfg

**Comment by Levak** [comment]
You meant 1.19200.1773.22400, not  1.19200.1766.41200

Updated in 5d0d500
