### ISSUE TITLE
How to create bot account with Levak/warfacebot??

### ISSUE THREAD

**Issue by tetteykn** [Levak/warfacebot#323]

**Comment by Levak** [comment]
"create bot account" refers to creating a dedicated account that will only be used for botting. Do not use your main account or borrowed account, if you don't want to have any issue with it.

So just go on wf.my.com (or your publisher), create an account with a temporary email, play on it to get to the level you want to unlock the missions you want and then use the bot.

Make sure the bot encryption key is correctly set, the key on the repository is always up to date, but not in the binary release. It's a text file, just update it: `cfg/server/*.cfg` from  https://github.com/Levak/warfacebot/tree/master/cfg/server

**Comment by tetteykn** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/51218189/59132094-84e01380-8974-11e9-91c8-bedc22cc47ce.png)
No idea i just downloaded that wb_launcher from 
https://github.com/Levak/warfacebot.git 
and that what i tried and what happened in the screenshoot

**Comment by Levak** [comment]
Encryption keys, as I said.
They are changed every update, you need to update them by yourself, I gave you the link above.
I don't trigger new build just because a text file changed.

**Comment by tetteykn** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/51218189/59132527-ba393100-8975-11e9-8d9d-9f4b1e3c7ddc.png)
what should i update? here? in eu.cfg

**Comment by Levak** [comment]
The entire file, just download and replace.

**Comment by tetteykn** [comment]
i downloaded and i replaced but i think game game_version and game_crypt_ke and other stuff are old i should edit it?

**Comment by Levak** [comment]
1. Binary releases come with pre-compiled executables, but expired config files
2. Repository (sources) is always up to date, So download the up to date config files from it. The one I see on your last screenshot is the last EU update version and key.

**Comment by tetteykn** [comment]
i dont know where i can download up to date files

**Comment by Levak** [comment]
> i dont know where i can download up to date files

You know, since you took a screenshot of it.
Just click "RAW".

**Comment by tetteykn** [comment]
im new here no idea where i can find it updated once

**Comment by Levak** [comment]
You did here! https://github.com/Levak/warfacebot/issues/323#issuecomment-500032688
https://github.com/Levak/warfacebot/blob/master/cfg/server/eu.cfg
https://raw.githubusercontent.com/Levak/warfacebot/master/cfg/server/eu.cfg
