### ISSUE TITLE
Zlibb.64 got error

### ISSUE THREAD

**Issue by jun1998** [Levak/warfacebot#332]
When I'm using the -gcc in the bot, I received this Error. I try to Reinstall the required Package but it still failed. I need an advice right now cuz I want to login to my Warface account when I'm far from my computer
![Screenshot_20190627-164030](https://user-images.githubusercontent.com/52279325/60255738-7ee9ac80-98fa-11e9-9c78-83221cc378f8.png)

**Comment by Levak** [comment]
1. You are missing zlib-dev package for your distribution. Likely missing libcrypto-dev and libreadline-dev packages too
2. Do not run warfacebot on your main account if you do not know what you are doing. e.g. HWID.
3. Use `./wb.sh`, not `wb.sh`

**Comment by jun1998** [comment]
Thanks Levak
Anyway, I play in VN server that are allow us to using bot, so Game hwid is 0

**Comment by Levak** [comment]
Any update?
