### ISSUE TITLE
Help to start battle royale pripyat / mojave ??

### ISSUE THREAD

**Issue by Alanx122** [Levak/warfacebot#334]
Hello, what is the command to start the battle royale pripyat / mojave? When I type lms_pripyat this error occurs "No such map or mission"
![unknown](https://user-images.githubusercontent.com/46060312/60414858-cfd5fb00-9baf-11e9-87ea-9e67cc9e761c.png)

**Comment by eddybanca** [comment]
I'm having the same problem! HELP!

**Comment by Levak** [comment]
What version of the **Game** are you playing on? EU?
What version of the **Bot** are you using? Compiled or downloaded?

**Comment by Alanx122** [comment]
Hello, I'm playing on warface BR My version of warface is 1.18000.944.21500. I downloaded your but did not work the cmd opens and closes I had to download another and copy some dll to open it.
![unknown (1)](https://user-images.githubusercontent.com/46060312/60498477-0766a500-9c8d-11e9-91bb-bb3f6633b9ca.png)

**Comment by Levak** [comment]
Then your problem is that you're using a too old version of Warfacebot. The map was added rather recently to the bot. Recompile the bot in order to get the map built-in.
