### ISSUE TITLE
Nao consigo iniciar a partida royale pripyat/mojave com os códigos citados

### ISSUE THREAD

**Issue by eddybanca** [Levak/warfacebot#335]

**Comment by eddybanca** [comment]
the commands to start the battle royale pripyat / mojave do not work, could you tell which ones are or if they even exist?

**Comment by eddybanca** [comment]
CMD# quickplay start lms_pripyat
CMD#      Failed to open quickplay room (Invalid or expired mission)
CMD#

**Comment by Levak** [comment]
Duplicate of #334
