### ISSUE TITLE
internal error

### ISSUE THREAD

**Issue by KoLLapS1337** [Levak/warfacebot#336]
Hi, Levak! I can't sign in. I entered all the account data correctly, but gives this error, what should I do?
![error](https://user-images.githubusercontent.com/52503600/60607657-283b1180-9dd7-11e9-9422-313891bcac8d.png)

**Comment by Levak** [comment]
Hi,
1. Is this the first time using warfacebot with the windows launcher?
2. On what server are youth trying to log in?
3. What windows version are you using? And IE version.

**Comment by KoLLapS1337** [comment]
1. yes, it's first time i using warfacebot
2. MAIL.RU - Alpha
3. Windows 7 home basic. IE version 8

**Comment by KoLLapS1337** [comment]
I updated an internet explorer to 11 version, so i can login, but cmd turns on for a split second, after which it closes immediately... i don't know what to do again

**Comment by Levak** [comment]
Update the game crypt keys to the ones available on the repository. 
cfg/server/ru-alpha.cfg

Also bear in mind that support of RU login has a known "issue" that requires several logo attempts to work.

**Comment by KoLLapS1337** [comment]
How to update crypt keys? I newbie

**Comment by Levak** [comment]
Tuda: https://github.com/Levak/warfacebot/blob/master/cfg/server/ru-alpha.cfg
