### ISSUE TITLE
Cannot join pvp quickplay

### ISSUE THREAD

**Issue by sumfun4WF** [Levak/warfacebot#337]
As soon as the bot finds a quickplay room, I get End of stream error and the bot is kicked from server. (NA/EU)

**Comment by Levak** [comment]
The "end of stream" error is due to MRAC automatically disconnecting any client without a valid anti-cheat heart-beat within 1-5min, or a "valid" HWID.

Assuming you've set `game_hwid`, you have 5min max to find a room in quickplay before the bot loses connection on EU/NA/RU.

**Comment by Carlsberg34** [comment]
Hi, Levak. 
As soon as the bot finds a quickplay room.  And I try to join there is an error "Impossible to join the player" . Previously, this was not, appeared in the last update of the game.
![Warface_190717_1636](https://user-images.githubusercontent.com/53007121/61380278-5e819200-a8a9-11e9-9481-e594cf6b1126.jpg)

**Comment by Levak** [comment]
@Carlsberg34 see #339
