### ISSUE TITLE
Pvp quickplay autoreject

### ISSUE THREAD

**Issue by SolarSpear** [Levak/warfacebot#339]
After the last update it is impossible to join the bot in a quick game. 'Failed to follow {nickname} (Autoreject)' - message in console.
![screen](https://user-images.githubusercontent.com/23638613/61231633-8fdd4f00-a73d-11e9-85de-fc95f9279794.png)

**Comment by Levak** [comment]
Which version of the **bot** are you using?
I am not able to reproduce your bug.

**Comment by SolarSpear** [comment]
I used a compiled version based on some age. Just compiled based on the latest files - the result is the same.

**Comment by Levak** [comment]
With the latest version of the bot you should see "failed to invite", not "failed to follow".
If you can compile the bot yourself, then compile it in debug mode and enable query logging.

In wb.cfg
```
query_debug=0
query_dump_to_file=1
```
And send me the file by email (after stripping what you feel confidential). 

Or on the command line:
```
query_debug 0
quickplay open tdm
quickplay start
... Joined room [...]
query_debug 1
... follow the bot
... error
```
And paste here just the queries.

**Comment by SolarSpear** [comment]
I tried the precompiled version 1.0.15, the result is the same. Which file should I send? And yes, when I try to type `query_debug 0` in the console, I get the message 'Command not found: query_debug'.

**Comment by Levak** [comment]
Oh you meant that by "just compiled based on the latest files". Then no, you can't enable debug mode.

**Comment by SolarSpear** [comment]
Forgive me my English)) I meant 'In the moment'. To compile, I use the latest files bot and a cygwin terminal.  Is it possible to compile a debug version?

**Comment by franchesko1437** [comment]
> О, вы имели в виду, что «просто скомпилированы на основе последних файлов». Тогда нет, вы не можете включить режим отладки.

Levak, This error appeared after the update. The one who made the MechCraft fixed it.
https://vk.com/wall-169489115_1441    - Post in vkontakte .

**Comment by Levak** [comment]
Is this issue only happening in PvP?
Because as I said, I cannot reproduce it in PvE.

bot1
```
quickplay open training
quickplay start
```
bot2
```
follow bot1
```

Works for me. Bot2 joins the room of bot1 once it finds a room.

**Comment by SolarSpear** [comment]
Only on pvp.  On pve bot works fine.

**Comment by Levak** [comment]
> Only on pvp. On pve bot works fine.

Ok. I am able to reproduce the error.
The error code comes from the masterserver.
After a quick I see a new argument in the `<follow_send>` query. Will try to deploy a fix.

**Comment by Levak** [comment]
Try https://github.com/Levak/warfacebot/releases/tag/1.0.15b

**Comment by franchesko1437** [comment]
> Try https://github.com/Levak/warfacebot/releases/tag/1.0.15b
Thanks, Levak.
All the same, it was not anti-cheat, as you said in the stream)

**Comment by Levak** [comment]
> All the same, it was not anti-cheat, as you said in the stream)

During the stream you said the bot DISCONNECTED. That wasn't the case.

**Comment by franchesko1437** [comment]
> > Все таки это был не античит, как вы сказали в потоке)
> 
> Во время стрима вы сказали, что бот ОТКЛЮЧЕН. Это был не тот случай.

Translation difficulties

**Comment by Carlsberg34** [comment]
Thanks Levak.
I downloaded the last Levak-bot and the problem was solved. 

I heard that through Levak bot, you can see the hidden parameter 'skill' which affects the auto balance. How to do this?

**Comment by Levak** [comment]
> I heard that through Levak bot, you can see the hidden parameter 'skill' which affects the auto balance. How to do this?

This is not a feature of the publicly compiled version of warfacebot (from Release tab). Compile it yourself and enable debug bot.

Again, this is not a supported feature.

**Comment by franchesko1437** [comment]
> го самостоятельно и включите отладочный бот.

How to enable debug bot?
