### ISSUE TITLE
Command 'quit' not work

### ISSUE THREAD

**Issue by alexey1970** [Levak/warfacebot#340]
Hi, Levak !
I'm run warfacebot-mingw-1.0.15 on VMware (Windows7-x64). Server [RU].
Bot work correct, but after command 'quit' nothing happens.
Should the 'quit' command close the console ?

**Comment by franchesko1437** [comment]
Леха, 49 лет, а все фигней занимаешься. Иди отдохни.

**Comment by wnull** [comment]
As far as I know, the `quit `command closes the `warfacebot `application, but does not close the terminal.
