### ISSUE TITLE
When using the "exec" which contains the command "invite". Console is closing

### ISSUE THREAD

**Issue by franchesko1437** [Levak/warfacebot#341]
Levak, Hello. Help please.

When I try to call my bots to the room using the "Exec" command, the console closes
```
exec 1.txt
```

Сonsole closed

I made a debug file.
Where can I send it to you?

**Comment by Levak** [comment]
> When I try to call my bots to the room using the "Exec" command, the console closes

I copy/pasted your `1.txt` and am not able to reproduce your issue.

> I made a debug file.
> Where can I send it to you?

To my email (see header: https://github.com/Levak/warfacebot/blob/master/include/wb_cmd.h#L3 )

**Comment by franchesko1437** [comment]
> На мою электронную почту (см. Заголовок: https://github.com/Levak/warfacebot/blob/master/include/wb_cmd.h#L3 )

I've posted. Check, please.

**Comment by Levak** [comment]
How is your file encoded?
Try to make sure it's encoded in UTF-8

Because this is what happens with your file:
```
<iq to='masterserver@warface/pvp_pro_019_r1' type='get' >
 <query xmlns='urn:cryonline:k01'>
  <invitation_send nickname='��2駠is_follow='0' group_id=''/>
 </query>
</iq>
```

**Comment by franchesko1437** [comment]
> Как закодирован ваш файл? 
> Попробуйте убедиться, что он закодирован в UTF-8
> 
> Потому что это то, что происходит с вашим файлом:
> 
> ```
> <iq to='masterserver@warface/pvp_pro_019_r1' type='get' >
>  <query xmlns='urn:cryonline:k01'>
>   <invitation_send nickname='��2駠is_follow='0' group_id=''/>
>  </query>
> </iq>
> ```

I did not encode the file. He was like that.
Most likely this is due to the fact that the player's nickname is written in Russian.

**Comment by Levak** [comment]
In Notepad++, go in "Encoding" > "Convert to UTF-8"

**Comment by franchesko1437** [comment]
> В Notepad ++ перейдите в «Кодировка»> «Преобразовать в UTF-8»
thanks Levak. everything is working

**Comment by franchesko1437** [comment]
Levak, please close the question. Problem solved
