### ISSUE TITLE
cmd close

### ISSUE THREAD

**Issue by KoLLapS1337** [Levak/warfacebot#342]
hello, it's me again. i'm back and updated crypt keys, but problem(cmd closes immediately) still exists. what to do?

**Comment by franchesko1437** [comment]
Not properly updated.
Duplicate of #99

**Comment by KoLLapS1337** [comment]
i just reinstalled wftbot, crypt keys is newest

**Comment by franchesko1437** [comment]
[https://github.com/Levak/warfacebot/releases/tag/1.0.15b](url)
I can not reproduce your problem.
My bot is loaded by the link above and it works

**Comment by KoLLapS1337** [comment]
ru alpha

**Comment by KoLLapS1337** [comment]
installed your version - did not help

**Comment by franchesko1437** [comment]
> установил вашу версию - не помогло
У меня все работает, разбирайся.
