### ISSUE TITLE
Обновление ключей игры RU сервера до версии 1.19700.1823.41200

### ISSUE THREAD

**Issue by mracking** [Levak/warfacebot#343]
Доброго времени суток Левак. Обновите пожалуйста ключи игры RU сервера до версии 1.19700.1823.41200
За ранее спасибо!

**Comment by seanwlk** [comment]
Check latest commit.

**Comment by franchesko1437** [comment]
Thanks Seanwlk.  Levak is sleeping)

**Comment by mracking** [comment]
> Проверьте последнюю фиксацию.

Спасибо
