### ISSUE TITLE
The bot does not work via wb.sh

### ISSUE THREAD

**Issue by LazyHail** [Levak/warfacebot#344]
![image](https://user-images.githubusercontent.com/53359042/61988705-a2a12f00-b02d-11e9-8316-be5f55ad979c.png)
I compiled a bot on the server, but he does not want to enter the game. How to be?
Oh great Levak HELP

**Comment by seanwlk** [comment]
The game version is wrong. Update that and the keys.

**Comment by franchesko1437** [comment]
> The game version is wrong. Update that and the keys.
I just tried to install it before writing here, but nothing happened, hence the old version.
All updated, the problem remains.
![image](https://user-images.githubusercontent.com/29465298/61992487-d8630980-b067-11e9-9855-285351b351f4.png)

**Comment by LazyHail** [comment]
> The game version is wrong. Update that and the keys.

I just tried to install it before writing here, but nothing happened, hence the old version.
All updated, the problem remains.
![image](https://user-images.githubusercontent.com/29465298/61992487-d8630980-b067-11e9-9855-285351b351f4.png)

**Comment by seanwlk** [comment]
Then I assume you're missing the hardware ID ?

**Comment by LazyHail** [comment]
> Then I assume you're missing the hardware ID ?

What?

---
A similar error as in the screenshot appears only with mail @mail.ru, with @yandex.ru and  mail authorization works.

**Comment by Levak** [comment]
The error means no user id could be retrieved from the auth. Either because the account is banned (should tell it before that stage), because of an error in parsing it by the script, or because the auth method changed.

From what you tell us here, please confirm all points:
 - auth works with both yandex and mailru accounts with the "wb_launcher.hta" file
 - auth works with yandex with "wb.sh" file
 - auth doesn't work with mailru accounts with "wb.sh" file.

Is that a recent change? Because I use daily wb.sh with mailru and free email accounts with no issue other than trying several times. My last test was a week ago and I will be unable to test for about an additional week. My stat bot is working with this script and mailru account.

How are you launching wb.sh? Hide the personal information, but we need the command line.

**Comment by LazyHail** [comment]
> Ошибка означает, что идентификатор пользователя не может быть получен из аутентификации. Либо потому, что учетная запись заблокирована (следует сообщить об этом до этого этапа), либо из-за ошибки при синтаксическом анализе сценария, либо из-за изменения метода auth.
> 
> Исходя из того, что вы нам расскажете, подтвердите все пункты:
> 
> * auth работает с учетными записями yandex и mailru с файлом "wb_launcher.hta"
> * auth работает с яндексом с файлом "wb.sh"
> * auth не работает с аккаунтами mailru с файлом "wb.sh".
> 
> Это недавнее изменение? Потому что я ежедневно использую wb.sh с mailru и бесплатными учетными записями электронной почты без каких-либо проблем, кроме попыток несколько раз. Мой последний тест был неделю назад, и я не смогу пройти тест еще около недели. Мой статист бот работает с этим скриптом и аккаунтом mailru.
> 
> Как вы запускаете wb.sh? Скрыть личную информацию, но нам нужна командная строка.

-Account is not locked
- I tried to run wb.sh on a computer in cygwin, the error is identical
Levak Questions
- wb.launcher.hta on the computer does not work with Yandex mail, it only works with mail to mail.ru
- wb.sh works with Yandex mail, but does not work with mail.ru mail (I already wrote about this above)
- that's right, the wb.sh file gives an error, which I sent above (photo), works with Yandex mail, but does not work with mail.ru mail
Please help me in the discord, I will show you a screen demonstration. I sent you a friend request :)
I run on the ubuntu server with the installation of the necessary libraries

**Comment by Levak** [comment]
I am not available for a week.

**Comment by LazyHail** [comment]
> Я не доступен в течение недели.

I will wait for you, it's not difficult for me.
If you are ready to help in the discord

**Comment by LazyHail** [comment]
> I am not available for a week.

You have done a lot of work on the bot. This greatly helped ordinary users who want to run the game in solo mode.
Thank you so much Levak

**Comment by Levak** [comment]
When I came back home I tested on my mailru bot account and had no issue logging in.

**Comment by Levak** [comment]
Is this still an existing issue?
