### ISSUE TITLE
RU - 1.19900.1832.41200

### ISSUE THREAD

**Issue by 1bot1** [Levak/warfacebot#347]
Hello. Make a welcome update for the RU-game.

**Comment by Levak** [comment]
Would you kindly check the repository, before opening an issue? Ty

https://github.com/Levak/warfacebot/blob/master/cfg/server/ru-pts.cfg

**Comment by 1bot1** [comment]
You updated the TCP, and today there was an update on the main server. You can of course copy the key from the TCP, but I wanted an “official” update from you ;-)

**Comment by 1bot1** [comment]
TCP(PTS)

**Comment by Levak** [comment]
> You updated the TCP, and today there was an update on the main server.

Sorry, my bad. I misread.
See 602ea46

**Comment by 1bot1** [comment]
Thanks for understanding and updating.
