### ISSUE TITLE
Здравствуйте Levak. Обновите пожалуйста ключи Ru сервера до версии игры 1.19900.1844.41200

### ISSUE THREAD

**Issue by mracking** [Levak/warfacebot#349]
Здравствуйте Levak. Обновите пожалуйста ключи Ru сервера до версии игры 1.19900.1844.41200
За ранее спасибо!

**Comment by seanwlk** [comment]
See [7e9daf8](https://github.com/Levak/warfacebot/commit/7e9daf81c247976341b2188e09b63c66233acf8c) .
