### ISSUE TITLE
Запуск на Рейтинговые матчи

### ISSUE THREAD

**Issue by mracking** [Levak/warfacebot#353]
Здравствуйте Levak! Возможно ли сделать так, чтоб можно было с помощью ботов запускаться на Рейтинговые матчи?

**Comment by Levak** [comment]
It is not a feature of warfacebot.
You have no reason to use warfacebot in ranked other than abusing the match making.

**Comment by mracking** [comment]
> Это не является особенностью warfacebot.
> У вас нет никаких причин использовать warfacebot в рейтинге, кроме злоупотребления созданием матча.

Бывает не хватает пятого игрока для рейтинговых матчей, а с посторенними не хочется запускаться. Эта функция была бы полезна.
