### ISSUE TITLE
Command to bot left own clan?

### ISSUE THREAD

**Issue by wnull** [Levak/warfacebot#355]
Is there a command so the bot could leave own clan? The configs on the directory [`lang` ](https://github.com/Levak/warfacebot/blob/master/cfg/lang/) of the languages I’ve seen [file](https://github.com/Levak/warfacebot/blob/master/cfg/lang/english.cfg#L278), the key `notif_clan_left` with value `%s left the clan`. 

I think that this should be implemented, but I did not find such a team. Tell me, is this team still there, or not? And if not, will it be implemented? I think the command would be very helpful.

**Comment by Levak** [comment]
The command exists in my version since 2016. Back in the days, there was a lot of troubles with account stealing and I was scared that it would be used for evil purposes - log onto victim accounts and destroy the clans.

Then I left in place clan management/display. E.g. #109

**Comment by wnull** [comment]
@Levak, thank you for your explanation.
