### ISSUE TITLE
BR - 1.18000.944.21500

### ISSUE THREAD

**Issue by Stealth760** [Levak/warfacebot#358]
Is it okay for me to use wrong "game_crypt_iv" and "game_crypt_key"?

Because in the BR file is the version "1.17400.907.21500" but in fact the game here is in the version "1.18000.944.21500".

So I just changed the version in the file and the bot worked.
But can the accounts get banned for this or does the distributor find something wrong at login?
like "this guy logged in with a different version, how did he do that?"
(Google Translate)

**Comment by Levak** [comment]
The "crypt key" is only used when encryption is enforced by the lobby server. I believe BR and VN servers do not enforce encryption, hence, changing just the game version is enough.

You are safe to do the change.
