### ISSUE TITLE
Connection error/timed out

### ISSUE THREAD

**Issue by wnull** [Levak/warfacebot#359]
When migrating from one server (HDD+SSD) to another (SSD), the following problem occurred: when you try to authorize, after 15-25 seconds, you receive a message about the connection being lost. There are no such issues on the primary server. On both machines Ubuntu 16.04 costs.
```
root@wnulltest:/warfacebot# bash testbot.sh
Connecting...
g_language = english
online_pvp_rank = 20
wb_accept_friend_requests = 1
wb_postpone_friend_requests = 0
wb_accept_clan_invites = 1
wb_postpone_clan_invites = 0
wb_enable_invite = 1
game_hwid = 123451550
online_server = s0.warface.ru
game_manual_profile_creation = 1
game_server_name = ru-alpha
game_version = 1.19900.1853.22400
game_crypt_iv = 834724096,29884556,849283813,14157667,779975000,969872986,327122214,893084885
game_crypt_key = 857804272,440128688,1219254068,4120703532,2057076187,2360279996,176240007,983734302,222413547,2854675118,726515478,3809921716,3759250121,466968803,2212697897,277959925,340892182,901640921,1110570707,3415469659,2542854728,2110438451,280882402,2013944917,2691179828,3376809656,3250560467,1242959575,667629373,4070972441,756101719,1907718504

Warfacebot Copyright (C) 2015-2017 Levak Borok
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see AGPLv3 Terms for details.


ERROR connect
Connection timed out
Warface Bot closed!
root@wnulltest:/warfacebot# 
```
Also, I decided to try to reinstall the server several times, and do everything without a backup, but from scratch, installing all the necessary packages. But the problem remained. What could be the reason? Here is a [list of installed packages](https://pastebin.com/raw/eDHJsW4U).

**Comment by Levak** [comment]
I see that you are connecting on the Russian server.
1. Are you aware if there are potentially "other" users of bots on the same data center?
2. Did you properly copied/created a cfg file containing `game_hwid` different than 0?

**Comment by wnull** [comment]
And so, in order:

1. 	Ping check on the server where the bot **works** stably.
	```
	root@iampressive:/# ping s1.warface.ru
	PING s1.warface.ru (178.22.91.203) 56(84) bytes of data.
	64 bytes from 178.22.91.203: icmp_seq=1 ttl=55 time=2.30 ms
	```

	Ping check on the server where the bot **does not work**.
	```
	root@wnulltest:~# ping s1.warface.ru
	PING s1.warface.ru (178.22.91.203) 56(84) bytes of data.
	64 bytes from 178.22.91.203: icmp_seq=1 ttl=56 time=2.12 ms
	```
	I do not see a problem in this. 
2. Here I do not quite understand what it was about and how to check it. But if it concerns here are other bot connections in this sector, the answer is no.
3. With regards to `game_hwid` problems should not be, because when you run the bash file I have it automatically generated ([#111](https://github.com/Levak/warfacebot/issues/111#issuecomment-322962175)).
	At least on the main server, this generation helps to run many bots at the same time.
<hr>

@Levak, i would like to ask with regards to installing [Cygwin packages](https://github.com/Levak/warfacebot#step-by-step) on **ubuntu 16.04** server. 

The method of [apt-cyg](https://github.com/transcode-open/apt-cyg#quick-start), which hangs on the internet, does not work. And have to do something kind of bike, installing the required packages in different ways. 

Could this be the cause of this error? If so, what should you pay attention to? And do you have any recommendations on how to properly install packages on ubuntu?

**Comment by Levak** [comment]
> And so, in order:

It doesn't make sense to me that you get a "connection time out" but can ping the server just fine. In your log you were trying to connect to Alpha (s0.warface.ru, but your ping is to Bravo (s1.warface.ru), idk if it makes any difference.

Try this?
```
echo 'ping' | netcat s0.warface.ru 5222 -
```

Should return something like that:
```
�����<?xml version='1.0'?><stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' id='0' from='warface' version='1.0'>����_<stream:error><xml-not-well-formed xmlns='urn:ietf:params:xml:ns:xmpp-streams'/></stream:error>
```

> @Levak, i would like to ask with regards to installing Cygwin packages on ubuntu 16.04 server.

Why are you trying to use Cygwin on ubuntu?
On ubuntu, simply use `apt-get install` followed by the packages listed.

**Comment by wnull** [comment]
> It doesn't make sense to me that you get a "connection time out" but can ping the server just fine.  In your log you were trying to connect to Alpha (s0.warface.ru), but your ping is to Bravo 
(s1.warface.ru), idk if it makes any difference.

Sorry, i didn't happen to notice that there was a Bravo server selected, but the results are identical to those on Alpha.

> Try this?
> 
> ```
> echo 'ping' | netcat s0.warface.ru 5222 -
> ```

On a running server:
```
root@iampressive:/warfacebot3# echo 'ping' | netcat s0.warface.ru 5222 -
�����<?xml version='1.0'?><stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' id='537903281' from='warface' version='1.0'>����_<stream:error><xml-not-well-formed xmlns='urn:ietf:params:xml:ns:xmpp-streams'/></stream:error>����</stream:stream>invalid port
```
On a server that is not running:
```
root@wnulltest:/# echo 'ping' | netcat s0.warface.ru 5222 -
invalid port
```
On a non-running server, it issues an `invalid port`, although on a production server, it gives the same `invalid port` response at the end of the xml. I don't know what it's about, it's weird. Can this be solved?

**Comment by Levak** [comment]
Your results clearly reveal a problem / block of the 2nd server, unrelated to warfacebot. Not sure how I can help there. I gave you all the elements I could to debug the  problem on your own.

Please keep in mind that mycom/mailru may want to block access from dedicated servers (that's what they do on EU/NA).

**Comment by wnull** [comment]
All the same I do not understand why one server works, and another is not present. Although they have one sector. At the moment, I have completely replaced the VDS servers, and they all work fine. Thank you very much for your advice.
