### ISSUE TITLE
I can not run the bot on A VMware virtual machine

### ISSUE THREAD

**Issue by Carlsberg34** [Levak/warfacebot#360]
Hi, Levak!
I installed a virtual machine and I have this error, what to do? 
![bandicam 2019-10-06 02-16-00-543](https://user-images.githubusercontent.com/53007121/66261961-88c35b80-e7d7-11e9-932e-19acab01ee8e.jpg)

**Comment by Levak** [comment]
I guess you need to update the internet explorer version on that virtual machine?

**Comment by Carlsberg34** [comment]
updated internet explorer and the error disappeared
Thanks)
