### ISSUE TITLE
after yesterday's update on RU-WF writes this: " failed to get accounts profile" 

### ISSUE THREAD

**Issue by Carlsberg34** [Levak/warfacebot#361]
![bandicam 2019-10-09 19-31-14-671](https://user-images.githubusercontent.com/53007121/66501038-ed760300-eac2-11e9-8299-519568e0d8ed.jpg)

**Comment by Carlsberg34** [comment]
And how to find out what version of the game? I on your site watched

**Comment by Levak** [comment]
By using the correct file in the first place:
https://github.com/Levak/warfacebot/blob/master/cfg/server/ru-alpha.cfg

You seem to have copied only keys, and forgot to update game version.
