### ISSUE TITLE
Помогите запустить бота

### ISSUE THREAD

**Issue by Rustamom** [Levak/warfacebot#365]
Вроде прочитал все, но ничего не получилось.

 Скачал для начала warfacebot по этой ссылке: https://github.com/Levak/warfacebot.git  . Запустил wb_launcher.hta ввел правильные логин и пароль от второго аккаунта, нажал "войти", но после этого ничего не произошло. Если же ввожу неправильный логин и пароль, то окно зависает и приходится его перезапускать.

 Затем скачал warfacebot-mingw-1.0.15b.zip по вот этой ссылке: https://github.com/Levak/warfacebot/releases/download/1.0.15b/warfacebot-mingw-1.0.15b.zip

Запустил wb_launcher, прошел авторизацию, открылась консоль cmd. Я начал пробовать ввести команды, но бота(второй аккаунт) я в сети не видел(он у меня уже был в друзьях), пробовал ввести несколько команд, но безуспешно. При создании карты через консоль мне отвечали, что данной карты не существует. 

**Пробовал все это дело на VMware, где нет ни Warface, ни игрового центра**

**Explorer 11 скачан**

Google translate:

It seems I read everything, but nothing worked.

First I downloaded warfacebot from this link: https://github.com/Levak/warfacebot.git. Launched wb_launcher.hta and pressed "enter", but after that nothing happened. If the window hung and had to restart it.

Then I downloaded warfacebot-mingw-1.0.15b.zip from this link: https://github.com/Levak/warfacebot/releases/download/1.0.15b/warfacebot-mingw-1.0.15b.zip

I launched wb_launcher, passed authorization, the cmd console opened. I tried to enter several commands, but he was not friends, he tried to enter several commands, but to no avail. When creating a card through the console, they answered me that this card does not exist.

**I tried the whole thing on VMware, where there is no Warface, no game center.**

**Explorer 11 downloaded**
 
![image](https://user-images.githubusercontent.com/48911064/68080781-3cd5f780-fe13-11e9-8770-e00060909a06.png)

**Comment by Levak** [comment]
You have to update crypt keys in `cfg` folder with up to date ones.

**Comment by Rustamom** [comment]
> You have to update crypt keys in `cfg` folder with up to date ones.

So today I just downloaded warfacebot

**Comment by Levak** [comment]
> So today I just downloaded warfacebot (Google translate)

You've downloaded the binary version 1.0.15b, which contain old encryption keys. Pair it with the repository encryption keys.

**Comment by Rustamom** [comment]
> > So today I just downloaded warfacebot (Google translate)
> 
> You've downloaded the binary version 1.0.15b, which contain old encryption keys. Pair it with the repository encryption keys.

Thanks, it's work
