### ISSUE TITLE
How can I enable a free connection when creating a room?

### ISSUE THREAD

**Issue by Rustamom** [Levak/warfacebot#368]

**Comment by Levak** [comment]
Explain? I don't understand your request.

**Comment by Rustamom** [comment]
![image](https://user-images.githubusercontent.com/48911064/68396561-cd4d6880-0182-11ea-82a8-ab984b6aabe9.png)
to turn it on

**Comment by Levak** [comment]
It's compiled by default to create only private rooms.

To change that behavior you will need to go in the source code and remove the `ROOM_PVP_PRIVATE` flag, then recompile.

https://github.com/Levak/warfacebot/blob/master/src/cmd/cmd_open.c#L35

**Comment by Rustamom** [comment]
How recompile this apps?

**Comment by Rustamom** [comment]
h

**Comment by Rustamom** [comment]
I edited the file like this

if (!cvar.wb_safemaster)
        flags = PVP_ALLOWJOIN ;


But "free connection" also doesn't work

**Comment by Rustamom** [comment]
Help me pls
