### ISSUE TITLE
 how to compile the program?

### ISSUE THREAD

**Issue by Rustamom** [Levak/warfacebot#369]
I am trying to compile warfacebot via cygwin, but for some reason it fails. What am I doing wrong?

![image](https://user-images.githubusercontent.com/48911064/68416430-891f8f80-01a5-11ea-92cc-62f8f32a4f61.png)
![image](https://user-images.githubusercontent.com/48911064/68416529-b53b1080-01a5-11ea-9afd-3d9eb286f0fe.png)

**Comment by Levak** [comment]
> What am I doing wrong?

You are lacking basic understanding of the command line functions. For that, I cannot help.
"cd" means "change directory"
"make" is a program that reads "Makefile" and executes the commands in it.

The README file details steps to follow. Your screenshots show that you are copy pasting them without understanding what they do. That's not how you should proceed.

Izvinitie.

**Comment by Rustamom** [comment]
Thanks! 
I’ll go to understand
