### ISSUE TITLE
Why Failed to change room settings (8:0)?

### ISSUE THREAD

**Issue by Rustamom** [Levak/warfacebot#375]

**Comment by Levak** [comment]
Hello,
Which publisher? (RU/EU/other)
Which game version? (there was an update on RU for instance)
Which mode? (PVP/PVE)
What are you trying to do?

**Comment by Rustamom** [comment]
I'm trying to turn on"Allow join" in room 32players

**Comment by Levak** [comment]
You can't have 32 players room.

**Comment by Rustamom** [comment]
s

**Comment by Rustamom** [comment]
When I create a room it is automatically created for 32 players
