### ISSUE TITLE
How can i fix this ?

### ISSUE THREAD

**Issue by psychowf** [Levak/warfacebot#384]
echo   -DHAVE_STRNDUP > .opt
gcc -Wall -Wextra -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -O2 -MMD -Iinclude -Ithird_party -DZLIB -DUSE_TLS -pthread -DHAVE_STRNDUP   -c -o src/threads/thread_readline.o src/threads/thread_readline.c
src/threads/thread_readline.c:29:31: fatal error: readline/readline.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'src/threads/thread_readline.o' failed
make: *** [src/threads/thread_readline.o] Error 1

**Comment by Levak** [comment]
By installing the required libraries. In this case libreadline-devel (5 or 6)

**Comment by psychowf** [comment]
After install i get this only :

echo   -DHAVE_STRNDUP > .opt
