### ISSUE TITLE
Temprorary bans

### ISSUE THREAD

**Issue by alexalok** [Levak/warfacebot#39]
After using bot for a few minutes, it's getting disconnected and account behind it is getting banned for approx. 24 hours.

```
##==(324)=> <iq xmlns='jabber:client' to='k01.warface' from='***@warface/GameClient' id='uid00000007' type='get' ><query xmlns='urn:cryonline:k01'><join_channel version='1.14000.4034.32100' token=' ' region_id='global'     profile_id='***' user_id='***' resource='pve_3'     hw_id='0' build_type='--release'/></query></iq>

<-(538/538)== <iq from='masterserver@warface/pve_3' to='***@warface/GameClient' xml:lang='en' id='uid00000007' type='result'><query xmlns='urn:cryonline:k01'><join_channel version='1.14000.4034.32100' token=' ' region_id='global' profile_id='***' user_id='***' resource='pve_3' hw_id='0' build_type='--release'/></query><error type='continue' code='8' custom_code='3'><internal-server-error xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas' xml:lang='en'>Custom query error</text></error></iq>

Failed to join channel (Banned)
```

**Comment by alexalok** [comment]
So far, it seems that setting HWID to any valid value solves the issue. I'll report if anything changes.

**Comment by Levak** [comment]
No plan on fixing this in an automated way
Simply set `game_hwid` in `wb.cfg`

**Comment by ptaking** [comment]
@alexalok Where can I get a valid HWID?

**Comment by alexalok** [comment]
> Where can I get a valid HWID?

Generally, any 9-digit number works, However, it may vary for realms other than RU/TR (I do not use bot for other realms).

> I got error code='8' custom_code='8'

Again, I can't tell for other realms, but on RU it seems to be the case if you restart bot in a quick succession, perhaps its presence on "old" channel from past relog isn't expiring in time or other strange things happen. Maybe the bot's author can provide you with more details.

> Is that also a temporary ban?

Tempban on RU works in a different way, it blocks connection by IP.
