### ISSUE TITLE
ERROR connect, Resource temporarily unavailable

### ISSUE THREAD

**Issue by shockwaves** [Levak/warfacebot#393]
Hi
Environment: WSL
It's always worked with **wb.sh** but today faced with connection error:

![image](https://user-images.githubusercontent.com/2717689/71601821-d264dd80-2b5d-11ea-9a24-8fddd709e44b.png)

**Comment by Carlsberg34** [comment]
Same problem. The console closes in 3-4 seconds. Changed in cfg / server/ ru alpha

**Comment by Levak** [comment]
I confirm the issue only on ru-alpha. Bravo and Charlie seem to work fine.

St first sight it seems to be a socket error, as if they changed domain name.

> Same problem. The console closes in 3-4 seconds. Changed in cfg / server/ ru alpha

What did you change to make it work?

**Comment by Carlsberg34** [comment]
On December 23, the update was released on the bot. I put it on and it worked. And since yesterday, the console closes in 3 seconds

**Comment by Carlsberg34** [comment]
mail.ru something has changed))

**Comment by Carlsberg34** [comment]
And how long will the problem with the bot be solved? ( google translator)

**Comment by Levak** [comment]
I am not home, I cannot tell what's wrong unless someone else shares it here

**Comment by Levak** [comment]
See 4ba3c80

**Comment by Carlsberg34** [comment]
Thanks. It's work
