### ISSUE TITLE
What next?

### ISSUE THREAD

**Issue by D4rckey** [Levak/warfacebot#396]
Hello. What do next? I dont know what i need write to start bot
![image](https://user-images.githubusercontent.com/31608371/72222436-7733e180-3586-11ea-9983-baace0b1fd97.png)

**Comment by Levak** [comment]
You have downloaded sources only. You have to compile the bot yourself - else download windows binaries if you are under Windows. 
https://github.com/Levak/warfacebot/releases

**Comment by D4rckey** [comment]
its termux for android. how to compile it?

**Comment by Levak** [comment]
> how to compile it?

Install the dependencies (depends on your distribution) and compile it.

> $ make

Refer to the README for dependencies, or just read what `make` tells you is missing.

**Comment by D4rckey** [comment]
i cant compile
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:229: wb] Error 1

**Comment by D4rckey** [comment]
https://pastebin.com/V1n8X26K all logs

**Comment by Levak** [comment]
https://stackoverflow.com/questions/1662909/undefined-reference-to-pthread-create-in-linux
