### ISSUE TITLE
FFA 32 players [WFRU]

### ISSUE THREAD

**Issue by Endreman** [Levak/warfacebot#399]
Hi Levak, please tell me how to create a room for 32 people in "FFA" mode - "Widestreet" map?
I can only create a royal battle. Please see the screenshots.

https://prnt.sc/qnpd6n

and

https://prnt.sc/qnpde5

**Comment by Endreman** [comment]
I was told that this is done in your bot, but by which team and how is it implemented?

**Comment by Levak** [comment]
You cannot create a room with 32 players.

**Comment by Endreman** [comment]
Why can't I create a room? But what about the screenshots that I attached?
