### ISSUE TITLE
Proxy, reconnect, account's data in cfg

### ISSUE THREAD

**Issue by D4rckey** [Levak/warfacebot#400]
Hi, Levak. How about to add support of proxy server(optional), it is need for some bots. Also I don't won't write my login and password every time. I suggest add function save datas in wb.cfg (If no start arguments datas will taken from wb.cfg, if user indicates self cfg - from this cfg). And ofc auto reconnect after losing connection.

**Comment by seanwlk** [comment]
except the proxy, which you can do by yourself by running it on the client, the rest you asked already exist in the project if you use the dbus manager https://github.com/Levak/warfacebot/blob/master/wbd_launcher

**Comment by D4rckey** [comment]
Oh, thanks

**Comment by D4rckey** [comment]
![image](https://user-images.githubusercontent.com/31608371/72439146-30352e80-37c8-11ea-842b-3199db6def79.png)

**Comment by Levak** [comment]
1. Indeed, "build" is not defined.
2. You have to compile warface it in DBus mode: `make clean manager`

**Comment by D4rckey** [comment]
>You have to compile warface it in DBus mode: make clean manager

![image](https://user-images.githubusercontent.com/31608371/72439869-8eaedc80-37c9-11ea-86bf-fdcf2cfb0f51.png)

**Comment by Levak** [comment]
Install Dev packages of gdbus etc.

**Comment by D4rckey** [comment]
> Install Dev packages of gdbus etc.
but this is an error of missing file, or am I mistaken?

**Comment by Levak** [comment]
> but this is an error of missing file, or am I mistaken?

The missing file is on your distribution. It's missing development headers for the packages used. You need to install Dev packages of gdbus. Probably others I forgot. Google is your friend.

**Comment by Levak** [comment]
On utuntu `libglib2.0-dev`

**Comment by D4rckey** [comment]
Thanks a lot. What about auto reconnect?

**Comment by wnull** [comment]
@D4rckey, i don't think this should be included in the build. You can use the process Manager, or some daemon for this, of course, if you are working with the console. IMHO.
