### ISSUE TITLE
How to open LMS room after creation? 

### ISSUE THREAD

**Issue by AzizjanT** [Levak/warfacebot#401]
Hello, Levak. 

I create a LMS room using your bot, but it is a private room, and i can't open it, just send invite command to bot for entering room. 

And second, this room doesn't appear in channel room list.

Will be glad if you help me)

**Comment by wnull** [comment]
@AzizjanT, Hi!

This is due to the setting properties of the room. I don't know if this is correct, but as an option, for a workaround, you can do the following: create a room yourself, then give the master (crown) to the bot and then change the room to the desired one using the `change` command.
