### ISSUE TITLE
bot login but not showing in the game

### ISSUE THREAD

**Issue by Mohamed-Slimane** [Levak/warfacebot#417]
hi
i have problem in all windows 10 version
when i login . the login working correctly but after cmd window the bot not showing online in the game
the same files tested in windows 7 and its working ? and the bot showing

the problem append in my pc with windows 10 . and still not working after reinstall windows 10
and not working in virtual server with windows server 2016

this is image from windows 10 after login 
the same problem with git commander. and i have changed the game_hwid but not working
![Screenshot_3](https://user-images.githubusercontent.com/23380229/75622810-b2c15400-5ba4-11ea-9215-a700a4bfa7a6.png)
 too

**Comment by Levak** [comment]
> the same files

No. You forgot to update your encryption keys
https://github.com/Levak/warfacebot/blob/master/cfg/server/eu.cfg

**Comment by Mohamed-Slimane** [comment]
> > the same files
> 
> No. You forgot to update your encryption keys
> https://github.com/Levak/warfacebot/blob/master/cfg/server/eu.cfg

i love you man
