### ISSUE TITLE
how to make it stay all times

### ISSUE THREAD

**Issue by Mohamed-Slimane** [Levak/warfacebot#418]
hi
i have server and i want to make the bot online 24/24 . to help

**Comment by Levak** [comment]
It is not possible anymore on EU/NA/RU because of MRAC.
You have to make it log on again after 2-5min with a script.

**Comment by Mohamed-Slimane** [comment]
Oh thank you man

**Comment by Mohamed-Slimane** [comment]
this worked for me 
`<script>
      setInterval(function() {
		login()
		}, 40 * 1000);
	</script>`
