### ISSUE TITLE
New Updat 04/03/2020

### ISSUE THREAD

**Issue by Mohamed-Slimane** [Levak/warfacebot#422]
hi livak
we have new update in game
can you tell me how to fix it .the stooping work after every u^pdat

**Comment by Levak** [comment]
You simply fetch the updated cfg files from https://github.com/Levak/warfacebot/tree/master/cfg/server

I have set up a bot that will check for game updates and generate the encryption keys.

**Comment by Mohamed-Slimane** [comment]
thank you very match levak
