### ISSUE TITLE
ru-charlie.cfg!!

### ISSUE THREAD

**Issue by RedTwink** [Levak/warfacebot#426]
Is this version still relevant today? An update for the game was recently released.

**Comment by Levak** [comment]
"recently" = ?
I have a bot that checks the updates for RU, RU-PTS, EU and NA automatically.

**Comment by Levak** [comment]
I just checked my game version for RU and it's the correct one here: 
https://github.com/Levak/warfacebot/blob/master/cfg/server/ru-charlie.cfg

**Comment by RedTwink** [comment]
Why is there an error on startup? I didn't do anything with the folder( 
Error: an ID, string , or number is assumed
![Хуита](https://user-images.githubusercontent.com/62310190/76951523-7fa4f180-6914-11ea-9d69-90228cf79625.PNG)

**Comment by RedTwink** [comment]
I did everything, but now the question is , how do I run multiple bots? One starts, and when the other starts , it falls.

**Comment by Levak** [comment]
> Why is there an error on startup? I didn't do anything with the folder(
Error: an ID, string , or number is assumed

I see on your screenshot that you are not using the latest release. It contains a fix for IDNs on RU server: 
https://github.com/Levak/warfacebot/releases/tag/1.0.16b

(after that, don't forget to update the crypt keys I've linked in my first post)

> I did everything, but now the question is , how do I run multiple bots? One starts, and when the other starts , it falls.

An account can only connect to the server once. 
I believe on RU there is another restriction that filters HWID too. Change it, assign one per bot `game_hwid`.

**Comment by RedTwink** [comment]
Sorry, I 'm stupid! How do I assign it to each bot?

**Comment by Levak** [comment]
> Sorry, I 'm stupid! How do I assign it to each bot?

In `wb.cfg`.
If you don't intend to script warfacebot yourself, the easiest is to duplicate the folder and in each have a different `wb.cfg`

**Comment by RedTwink** [comment]
All, thank you very much!) Everything works)
