### ISSUE TITLE
Error 348!

### ISSUE THREAD

**Issue by RedTwink** [Levak/warfacebot#431]
It works on the main PC. On a laptop with the same Wi-Fi and files transferred from the main computer, this does not work. Warface is installed on this computer

![cp8UFJnnDro](https://user-images.githubusercontent.com/62310190/77576992-bebbdf80-6ede-11ea-9f09-6f1d637711bd.jpg)

**Comment by Levak** [comment]
Update Internet Explorer?

**Comment by RedTwink** [comment]
It is not older there than on the main PC, where everything works

**Comment by Levak** [comment]
I do not know Russian very well.
Does it say "Expected identifier, string or number" at line 348, character 13?

There is nothing there that may suggest any issue:
https://github.com/Levak/warfacebot/blob/master/wb_launcher.hta#L348

Are you using EU/NA?
When does the error appear?

**Comment by Levak** [comment]
Ok, maybe this:
http://loco.ru/materials/300-sluchai-vozniknoveniya-oshibki-v-ie-predpolagaetsya

"continue" should be quoted.
Try to replace:
```
            continue: 'https://auth-ac.my.games/sdc?from=https%3A%2F%2Fapi.my.games%2Fsocial%2Fprofile%2Fsession',
```
with
```
            'continue': 'https://auth-ac.my.games/sdc?from=https%3A%2F%2Fapi.my.games%2Fsocial%2Fprofile%2Fsession',

```

**Comment by RedTwink** [comment]
The error appears on startup (wb_launcher.hta) line 348 character 13

**Comment by Levak** [comment]
> The error appears on startup (wb_launcher.hta) line 348 character 13

Modify wb_launcher.hta as I said. Add quotes around "continue".

**Comment by RedTwink** [comment]
Now error: line 516 character 7

**Comment by Levak** [comment]
> Now error: line 516 character 7

Ok, this is clearly your internet explorer version. Update it.

**Comment by RedTwink** [comment]
All done! Thanks
