### ISSUE TITLE
Is the north American server available? 

### ISSUE THREAD

**Issue by lvzusheng** [Levak/warfacebot#436]
Is the north American server available? Why is there no response when I send the friend request? I log in to accept the friend request, and then restart the bot, but it is offline on my main account
![RVZDD(RF`R82{@ F8L(UBA](https://user-images.githubusercontent.com/13249430/78270592-9adf4600-753d-11ea-8b8d-290b969d9fba.png)

**Comment by Levak** [comment]
You are using expired encryption keys. 
Update them: 
https://github.com/Levak/warfacebot/blob/4d4f48734f019cb446ae4e1ad25f5562814958c9/cfg/server/na.cfg

**Comment by lvzusheng** [comment]
Thank you very much. It looks like it's working, but it's been running for less than two minutes and the connection goes down. Why?By the way, where do I need to get the above.
![QQ截图20200403002037](https://user-images.githubusercontent.com/13249430/78273319-3e7e2580-7541-11ea-8367-1713eaeb87ae.png)

**Comment by Levak** [comment]
> but it's been running for less than two minutes and the connection goes down. Why?By the way, where do I need to get the above.

MRAC kicks any account not running the anti-cheat heartbeat.
warfacebot doesn't implement the anti-cheat heartbeat for obvious reasons.

**Comment by lvzusheng** [comment]
Okay, thanks, so what do I need to do.Is it necessary to start the game as soon as possible before the connection drops?

**Comment by Inclyde** [comment]
Tell me I can not start from windows
