### ISSUE TITLE
Mail.ru не запускается на Северной Америке

### ISSUE THREAD

**Issue by mracking** [Levak/warfacebot#437]
Здравствуйте Левак. Что нужно сделать, что бы запускать ботов зарегистрированных на mail.ru на сервере Северной Америке? За ранее спасибо!

**Comment by Levak** [comment]
> Hello Levak. What needs to be done to launch bots registered on mail.ru on a North America server?

You mean, the email is @mail.ru, or the account is registered on RU server?

With a @mail.ru email address, just log in with email+pass, nothing particular. You have to be in non-blocked countries to log on EU/NA. Russia is blocked for instance.
