### ISSUE TITLE
warface cmd closing

### ISSUE THREAD

**Issue by Joker1239** [Levak/warfacebot#438]
I'm trying the warface bot, but as I put the login and password in the launcher, open the CMD and it closes in 1 second, my server is BR
sorry for my english, i'm using google translator

**Comment by Levak** [comment]
- Can you see what is written in the console?
- Have you updated the game version in `cfg/server/br.cfg`?

**Comment by Joker1239** [comment]
No, I can't, he close in 1 second and i'm using the last version

**Comment by Joker1239** [comment]
I made it! I did a download of other version and changed cfg, how you said, thanks :D

**Comment by Levak** [comment]
> I made it! I did a download of other version and changed cfg, how you said, thanks :D

Interesting. What version did you use to make it work?

**Comment by Joker1239** [comment]
1.0.13

**Comment by Levak** [comment]
And I suppose 1.0.14 and 1.0.15 didn't work either?

**Comment by Joker1239** [comment]
Exactly

**Comment by Levak** [comment]
What is the rank of the account you are trying to log on?

**Comment by Joker1239** [comment]
Level 6
In server br the minimum to go for professional is level 40
One more question. The accounts placed on warfacebot have a risk of being banned?

**Comment by nathan130200** [comment]
> One more question. The accounts placed on warfacebot have a risk of being banned?<br/>

You must use fake accounts, actually stupied Level Up! brain is dead and they think that warfacebot is a hacking software, and ban your account. Like #124 that fake account that i used got ban.

**Comment by Joker1239** [comment]
Vi que você é br. Eu to falando de usar as contas no launcher do wfbot, as contas q eu colocar ali, elas tem risco de tomar ban ? Ou só a q eu usar no launcher normal do wf ?
