### ISSUE TITLE
Error "Authentication failed (Session)"

### ISSUE THREAD

**Issue by Warface2021** [Levak/warfacebot#439]
Good evening. When I log into my mygames.NA account, the following message "Authentication failed (session)" is displayed. What can this be and how do I fix it? I already edited the code for the new version.
I have also tried several accounts.

**Comment by Levak** [comment]
This error doesn't ring me any bell. My boys are working fine on NA. And servers seem to be up and running.
Do you have a screenshot?

**Comment by Warface2021** [comment]
![image](https://user-images.githubusercontent.com/63530743/79186940-51221580-7df1-11ea-9041-39e2cc1c6e55.png)

**Comment by oilujgomes** [comment]
![image](https://user-images.githubusercontent.com/64264057/80214591-7e509e00-8611-11ea-8b7e-f58cca84f504.png)

**Comment by Levak** [comment]
Do you still experience the issue? No fix has been made.
Are you able to log on the official website?
