### ISSUE TITLE
Is it possible to create a quick game And How? ru server

### ISSUE THREAD

**Issue by Ryzen228** [Levak/warfacebot#453]
You can create an example to run.

**Comment by Levak** [comment]
From the doc:
```
quickplay open ffa
quickplay start
```

**Comment by Ryzen228** [comment]
but how to call your friend?
in a quick game I try to do this, it says that a friend is not online, although he is online and if you send the add command he will be friends
Nick 721333

**Comment by Ryzen228** [comment]
quickplay open ffa 
quickplay invite 721333
quickplay start

**Comment by Levak** [comment]
Works fine for me.

**Comment by bakedbeans3** [comment]
Levak - if on NA and i want to be on a specific regionalized server such as Singapore and not Washington, which server will this command line put the quickplay game on?

**Comment by Levak** [comment]
> Levak - if on NA and i want to be on a specific regionalized server such as Singapore and not Washington, which server will this command line put the quickplay game on?

Add this in `wb.cfg`
```
online_region_id singapore
```

**Comment by bakedbeans3** [comment]
super thanks.

Another question: If i want to open a specific ffa map or any quickplay map, is there a command for the map name to be opened and a listing of the map names somewhere?

**Comment by Levak** [comment]
> Another question: If i want to open a specific ffa map or any quickplay map, is there a command for the map name to be opened and a listing of the map names somewhere?

It's written in the README and you get auto-completion by pressing TAB. All maps are there.
```
quickplay open pvp
quickplay open ffa_forest
```

**Comment by bakedbeans3** [comment]
I read the READ ME in the folder of the wbot but didnt see the map names,  Are you referring to a different document?

**Comment by bakedbeans3** [comment]
Hi Levak - please help me find the correct READ me to follow

**Comment by Levak** [comment]
> Hi Levak - please help me find the correct READ me to follow

https://github.com/Levak/warfacebot#owner-only-commands

**Comment by bakedbeans3** [comment]
So the owner only commands i put the command Ryzen228 suggested for starting a quickplay ffa and inviting a friend (myself) in the wb.cfg file and i guess i expected an invite from the bot to quickplay and nothing happened.

**Comment by Levak** [comment]
> inviting a friend (myself) in the wb.cfg file and i guess i expected an invite from the bot to quickplay and nothing happened.

`wb.cfg` is a config file, not a script file for commands. You can only put cvars in it, not commands.
To have auto-start commands, the feature #457 needs to be implemented (when I will have free time).

**Comment by bakedbeans3** [comment]
ok thanks for the differentiation on cvars and commands.

above you wrote "It's written in the README and you get auto-completion by pressing TAB. All maps are there."

I presumed this would work, but not for me.

**Comment by bakedbeans3** [comment]
argh the bots are doing ping time out on quickplay

**Comment by bakedbeans3** [comment]
Levak at the cmd prompt once the bot is loaded in, I am able to invite my friend, however, after roughly 20 seconds the quickplay session ceases.

**Comment by Levak** [comment]
> 20 seconds the quickplay session ceases.

You mean the bot crashes due to MRAC?
That's "normal" and I cannot fix this. If I do implement MRAC, cheaters can copy it and make their own anti-MRAC bypass.

**Comment by bakedbeans3** [comment]
i figured it was MRAC kicking the no heart beat on the bot.

So the quickplay option is only effective for invites say less than 30 seconds in que?

**Comment by Levak** [comment]
> So the quickplay option is only effective for invites say less than 30 seconds in que?

I implemented the quickplay logic in 2016-2017 way before MRAC appeared in April 2017. Sooo, yeah.
