### ISSUE TITLE
Launch pvp rooms

### ISSUE THREAD

**Issue by lite231231** [Levak/warfacebot#458]
I used the version of 2018 and this script worked that it needs to be changed in it so that everything works in 2020

<iq to="masterserver@warface/pvp_pro_075_r1" from="622498717@WARFACE/GameClient" type="get"><query xmlns="urn:cryonline:k01"><gameroom_open room_name="Комната игрока" team_id="1" status="0" class_id="2" room_type="2" private="0" mission="3889f29a-fe06-425b-9ff8-f94ffbd5307c" inventory_slot="34326183935" dead_can_chat="1" friendly_fire="1" enemy_outlines="1" auto_team_balance="0" join_in_the_process="1" time_limit="100" round_limit="12" preround_time="1" locked_spectator_camera="1" overtime_mode="1" /></query></iq>

**Comment by Levak** [comment]
Use version 1.16b
https://github.com/Levak/warfacebot/releases/tag/1.0.16b
