### ISSUE TITLE
Error when run make wbd

### ISSUE THREAD

**Issue by ngoducdat** [Levak/warfacebot#46]
![screenshot_2016-12-30-19-37-13](https://cloud.githubusercontent.com/assets/24789884/21565203/989961de-cec7-11e6-90e0-66145d84ccc6.png)

**Comment by Levak** [comment]
Are you trying to run `make wbd` instead of `make manager` ?

**Comment by ngoducdat** [comment]
Make manager
It worked

**Comment by ngoducdat** [comment]
![screenshot_2016-12-31-10-09-33](https://cloud.githubusercontent.com/assets/24789884/21575539/72afef86-cf41-11e6-8383-d565b12613c9.png)

Make manager. 
It worked

**Comment by ngoducdat** [comment]
How to log in to multiple accounts at once ?

**Comment by ptaking** [comment]
@ngoducdat Open a new terminal session to login to another account
