### ISSUE TITLE
Compile Error - Valgrind API

### ISSUE THREAD

**Issue by Weser87** [Levak/warfacebot#469]
src/stream/tls.o src/stream/tls.c
src/stream/tls.c:39:12: fatal error: valgrind/memcheck.h: No such file or directory
   39 | #  include <valgrind/memcheck.h>
      |            ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<встроенное>: src/stream/tls.o] Error 1

How can I fix the error?

**Comment by Levak** [comment]
Weird, it shouldn't try to use valgrind API if it's not available on your machine.

https://github.com/Levak/warfacebot/blob/master/Makefile#L36

What is your Linux distribution?

If you just want to fix the error, remove the line I linked.

**Comment by Weser87** [comment]
i am using cygwin
![image](https://user-images.githubusercontent.com/65085903/85015112-19787680-b170-11ea-8d53-a61dd9c6a1bf.png)
