### ISSUE TITLE
Missing cygwin1.dll

### ISSUE THREAD

**Issue by PepikCZ** [Levak/warfacebot#47]
Hello when i try to run the bot from the html launcher i click login it runs the wb.exe but says that cygwin1.dll and several more dlls are missing can you help me please
Thanks.

**Comment by Levak** [comment]
If you compiled warfacebot using Cygwin, you'll need to copy the missing DLL from cygwin over to warfacebot folder. I don't know them by heart, but that's the main reason why the official releases are using mingw to give a native win32 support.

FYI, Cygwin is an abstraction layer for POSIX functions on Windows. Thus, the compilation support is greater (no code modification needed) than MinGW, but it requires the Cygwin runtime (the missing DLLs) to run properly.

**Comment by PepikCZ** [comment]
Thanks everything working properly now.
