### ISSUE TITLE
loop the bot

### ISSUE THREAD

**Issue by I-LOVE-C2H5OH** [Levak/warfacebot#471]
can I loop the bot?

**Comment by Levak** [comment]
If you mean auto restart, that is not a feature planned.

**Comment by franchesko1437** [comment]
![image](https://user-images.githubusercontent.com/29465298/85210329-a32e6c80-b347-11ea-903a-09362518dbe5.png)
Имеется)

**Comment by rizop** [comment]
> ![image](https://user-images.githubusercontent.com/29465298/85210329-a32e6c80-b347-11ea-903a-09362518dbe5.png)
> Имеется)

Есть варик настроить себе такой же с помощью тебя ?$$?

**Comment by MorningStar32** [comment]
> ![образ](https://user-images.githubusercontent.com/29465298/85210329-a32e6c80-b347-11ea-903a-09362518dbe5.png)
> Имеется)

Сможешь подсказать как авторестарт организовать
