### ISSUE TITLE
the bot doesn't start

### ISSUE THREAD

**Issue by I-LOVE-C2H5OH** [Levak/warfacebot#472]
![image](https://user-images.githubusercontent.com/41304540/85197671-58d7cc00-b304-11ea-9419-f200b9b51760.png)
![image](https://user-images.githubusercontent.com/41304540/85198708-a6f0cd80-b30c-11ea-9ae2-492adfba5b33.png)

latest encryption keys
Ru Bravo Server

**Comment by I-LOVE-C2H5OH** [comment]
the new version doesn't work wb.exe

**Comment by Carlsberg34** [comment]
how do I open an hta file??

**Comment by Levak** [comment]
Are you doing that from your home network, or from a VPS? Are you sure the VPS has access to the game server (e.g. blocked IP)?

**Comment by I-LOVE-C2H5OH** [comment]
home network

**Comment by Levak** [comment]
> the new version doesn't work wb.exe

You mean since the migration? Have you tried the very last `wb_launcher.hta` from yesterday?

Also, what is the domain of them bot's email address? @mail.ru?

**Comment by I-LOVE-C2H5OH** [comment]
old version wb.exe fully functional, new version - not

**Comment by Levak** [comment]
Ok, let's start from the beginning:
 - which distribution? GNU/Linux or Windows Linux Subsystem or Windows
 - which build environment? Native or Cygwin or MinGW
 - which version (exact) works? (e.g. `1.0.16b`)
 - which version (exact) doesn't work? (e.g. `master`)

**Comment by I-LOVE-C2H5OH** [comment]
1) Windows
2) Cygwin
3) v1.0.14
4) v1.0.15

**Comment by Levak** [comment]
I've cloned master;
I've built it in `debug-wb` mode using Cygwin 2.10 (on Windows 10);
I've tested on EU, RU-Alpha, RU-Bravo

No issue on my side.
Did you compile yourself that 1.0.16? If so, run `make clean debug-wb` and test again. I'm interested in seeing what the debug output gives you.

**Comment by I-LOVE-C2H5OH** [comment]
![image](https://user-images.githubusercontent.com/41304540/85804331-2c400c00-b76b-11ea-9828-bea135235d09.png)
x86 (32 bit)
3.1.5 cygwin

**Comment by Levak** [comment]
If you have access to a term, try
```
(echo '<?xml>'; sleep 2) | netcat s2.warface.ru 5222
```
It should answer something. If it doesn't, you've been IP Banned.
You're the 3rd person with these symptoms, and it seems to match.

Try with alpha (`s1.warface.ru`) and charlie (`s3.warface.ru`). Try with EU (`eu-comm.wf.my.com`).

**Comment by I-LOVE-C2H5OH** [comment]
I log in through game center, and everything is fine

**Comment by Levak** [comment]
> I log in through game center, and everything is fine

You did not answer my question. 
Is the command I gave you working on RU-alpha, bravo, charlie and EU?

**Comment by I-LOVE-C2H5OH** [comment]
Yes

**Comment by aleks6923** [comment]
the bot is not included in the game room

**Comment by Levak** [comment]
Can you try this with cygwin v2.905: #105 (comment)
https://github.com/Levak/warfacebot/blob/master/src/stream/tls.c#L74
```diff
  static ssize_t _default_send(int fd, const void *buf, size_t count)
  {
-     return send(fd, buf, count, MSG_MORE);
+     return send(fd, buf, count, 0);
  }
```

**Comment by Levak** [comment]
Check with 53ebf33

**Comment by I-LOVE-C2H5OH** [comment]
thanks, all work
