### ISSUE TITLE
BOT Already In Game

### ISSUE THREAD

**Issue by bakedbeans3** [Levak/warfacebot#479]
Levak,

This week i started getting issues with loading the bots.  Bots randomly load in and while I see connecting TLS it stops the full load in.  The resulting fail message says the bot is already in game.

anyone else experiencing this issue?

**Comment by bakedbeans3** [comment]
![image](https://user-images.githubusercontent.com/66225184/85929231-58918080-b870-11ea-9ec7-4fd20f5e8807.png)

**Comment by Levak** [comment]
Which message exactly? I don't remember having put such message in the bot. Or you meant "already in the room" when inviting?

Your screenshot looks fine. What should I see?

**Comment by bakedbeans3** [comment]
It does not complete the load in.  Later it looks like this:

![image](https://user-images.githubusercontent.com/66225184/85929263-9e4e4900-b870-11ea-97e6-048d22c8a585.png)

**Comment by bakedbeans3** [comment]
this is random, one time the bot loads, the next time i get the above.  If i load 3 bots of the launcher i might be lucky for one to actually load now.

**Comment by Levak** [comment]
What the actual f.
NA server is that dead it refuses it logs in players?

**Comment by bakedbeans3** [comment]
what does that mean?

**Comment by bakedbeans3** [comment]
?

**Comment by Levak** [comment]
Channel pve_2 is dead. Hence the error.

**Comment by Levak** [comment]
While they fix it, you can try to add `online_channel_type pvp_pro` in `wb.cfg`

**Comment by bakedbeans3** [comment]
Nice fix Levak - thanks
