### ISSUE TITLE
cURL not found

### ISSUE THREAD

**Issue by stevenrd** [Levak/warfacebot#48]
**I got this issue... Please help me thx**
![test](https://cloud.githubusercontent.com/assets/25191622/22051314/792115fe-dd18-11e6-85f4-edc6c6ca8a1a.jpg)

**Comment by Levak** [comment]
Just install curl on your system via packet manager

**Comment by stevenrd** [comment]
Hi Levak, Could you help me with this? pls: 
![test](https://cloud.githubusercontent.com/assets/25191622/22083022/84ccbe8e-dda0-11e6-8257-f2c4e7a685b6.jpg)
Sorry, I am newbie :'v
