### ISSUE TITLE
Автоприсоединение к владельцу

### ISSUE THREAD

**Issue by MorningStar32** [Levak/warfacebot#486]
Привет, Levak. Можно ли как то реализовать автоприсоединение по нику?

**Comment by Weser87** [comment]
follow {NickName}

**Comment by MorningStar32** [comment]
https://github.com/Levak/warfacebot/issues/486#issuecomment-654413423
Нужно чтобы при запуске бота он сразу присоединялся к владельцу

**Comment by Levak** [comment]
See #457
