### ISSUE TITLE
Recompilation in Cygwin

### ISSUE THREAD

**Issue by wnull** [Levak/warfacebot#487]
Hi, Levak. 

I am trying to recompile the project using the `make` command, but I encountered the following problem. I installed all the necessary packages to work in Cygwin. 

![qe](https://user-images.githubusercontent.com/33278849/86744557-5e424f80-c042-11ea-9a46-b2e49a97c81c.png)

Log:
```
cc -Wall -Wextra -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -O2 -MMD -Iinclude -Ithird_party -DZLIB -DUSE_TLS    -c -o src/cmd/cmd_quit.o src/cmd/cmd_quit.c
In file included from src/cmd/cmd_quit.c:20:
include/wb_threads.h:22:11: fatal error: pthread.h: No such file or directory
   22 | # include <pthread.h>
      |           ^~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: src/cmd/cmd_quit.o] Error 1
```
What am I missing? There were no such problems in ubuntu.

**Comment by Levak** [comment]
Looks like your are missing the libpthread package on cygwin. Open up the cygwin installer and pick it up.

**Comment by wnull** [comment]
> Looks like your are missing the libpthread package on cygwin. Open up the cygwin installer and pick it up.

I installed this, but I don’t understand why the problem remains?

![](https://user-images.githubusercontent.com/33278849/86755515-5f777a80-c04a-11ea-9693-15f35867d279.png)

**Comment by wnull** [comment]
@Levak,


I installed all the packages from the `Devel` section, and that error went away. But there was a new
```
src/stream/tls.c:39:12: Fatal error: valgrind/memcheck.h: No such file or directory
   39 | #  include <valgrind/memcheck.h>
      |            ^~~~~~~~~~~~~~~~~~~~~
```

**Comment by Levak** [comment]
Yes, that valgrind error is #469  idk why it triggers on cygwin.

**Comment by wnull** [comment]
> Yes, that valgrind error is #469 idk why it triggers on cygwin.

This issue was resolved and the compilation was successful. Only on startup, nothing works (empty command window). When recompiling, this comes out:

```
wnull@DESKTOP-VETFGA2 /cygdrive/c/testing13372
$ make
rm: невозможно удалить 'a.out': No such file or directory
echo -DVALGRIND_API   > .opt
make: *** Нет правила для сборки цели «include/openssl/ssl.h», требуемой для «src/stream/tls.o».  Останов.
```
But, I installed all packages related to `OpenSSL`. When checking, it shows that the package is there:

```
wnull@DESKTOP-VETFGA2 /cygdrive/c/testing13372
$ openssl version
OpenSSL 1.1.1f  31 Mar 2020
```

Did you compile the latest release from MinGW via Cygwin?

**Comment by Lako-FC** [comment]
**._. I have problem:**
[DEBUG-WB]:
Warfacebot Copyright (C) 2015-2020 Levak Borok
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see AGPLv3 Terms for details.

Loading cached `items'
Cannot open file for reading: ./QueryCache/items.xml
Loading cached `shop_get_offers'
Cannot open file for reading: ./QueryCache/shop_get_offers.xml
Loading cached `quickplay_maplist'
Cannot open file for reading: ./QueryCache/quickplay_maplist.xml
Loading cached `get_configs'
Cannot open file for reading: ./QueryCache/get_configs.xml
##--(148)-> <?xml version='1.0' ?><stream:stream to='warface' xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' xml:lang='en' version='1.0'>
CMD#

**and.. point.. sad.. :c 
i use: warfacebot-mingw-1.0.16b, warfacebot-master (18.07.20), cygwin v2.905 (x64 and x86 use), win10 x64, actual key for server, account don't have ban and i use my IP, VPN, proxy - don't block me mail.ru, problem in new cygwin (v2.905) or new version packed. Sorry, (my English is bad)**

**Comment by wnull** [comment]
@Lako-FC, the problem is similar, I do not find a solution.

**Comment by Lako-FC** [comment]
I found a way out :) (make last warfacebot levak - 21.07.20)
@Levak  **I will soon offer a README fix with instructions for installing warfacebot levak on Windows (build).**
![image](https://user-images.githubusercontent.com/59660240/88061828-75745780-cb81-11ea-9ea7-6c51aca41899.png)

**Comment by Levak** [comment]
Can you try this: https://github.com/Levak/warfacebot/issues/105#issuecomment-322346757

**Comment by Lako-FC** [comment]
> Can you try this with cygwin v2.905: [#105 (comment)](https://github.com/Levak/warfacebot/issues/105#issuecomment-322346757)
> https://github.com/Levak/warfacebot/blob/master/src/stream/tls.c#L74
> 
> ```diff
>   static ssize_t _default_send(int fd, const void *buf, size_t count)
>   {
> -     return send(fd, buf, count, MSG_MORE);
> +     return send(fd, buf, count, 0);
>   }
> ```

Should I try it?
Need to build and run? To use debug mode?

**Comment by Levak** [comment]
> Should I try it?
 Yes please.
Debug mode is not needed, it was just to used to investigate the problem at the time.

**Comment by Levak** [comment]
I downloaded cygwin 2.905 and reproduced the problem.
The patch above fixes the issue.

**Comment by Lako-FC** [comment]
> > Should I try it?
> 
> Yes please.
> Debug mode is not needed, it was just to used to investigate the problem at the time.

I make with your change to Babun, everything works.

**Comment by Lako-FC** [comment]
Still, is it better to rewrite readme under Babun? It is lighter, faster and does not need to choose packages (or make a choice).

**Comment by Lako-FC** [comment]
I put together the latest version and get error:
`Makefile:36: *** unterminated call to function 'shell': missing ')'.  Stop.`

**Comment by Levak** [comment]
> @Levak
> I put together the latest version and get error:
> `Makefile:36: *** unterminated call to function 'shell': missing ')'. Stop.`

Yes I see it too on Travis. As I said I could not test under Linux. 
Seems like GNU/Make behaves differently on Linux and CygWIN 2.9

**Comment by Lako-FC** [comment]
I fix, check
![image](https://user-images.githubusercontent.com/59660240/88092952-bb91e100-cbaa-11ea-83b8-a83f21b71582.png)

**Comment by Levak** [comment]
Should be fine now with 53ebf33
