### ISSUE TITLE
don't work

### ISSUE THREAD

**Issue by perchec** [Levak/warfacebot#488]
after entering the login and password, the console opens and closes immediately

**Comment by Levak** [comment]
What did you download? A bin release, or sources only?
What server?

**Comment by perchec** [comment]
![Скриншот 07-07-2020 16_24_00](https://user-images.githubusercontent.com/26325026/86788083-332a2100-c07f-11ea-9c95-c0eafbc8bb75.jpg)
Server charlie

**Comment by Levak** [comment]
From that link you only get the sources and up-to-date s launchers+keys. You don't get the compiled binary WB.exe

To get that binary, you can fine it from the release tab:
https://github.com/Levak/warfacebot/releases

Copy files from the sources onto the binary release to get up-to-date launchers and keys.

**Comment by perchec** [comment]
thanks, now it works
