### ISSUE TITLE
End of Stream

### ISSUE THREAD

**Issue by hederod** [Levak/warfacebot#489]
the bot is disconnected in a few seconds

any soluction ?

server NA

**Comment by Levak** [comment]
Few seconds is 1min, and if you force it, up to 20sec. This is MRAC kicking the bots because they don't implement the heartbeat. It will kick the account more often the more you try. So let it cool down for few minutes before trying again.

**Comment by hederod** [comment]
some mmorpg games use "visual mode" to circumvent the anticheat, 
but I have no idea how to do this...
openkore on ragnarok online is a exemple.

**Comment by Levak** [comment]
> some mmorpg games use "visual mode" to circumvent the anticheat,
> but I have no idea how to do this...
> openkore on ragnarok online is a exemple.

If I was to try for vent the MRAC anticheat - any cheater would have at hand a way to do it. Implementing the heartbeat is the fundamental pillar of how MRAC works. It assumes that if it has an heartbeat, the client is trusted and will send telemetry data. If it is a third-party client, it will kick it from the game server.
