### ISSUE TITLE
Help-Chaptcha Required

### ISSUE THREAD

**Issue by stevenrd** [Levak/warfacebot#49]
Hi Levak, Could you help me with this? Please...
Sorry, I'm newbe...
![test](https://cloud.githubusercontent.com/assets/25191622/22131296/c2ffd2d4-de88-11e6-960d-b2419719849a.jpg)

**Comment by ngoducdat** [comment]
Why you not try the release . It is easy to use
https://github.com/Levak/warfacebot/releases/tag/1.0.6
