### ISSUE TITLE
no ping

### ISSUE THREAD

**Issue by loker15** [Levak/warfacebot#499]
бот не запускается, пинга нет, на сервере ру альфа__the bot does not start, there is no ping, on the server ru alpha
![бот](https://user-images.githubusercontent.com/68181440/87553613-cab0f480-c6bb-11ea-9355-f0b23a593865.JPG)

**Comment by Levak** [comment]
Can you access the game normally from the same IP?

**Comment by loker15** [comment]
access to the game is from the same ip, and I play, the bot does not work. my friend also

**Comment by Levak** [comment]
Can you show the beginning of the console? Where the crypt key and game version are shown.

**Comment by loker15** [comment]
this place?
![12ц](https://user-images.githubusercontent.com/68181440/87559186-a3a9f100-c6c2-11ea-93be-a52f8ba08e38.JPG)

**Comment by Levak** [comment]
You are missing several cvars mandatory to start the bot.
`game_crypt_key` and `game_version` for instance.

**Comment by loker15** [comment]
where to get them

**Comment by loker15** [comment]
I have a bot on a virtual machine, there is no game on a virtual machine, only on the basis of

**Comment by Levak** [comment]
https://github.com/Levak/warfacebot/tree/master/cfg/server
