### ISSUE TITLE
Captcha removed from login endpoint

### ISSUE THREAD

**Issue by alexalok** [Levak/warfacebot#50]
Nuff said

**Comment by Levak** [comment]
Still wondering if I should update the public release and master when we know they are in transition to my.com. Perhaps it's just a temporary deactivation/mistake. Who knows. In every scenario we end up changing the launcher again in 1 or 2 months.

An immediate hotfix would be to revert the GUI launcher ( https://github.com/Levak/warfacebot/blob/bf2ab818c9a6306eacad1c1964b7716fa983e3b5/wb_launcher.hta ). AFAIK command line launcher is still compatible, isn't it?

**Comment by alexalok** [comment]
Yup, command line launcher still works, but from my personal experience, most of bot users run it using GUI launcher, so why not to ease their life? I bet most of them don't know how to revert anyway.

**Comment by Levak** [comment]
Closing, following to commit 0f157d6dd8c927e2f689298ad620b4b2955d0144 EU and NA use a new auth toward my.com that doesn't require captcha.
