### ISSUE TITLE
Use Babun instead of CygWIN

### ISSUE THREAD

**Issue by Lako-FC** [Levak/warfacebot#501]
Hello @Levak , I love your project ._.
I solved the problem in this request (I will make a README correction request soon): https://github.com/Levak/warfacebot/issues/487 https://github.com/Levak/warfacebot/issues/472 :D
(I use: Win10 Pro x64 (babun make x32 wb))

**Advantages of using Babun instead of CygWin:**
- Babun already has all the necessary packages for building "warfacebot levak". 
- Babun is easier and faster to install, and you don't need to choose anything, so let's say "everything in a click". 
- Babun-there is a CygWin, but it is a shell.
- Do not delete cygwin DLL's when rebuilding the project (cygwin had an error, it may be fixed in the future).
- Don't delete a line of code in the Makefile: `VALGRIND_API= $(shell echo '\#include <valgrind/memcheck.h>' | $(CC) -E-x c - > /dev/null 2> /dev/null & & echo '- DVALGRIND_API' | / echo ' ') `

**Instructions**:
1. Go to the 'babun' website: https://babun.github.io/
2. Download the archive.
![image](https://user-images.githubusercontent.com/59660240/88085391-3523d200-cb9f-11ea-94ee-89ac93ad4944.png)
3. Move the folder from the archive.
4. Run 'install.bat', wait until the end of the installation.
![image](https://user-images.githubusercontent.com/59660240/88085404-3a811c80-cb9f-11ea-9a22-95ee6ed0bf29.png)
![image](https://user-images.githubusercontent.com/59660240/88085410-3ce37680-cb9f-11ea-823f-171a4df761f5.png)
5. After installation, open the terminal.
6. Write: `cd '(path to warfacebot levak)'` (in my case: `cd "C:\warfacebot-master"`).
7. Write: `make` (if it was created earlier, write '`make clean`' to clean the build).
![image](https://user-images.githubusercontent.com/59660240/88085429-42d95780-cb9f-11ea-8210-d20f6728151f.png)
8. Waiting until the end of the build (created wb.exe). 
![image](https://user-images.githubusercontent.com/59660240/88085442-47057500-cb9f-11ea-8bf5-f54777ac6e9c.png)
9. Go to the folder installed 'babun' (standard: C:\Users\%USERPROFILE%\.babun).
10. Go to the bin section ('. babun\cygwin\bin\').
![image](https://user-images.githubusercontent.com/59660240/88085455-4bca2900-cb9f-11ea-9ffa-f5b259b7861a.png)
11. in turn, we search through the search for DLL files: cygcrypto-1.0.0.dll, cyggcc_s-1.dll, cygncursesw-10.dll, cygreadline7.dll, cygssl-1.0.0.dll, cygwin1.dll, cygz.dll
![image](https://user-images.githubusercontent.com/59660240/88085463-4f5db000-cb9f-11ea-888b-05f82f5048e6.png)
12. Copy the DLL files to the folder with 'wb.exe'.
![image](https://user-images.githubusercontent.com/59660240/88085477-5389cd80-cb9f-11ea-9b19-549b6f628a92.png)
13. Launching 'wb.exe' via the launcher.

P.S: 
1) If you need to install in your folder, then read 'install.txt'.
2) In the terminal insert is performed with the right mouse button.
3) In the future, you can run 'babun' by going to the catology (.babun) and running 'babun.bat'.
4) Remember that launching bots is prohibited on Warface-RU, you can get a game account blocked for this.
5) Launch bots is allowed only where there is no Warface, Game Center, mrac (for example, on a virtual machine).

**Comment by Levak** [comment]
Thanks for your interest in the project and this step-by-step guide.

I notice the following things in your screenshots:
 - Babun is "discontinued"
 - Cygwin 1.0.0

Isn't Babun "just" an older version of Cygwin, hence why it would work instead of cygwin v2.905 ?

**Comment by Lako-FC** [comment]
1. Babun is "discontinued" - I tested it.
2. Babun use CygWin (old version), but he optimized it and installed all the necessary packages.
https://github.com/babun/babun

**Comment by Lako-FC** [comment]
![image](https://user-images.githubusercontent.com/59660240/88087080-ce53e800-cba1-11ea-8a4e-5afd61a947f9.png)

**Comment by Lako-FC** [comment]
I thank you for your project, as the Creator of Fan-Bot's project.
![babun-logo](https://user-images.githubusercontent.com/59660240/88087272-1541dd80-cba2-11ea-96ab-1d298597135b.png)

**Comment by Lako-FC** [comment]
Babun - PROJECT DISCONTINUED, yes.
Its support is over, but it does not interfere with the build, and it has the source code.
The site is available and everything works, you can check for yourself.

**Comment by Levak** [comment]
The reason why I'm not thrilled to encourage the use of Babun is because it is basically an old (stable) version of CygWIN. Of course it will work as it used to work when I first ported warfacebot to CygWIN.

But CygWIN evolves, gets newer tools, compilers, libs etc. If Babun worked for you without any edit, good! But after a few tweaks I was able to fix CygWIN build too - see 64fe2d7
