### ISSUE TITLE
How to create a room mojave with 4 slots?

### ISSUE THREAD

**Issue by WFIsMyLife** [Levak/warfacebot#505]
Please help

**Comment by Levak** [comment]
You can't. You need minimum 16 players to start a battle royale game.

**Comment by Weser87** [comment]
create a room for 4 players - change lms_mojave

**Comment by WFIsMyLife** [comment]
> create a room for 4 players - change lms_mojave

Не удалось изменить настройки комнаты (8:0)

**Comment by I-LOVE-C2H5OH** [comment]
> > создать комнату для 4 игроков - изменить lms_mojave
> 
> Не удалось изменить настройки комнаты (8: 0)


this means it is impossible, as levak wrote above, it will not start if there are less than 16 players

**Comment by I-LOVE-C2H5OH** [comment]
I think the answer was exhaustive, I think you can open the question

**Comment by Grisha42** [comment]
Everything is for you)

Create a room for 4 players

insert command: <iq to="masterserver@warface/pvp_pro_076_r1" from="XXXXX@WARFACE/GameClient" type="get"><query xmlns="urn:cryonline:k01"><gameroom_update_pvp by_mission_key="1" mission_key="YYYYY" private="0" inventory_slot="17678991317" class_id="2" dead_can_chat="1" friendly_fire="0" enemy_outlines="0" auto_team_balance="0" join_in_the_process="1" /></query></iq>

Replace XXXXX with your payment ID
Replace YYYYY with the key of the desired map from pvp_maps.c

**Comment by Grisha42** [comment]
`<iq to="masterserver@warface/pvp_pro_076_r1" from="669642211@WARFACE/GameClient" type="get"><query xmlns="urn:cryonline:k01"><gameroom_update_pvp by_mission_key="1" mission_key="e246660c-52cb-4a56-8d25-c0f040d03793" private="0" inventory_slot="17678991317" class_id="2" dead_can_chat="1" friendly_fire="0" enemy_outlines="0" auto_team_balance="0" join_in_the_process="1" /></query></iq>`

**Comment by Grisha42** [comment]
Everything for you)

1) Create any 4 player room PVP
2) give master to bot
3) Fix my command for your bot: `<iq to="masterserver@warface/pvp_pro_076_r1" from="XXXXXX@WARFACE/GameClient" type="get"><query xmlns="urn:cryonline:k01"><gameroom_update_pvp by_mission_key="1" mission_key="YYYYYY" private="0" inventory_slot="17678991317" class_id="2" dead_can_chat="1" friendly_fire="0" enemy_outlines="0" auto_team_balance="0" join_in_the_process="1" /></query></iq>`
1)Replace XXXXX with payment ID
2)Replace YYYYY with the map code from src / pvp_maps.c
4)insert your command into the console

**Comment by Levak** [comment]
This is equivalent to using the "change" command

**Comment by Grisha42** [comment]
> Это эквивалентно использованию команды «изменить»

WF Is My Life wanted to make a 4-player Battle Royale. Using the change command, he would not be able to achieve the desired result, since it would change the standard settings for 32-player Battle Royale
