### ISSUE TITLE
How to change the bot profile

### ISSUE THREAD

**Issue by Golyb4ik** [Levak/warfacebot#506]
Hello! When I change the file src/xmpp_wf/result/xmpp_iq_peer_player_info.c , the statistics of the running bot is not updated, I can not understand what the problem is, please help (sorry for the translation, Yandex translator is used)

**Comment by Levak** [comment]
You need to recompile with `make`. For that you need a C compiler and all the required libraries in devel mode.
Bear in mind that altering the stats shown there can lead to bans as it is checked server-side.

**Comment by Golyb4ik** [comment]
can you tell us more about the compiler, such as the exact name/what needs to be done?

**Comment by Lako-FC** [comment]
._ .
Я как понимаю, то ты знаешь русский или же им являешься, так что лови статью:
https://vk.com/@official_funcode-wb-babun
> В ней показано, как пересобирать сборку и что для этого нужно установить.

**Comment by Golyb4ik** [comment]
Не знаю почему, бот включается очень долго и сразу же выключается, хотя всё сделал правильно по инструкции

**Comment by Lako-FC** [comment]
I helped him in THE Vkontakte social network.
You can close the request, I think.
