### ISSUE TITLE
make: *** [<integrated>: src/clanmate.o] Error 1

### ISSUE THREAD

**Issue by Lako-FC** [Levak/warfacebot#509]
**¯ \ _ (ツ) _ / ¯** 
(CygWin Last Version)

```
$ make
echo     > .opt
gcc -Wall -Wextra -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -O2 -MMD -Iinclude -Ithird_party -DZLIB -DUSE_TLS    -c -o src/clanmate.o src/clanmate.c
make: *** [<integrated>: src/clanmate.o] Error 1
```

**Comment by Lako-FC** [comment]
The build in' Babun ' works without problems.

**Comment by Levak** [comment]
Do you have the full error? 
I feel like something is missing from this output.

**Comment by Weser87** [comment]
for me cygwin works fine.
try to remove cygwin1.dll when building

**Comment by Lako-FC** [comment]
> Do you have the full error?
> I feel like something is missing from this output.

Yea, full error.

**Comment by Lako-FC** [comment]
> for me cygwin works fine.
> try to remove cygwin1.dll when building

Oh, **thank you**, it helped, but I already forgot after 2 years that you need to delete this library.
You can close the request.
