### ISSUE TITLE
Fix xmpp_iq_join_channel, wb_lang, russian.cfg, english.cfg

### ISSUE THREAD

**Issue by Lako-FC** [Levak/warfacebot#511]
@Levak 
I found an error in `sprintf("Total number of items: %ld", items->length);` [xmpp_iq_join_channel.c -> 322]

1. Approve my amendments to: `russian.cfg, english.cfg`
2. Fix in `wb_lang.h`: 
```
[185]      XLANG(unlocked_items)                   \
[186-add]  XLANG(total_number_of_items)            \
```
3. Fix in `xmpp_iq_join_channel.c`:
Replace `xprintf("Total number of items: %ld", items->length);` with `xprintf("%s: %ld", LANG(total_number_of_items), items->length);`
4. End.

**After that the translation will work:**
![image](https://user-images.githubusercontent.com/59660240/89289527-d10a0f00-d670-11ea-9b27-98f2781fd124.png)
![image](https://user-images.githubusercontent.com/59660240/89289694-1af2f500-d671-11ea-809f-9b5a99efd3fb.png)

**Comment by Levak** [comment]
Hi,
You did 2 PRs, #512 and #513 and an issue (this one #511) for the same "pull request".

Why not do it all at once, in one single PR? Are you doing it from the web interface?

**Comment by Lako-FC** [comment]
> Hi,
> You did 2 PRs, #512 and #513 and an issue (this one #511) for the same "pull request".
> 
> Why not do it all at once, in one single PR? Are you doing it from the web interface?

Yea, I do it through the web interface. I'm not very experienced in git.

**Comment by Lako-FC** [comment]
I have created a queries (4).
:D

**Comment by Levak** [comment]
> Yea, I do it through the web interface. I'm not very experienced in git.

For next time, instead of targeting "master", do "create a new branch", then in your other web-interface changes, target your new branch instead of "master", then you can create a PR from that branch. 

But I agree that github web interface is not very keen to have modifications in several files. Using the real git client is way better (but needs experience with git).

I will merge them all.

**Comment by Lako-FC** [comment]
> > Yea, I do it through the web interface. I'm not very experienced in git.
> 
> For next time, instead of targeting "master", do "create a new branch", then in your other web-interface changes, target your new branch instead of "master", then you can create a PR from that branch.
> 
> But I agree that github web interface is not very keen to have modifications in several files. Using the real git client is way better (but needs experience with git).
> 
> I will merge them all.

Thx) I'll remember.

**Comment by Levak** [comment]
I rebased to only have 1 commit 9860a7ff4f3421baad1b35cc429abebeb236a178
