### ISSUE TITLE
Help RUWF

### ISSUE THREAD

**Issue by SWITCH3ED** [Levak/warfacebot#52]
![1](https://cloud.githubusercontent.com/assets/25305127/22216373/e160b624-e1af-11e6-9f51-13a6fa6e6ea5.JPG)

**Comment by Levak** [comment]
Duplicate of #20

**Comment by alexalok** [comment]
You can use a wrapper for warfacebot https://mechcraft.ru/mechcraft-бот-standalone/
It is paid, however.

**Comment by SWITCH3ED** [comment]
Thanks, programm not free?

**Comment by Levak** [comment]
> You can use a wrapper for warfacebot https://mechcraft.ru/mechcraft-бот-standalone/
It is paid, however.

Is Warfacebot AGPLv3 license file shipped with the executable that is installed on the client?

**Comment by alexalok** [comment]
yup
