### ISSUE TITLE
Duration for server kick

### ISSUE THREAD

**Issue by SvenBM** [Levak/warfacebot#537]
Hi, the time until the bot gets kicked from the server has become VERY short. It's only 3 or 4 seconds by now. 
Can i do something to increase this duration?

**Comment by Levak** [comment]
Sadly, no. Due to abuses of certain russian players using warfacebot o farm xp and cp in illegal ways, mailru a d mycom want to make the life of bots (3rd party clients) impossible.

**Comment by SvenBM** [comment]
Thanks for response. Sad, indeed -.-
