### ISSUE TITLE
The bot goes on only 1 sec

### ISSUE THREAD

**Issue by tetteykn** [Levak/warfacebot#540]
when i start the bots with windows they go on only for 1 or 2 sec then they go offline.

Is there a command to reject friend invitation? i used DND on them but doesnt work

**Comment by Levak** [comment]
1. No, this is the new anti-bot measures taken by mygames/mailru that reduced the time allowed for 3rd party clients from 5min to 6 sec

2. Yes, `wb_accept_friend_requests 0` but I recommend `wb_postpone_friend_requests 1` to not immediately reject friend requests, as it will be obvious the client is using a bot. Same pair of options exist for clans. Read the main page.

**Comment by tetteykn** [comment]
Thanks
