### ISSUE TITLE
Checking game keys on RU servers

### ISSUE THREAD

**Issue by wnull** [Levak/warfacebot#544]
Hi, @Levak. Could you check the validity of keys for RU servers? Authorization is successful, I looked at the `token` and `userid` - the values are valid. But at startup wb.exe you can't log in to the game by passing parameters.

```bash
Starting TLS connection...
done.
Authentication failed
Closed dispatch
CMD# ^C

Closed idle
Warface Bot closed!
CMD#
```

**Comment by AleksTeam** [comment]
НЕ РАБОТАЮТ БОТЫ! cmd открывается потом сразу же закрывается

**Comment by ProIsmo** [comment]
https://ru.warface.com/news/1009009.html

> Улучшены методы проверки игроков на этапе авторизации. Это сильно затрудняет подключение к игре через сторонние приложения, которые могли использоваться злоумышленниками.

**Comment by AleksTeam** [comment]
Значит, WFBot не будет работать?

**Comment by wnull** [comment]
@ProIsmo, thank you for the info.

**Comment by AleksTeam** [comment]
Можете пожалуйста ответить на мой вопрос: "Значит, WFBot не будет работать?"

**Comment by bakedbeans3** [comment]
How about NA server keys Levak?

**Comment by Kavan72** [comment]
@bakedbeans3 forgot about warfacebot, go play mario

**Comment by Carlsberg34** [comment]
The end of bot breeding on the RU server has come
