### ISSUE TITLE
Update version for WEST to 1.22800.2166.11900 Authentication failed Closed Dispatch#

### ISSUE THREAD

**Issue by SencerSofuoglu** [Levak/warfacebot#545]
Hi;
I get this error.
My password, username is correct.
I could not understand the reason.
Can you help me fix the problem?
........................
Starting TLS connection...
done.
Authentication failed
Closed dispatch
CMD#
.......................................

**Comment by EpidemzWF** [comment]
Game update on September 24.
Improved methods for checking players at the login stage. This makes it difficult to connect to the game through third-party applications that could be used by attackers.

Only Levak can figure it out, the only question is whether he wants to do it.

**Comment by SencerSofuoglu** [comment]
> 
> 
> Game update on September 24.
> Improved methods for checking players at the login stage. This makes it difficult to connect to the game through third-party applications that could be used by attackers.
> 
> Only Levak can figure it out, the only question is whether he wants to do it.

Could you help?
No.
Why do you write things we already know?

**Comment by I-LOVE-C2H5OH** [comment]
> > Обновление игры 24 сентября. 
> > Улучшены методы проверки игроков на этапе авторизации. Это затрудняет подключение к игре через сторонние приложения, которые могут быть использованы злоумышленниками.
> > Разобраться может только Левак, вопрос только в том, хочет ли он это делать.
> 
> Не могли бы вы помочь?
> Нет.
> Почему вы пишете то, что мы уже знаем?


Как помочь вам? Весь исходный код дан на главной странице, вся информация есть там, потому что левак оставил комментарии.

**Comment by SencerSofuoglu** [comment]
> 
> 
> > > Обновление игры 24 сентября.
> > > Улучшены методы проверки игроков на этапе авторизации. Это затрудняет подключение к игре через сторонние приложения, которые могут быть использованы злоумышленниками.
> > > Разобраться может только Левак, вопрос только в том, хочет ли он это делать.
> > 
> > 
> > Не могли бы вы помочь?
> > Нет.
> > Почему вы пишете то, что мы уже знаем?
> 
> Как помочь вам? Весь исходный код дан на главной странице, вся информация есть там, потому что левак оставил комментарии.

Sorry i dont understand.. 
Pls write me English...

**Comment by Sofuzade** [comment]
i dont understand bot isnt work but levak updating all time .. İf not work why updating ? İf it work why dont you interest our writing?

**Comment by SencerSofuoglu** [comment]
bot not working but why updating levak ?

**Comment by Levak** [comment]
Duplicate of #547
