### ISSUE TITLE
[RU] Failed to join channel since update

### ISSUE THREAD

**Issue by shockwaves** [Levak/warfacebot#58]
current version warfacebot is `1.14500.1321.41200`
Game.log contain version `1.14500.1334.41200`
server `ru-alpha`

**Comment by Levak** [comment]
You edit `cfg/server/ru-alpha.cfg` with the appropriate one.

**Comment by shockwaves** [comment]
Failed to join channel (Invalid token or userid)

**Comment by shockwaves** [comment]
i change version accord to new in ru-alpha confug but now message is
`Failed to join channel (Invalid token or userid)`

**Comment by Levak** [comment]
I can reproduce, I'll look later when I get my hands on official RU client.

**Comment by shockwaves** [comment]
big thank`s Levak! Your application is great!

**Comment by Levak** [comment]
Should be fixed now.
Thanks for the report 👍
