### ISSUE TITLE
STAY wf

### ISSUE THREAD

**Issue by walvering** [Levak/warfacebot#67]
I would like to change the amount of time in the stay command..example 10 hours

**Comment by bosoi911** [comment]
Levak what this? 
![d5ae4a3aed6848f2acfab47947427ba9](https://cloud.githubusercontent.com/assets/26326318/24018905/e18370c2-0aa6-11e7-8c4d-20b488604cf5.png)

**Comment by Levak** [comment]
@bosoi911 I already told you to not hijack other unreleated issues. to answer your question, you need the most recent version from yesterday.

@walvering pinning for enhancement (a cvar).
In the meantime, you can perhaps edit 
https://github.com/Levak/warfacebot/blob/master/src/cmd/cmd_stay.c#L32 for the owner-only command

and
https://github.com/Levak/warfacebot/blob/master/src/xmpp_wf/result/xmpp_message.c#L289. for the whisper command.

Which one had you in mind in particular?

**Comment by walvering** [comment]
Command whisper ... if I want to make alteration in time ..example: put 10h or more .. how would it?

**Comment by Levak** [comment]
> how would it?

Told you, either wait for a new CVar or modify it by yourself where I linked you (and recompile).

**Comment by bosoi911** [comment]
The bot has started! But it turns off after 3 min! thank you in advance!

![3bf4d3cce1bd45a8ac0eb79aa65c8a53](https://cloud.githubusercontent.com/assets/26326318/24031625/abd1b31e-0af4-11e7-84ea-3f10d741f8b4.png)

**Comment by Levak** [comment]
@bosoi911 third time, next time I delete your posts. Create your own issues.
To answer you, this is a known "issue". It's called MRAC. On EU/NA/RU you cannot hold a session longer than 4 minutes.

**Comment by alexalok** [comment]
BTW, if bot enters a game which has already started, it exits even if in stay mode.

**Comment by Levak** [comment]
> BTW, if bot enters a game which has already started, it exits even if in stay mode.

Stay mode is local to a game room. You cannot enter stay mode from outside a game room.

**Comment by alexalok** [comment]
> Stay mode is local to a game room. You cannot enter stay mode from outside a game room.

Oh, didn't pay attention to that. Thanks for clarifying.
