### ISSUE TITLE
[VN] Failed to join channel (Invalid token or userid)

### ISSUE THREAD

**Issue by ptaking** [Levak/warfacebot#68]
![screen shot 2017-03-21 at 9 11 30 am](https://cloud.githubusercontent.com/assets/12915431/24129697/3c0ce2a2-0ddc-11e7-9196-56c24c77fbca.png)
It just happend this morning.

**Comment by ptaking** [comment]
It's seems like server's problem.

**Comment by ptaking** [comment]
Issue confirmed from server.

**Comment by alexalok** [comment]
You should generally recompile wb in debug mode (`make clean debug-wb`) to be able to see which query causes an error.
