### ISSUE TITLE
Internal Error - when try to log in

### ISSUE THREAD

**Issue by SyclopX** [Levak/warfacebot#70]
![untitlediiiiii](https://cloud.githubusercontent.com/assets/23517655/24322730/200628ea-1190-11e7-9bbb-75eb50edffb7.png)

When I try to log in this error message comes 
I am using my.com europe server

**Comment by Levak** [comment]
Which realm?

If you can, with a text editor, edit wb_launcher.hta
Comment lines 381, 407-9
https://github.com/Levak/warfacebot/blob/master/wb_launcher.hta#L381
https://github.com/Levak/warfacebot/blob/master/wb_launcher.hta#L407

**Comment by SyclopX** [comment]
Server - my.com europe 

![untitledhhhhhhhh](https://cloud.githubusercontent.com/assets/23517655/24322915/ebfdb344-1192-11e7-89e4-5781890faede.png)

**Comment by Levak** [comment]
> Server - my.com europe

I just tested, have no issue, even if password is wrong.

BTW, "comment the lines", I meant "add // in front of the lines". Objective: Remove the try/catch so that the internal error is raised with details - didn't take the time to add a proper error handling.

This will show at least the line that is causing the "internal error" in the code.

**Comment by SyclopX** [comment]
I get these error messages 

Line: 421
Error: Object doesn't support this property or method
(when I open wb_launcher.hta)
I closed error message launcher opened 

Line: 130
Error: Object expected
(when I press Login)
I closed error message then nothing happens

I have commented 381, 407, 408, 409 lines as you said.

Thanks in advance for your time wasting for me.

**Comment by Levak** [comment]
Ok.
What version of IE do you have?

Seems like there are some troubles with older version which I didn't address
http://stackoverflow.com/questions/1695376/msie-and-addeventlistener-problem-in-javascript

For the second error, line 130, try replacing `text/xml` with `text/html`. I do not have a lot of visibility as to why you would end up with HTML in the returned queries. Perhaps a permission denied? You can also add just before line 130 a `alert(u.txt);` and see what it says.

**Comment by SyclopX** [comment]
I updated Internet Explorer. Now its working fine. Thank you for your support.
