### ISSUE TITLE
Error with wb.sh

### ISSUE THREAD

**Issue by warete** [Levak/warfacebot#71]
![image](https://cloud.githubusercontent.com/assets/12802923/24330659/7983519e-122c-11e7-9cdf-71646e3a741e.png)

**Comment by Levak** [comment]
That's a bash error that happens when you edit a file with windows notepad.
You edited wb.sh didn't you?
Download the file again and use another code editor that doesn't add \r to lines.

**Comment by warete** [comment]
No, i didnt edit this file.

**Comment by alexalok** [comment]
If you `git clone`d  bot on Windows using Git which was installed with default settings, it automatically converted line endings to Windows-style. As a solution, one can use Notepad++, which has a conversion feature, or disable autoconversion of line endings in Git settings.

As a last resort, download the file again, as Levak said (i.e. https://raw.githubusercontent.com/Levak/warfacebot/master/wb.sh) and **do not open it** using default Notepad. Aforementioned Notepad++ will work, though.

**Comment by Levak** [comment]
No answers in a week, closing.
