### ISSUE TITLE
Warface Thailand

### ISSUE THREAD

**Issue by dolongnao** [Levak/warfacebot#72]
Hi levak!
You can update the bot for warface Thailand. [https://warface.in.th]
Thanks.

**Comment by SyclopX** [comment]
+
waiting for the update for Thailand
if you need game files for something i can upload as a help :)

**Comment by Levak** [comment]
Hi,

> if you need game files for something i can upload as a help :)

The most "critical" part is the launcher, nor the game files :p

Game files usually only give game version. On the other hand, launcher gives server address and authentication method. AFAIK, TH server uses facebook to login.

I don't have this feature in my priority queue at the moment, but I will gladly merge a pull request if someone ends up doing it.

**Comment by SyclopX** [comment]
New NetPlay launcher does not need facebook to login. Just ID and password
![wb2](https://cloud.githubusercontent.com/assets/23517655/26165843/0b55c962-3b4f-11e7-958f-88a57108ca60.png)

If you have extra time please improve this feature for us

**Comment by Levak** [comment]
Closing, since Warface Thailand stopped to exist.
