### ISSUE TITLE
End of stream

### ISSUE THREAD

**Issue by Alov** [Levak/warfacebot#75]
Hi! I have some problem...
The bot enters the game for a few moments and waits for instructions from the terminal, and then I get it
```
read: End of stream (5)
Closed readstream
Closed sendstream
Closed ping
```
Then the bot exits the game.
Also, I have problems with displaying cyrillic letters.
Current version of the game 1.14700.1352.41200

![image](https://cloud.githubusercontent.com/assets/20107363/24874768/7b6d0532-1e2e-11e7-956c-1c1bb67d413f.png)

**Comment by Alov** [comment]
The linux version has the same problem, but the problem with Cyrillic is solved.
![image](https://cloud.githubusercontent.com/assets/20107363/24877635/01a0889c-1e41-11e7-8edf-1edc1cef0f44.png)

**Comment by Levak** [comment]
Hi,

Regarding the DC, this is a known issue, called MRAC. See #20
Regarding Cyrillic, see #66
