### ISSUE TITLE
BOT stay in game

### ISSUE THREAD

**Issue by minhxxx** [Levak/warfacebot#77]
Dear Levak, 

How to let the bot stay in the game, not just in the room? 

We can play the solo game, but still want to collect XP, $ to BOT account, can we do that? 

Please help me ^_^

Thanks.

**Comment by Levak** [comment]
Hi,
Warfacebot is an implementation of the lobby protocol, the one using XMPP (text-based protocol).
Joining the game session means implementing the CryEngine network protocol (synchronized, compressed, by channel, binary-based protocol), which is not done.

Also, let's suppose this existed, gaining XP, money, etc requires certain constrains regarding Warface match minimum requirement. For instance, in PvE, a player will gain the same amount of base XP as the other players if it has a positive score, non-null. A "bot" standing still will gain no XP. In PvP, the story is somewhat similar yet longer to explain, but I hope you get the point.

At the moment there is no plan what so ever to implement a CryEngine layer in Warfacebot.

**Comment by minhxxx** [comment]
Dear Levak, 

Thanks for you explain, I got your point, appreciated for your quickly reply.

Cheers,
