### ISSUE TITLE
Failed to get account profiles (reason: Game version mismatch)

### ISSUE THREAD

**Issue by zeca2099** [Levak/warfacebot#78]
How do i fix this??

**Comment by Levak** [comment]
You edit the file `cfg/server/<yourserver>.cfg` with the appropriate -quote on quote- "game version".
And if you are lazy, you can just download the latest version from the automatic builds from today.

https://github.com/Levak/warfacebot/releases/tag/1.0.9

**Comment by nathan130200** [comment]
I changed the correct game version. And same error occurs. I'm using for BR and version is 1.1.419.115.

**Comment by nathan130200** [comment]
Simply, your bot no longer suits the latest warface updates.

**Comment by Levak** [comment]
> I changed the correct game version. And same error occurs.

Probably means it's not the correct version

> I'm using for BR and version is 1.1.419.115, simply,

AFAIK, the versions are not of that format. More something like `1.13000.612.21500` (that's an old one, i know). To get game version, go to install dir, do Alt+Enter on `Bin32Release\Game.exe` then `Details`.

> your bot no longer suits the latest warface updates.

I rarely keep version numbers up to date, they are just a simple text version to change for the end user, rather than recompiling the entire app.

**Comment by nathan130200** [comment]
What a funny thing, I said the bot badly, quickly you answered if defending, now help rubens with the xmpp server, you completely ignore it. I have the same files of your xmpp that you have in the prints. Too bad I just found out about the damage / hits.

**Comment by nathan130200** [comment]
I've always known that you deliberately ignore others on the forum.

**Comment by nathan130200** [comment]
I thought Americans were cooler, but now I see they're all uneducated.

**Comment by nathan130200** [comment]
So you're really ignoring anyone who asks you about the xmpp server?

**Comment by nathan130200** [comment]
So you're really ignoring anyone who asks you about the xmpp server?

**Comment by nathan130200** [comment]
You can delete the will that I put.
