### ISSUE TITLE
Statistics thread

### ISSUE THREAD

**Issue by LimeiloN** [Levak/warfacebot#86]
IDEA ! Warfacebot may collect data to provide some stats like number of online players, writing it to a file for further interpreting.
I think of a thread which collect the data and write it in the file. Multiple cvars can be used : 
- stat_collect (activate or deactivate the thread)
- stat_deltatime (time between queries)

But I would need some help to do it as idk how to have those .o object files for generation.
The main functions should be easy to perform as I pretty much understood how warfacebot work.

**Comment by Levak** [comment]
Hi,

Such work load has been deported to the DBus API in an attempt to remove any specific usage from warfacebot.

This means that, if you want to script warfacebot behavior, you can do so using its DBus API. Server statistics are provided thru the method _ChannelStats_.

See #59
