### ISSUE TITLE
Help problems

### ISSUE THREAD

**Issue by franchesko1437** [Levak/warfacebot#87]
hi Levak
Problem. The bot does not start. After the CMD, nothing happens
Mail/alpha
Photo:
http://s011.radikal.ru/i318/1706/c7/56202d81f6df.jpg

**Comment by Levak** [comment]
Please make sure the game version in `cfg/server/ru-alpha.cfg` matches the one of your game client.
For instance, I see RU server is at version `1.15000.1381.41200` right now.

**Comment by franchesko1437** [comment]
Already solved the problem. Thank you for quick response.
Tell me why the bot crashes from the server after 2 minutes in the game. In mechcraft. Does not crash after 2 minutes

**Comment by Levak** [comment]
because of MRAC. mechcraft has auto relogin by just relaunching bot automatically.

**Comment by franchesko1437** [comment]
mechcraft lasts longer than 10-20 minutes

**Comment by franchesko1437** [comment]
Ты знаешь русский язык?

**Comment by Levak** [comment]
> Ты знаешь русский язык?

No, I use gtranslate if needed.

**Comment by franchesko1437** [comment]
Ok. So why does not mechcraft take longer?

**Comment by franchesko1437** [comment]
Do not take off from the game server for longer*

**Comment by franchesko1437** [comment]
Difficulties of translation. Sorry. Using translator

**Comment by Levak** [comment]
> Difficulties of translation. Sorry. Using translator
You can edit your posts if needed.

> Ok. So why does not mechcraft do not take off from the game server for longer
As I said, they probably just have auto-relaunch and you think it lasts longer. Mechcraft uses unmodified warfacebot. If they did modify it, ask them for the source code as the license is AGPLv3.

**Comment by franchesko1437** [comment]
In Sense, ask for the source code? They can provide it?

**Comment by Levak** [comment]
> In Sense, ask for the source code? They can provide it?

They have to provide the sources yes, according to AGPLv3 license of warfacebot. Of course, only the sources of the executable. If they have some magic _outside_ of warfacebot, you cannot claim the sources for it.

**Comment by franchesko1437** [comment]
thank you

**Comment by franchesko1437** [comment]
A question.
Have a bot fixed on a Russian server?
How to reset trial on mechcraft
