### ISSUE TITLE
Do you support other methods?

### ISSUE THREAD

**Issue by nathan130200** [Levak/warfacebot#88]
_Can I join him, with a bot in the discord? Another thing how can I compile the project in windows? I know there is the mingw version of it on windows but I would like to compile it in debug mode, I am studying the structure of xmpp._

**Comment by Levak** [comment]
> Can I join him, with a bot in the discord?

You can create a python script that would bin DBus commands from the bot and connect into Discord using its Pythong API.

> Another thing how can I compile the project in windows? I know there is the mingw version of it on windows but I would like to compile it in debug mode, I am studying the structure of xmpp.

Download mingw and compile it the same way as TravisCI does (see `.travisci` file)

**Comment by nathan130200** [comment]
Thanks :D
