### ISSUE TITLE
Closes the program after connecting the bot

### ISSUE THREAD

**Issue by Tapok777** [Levak/warfacebot#92]
I seem to have figured out all the installation problems and it works. But when the bot enters the network after a few seconds the program warfacebot-master closes this because of the MRAC?

**Comment by Levak** [comment]
After a few seconds, because of missing `game_hwid`, and after a few minutes with.
Both due to MRAC, yes.

**Comment by Tapok777** [comment]
How to turn on include game_hwid?

**Comment by Levak** [comment]
Edit `wb.cfg`, and put the following:

```
game_hwid = xxxx
```

... where `xxxx` is a valid HWID. Not going any further in the explanation.

**Comment by Tapok777** [comment]
Should I write my real game_hwid or random?

**Comment by Tapok777** [comment]
The video shows my problem, while the program does not give me an error, it just closes without warning.
video https://youtu.be/eT6xxU0pwW0

**Comment by franchesko1437** [comment]
Чел как у тебя все на русском языке? у меня крякозыба, а он помогать не хочет.  Вылетать будет всегда это особенность античита, а если хочешь что бы автоматически перезапускало купи мечкрафт за 199 р

**Comment by Tapok777** [comment]
Я язык в файле wb.cfg менял, а именно, что бы не было кракозябр, я не делал каких-то специальных настроек. А что за "мечкрафт за 199" и где купить?

**Comment by Tapok777** [comment]
А так по сути, я понял, что у тебя проблемы с региональными настройками языка.

**Comment by franchesko1437** [comment]
Загугли mechcraft
