### ISSUE TITLE
src/threads/thread_readline.c:29:31: fatal error: readline/readline.h: No such file or directory

### ISSUE THREAD

**Issue by snevs** [Levak/warfacebot#93]
sudo make
echo   -DHAVE_STRNDUP > .opt
gcc -Wall -Wextra -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -O2 -MMD -Iinclude -Ithird_party -DZLIB -DUSE_TLS -pthread -DHAVE_STRNDUP   -c -o src/threads/thread_readline.o src/threads/thread_readline.c
src/threads/thread_readline.c:29:31: fatal error: readline/readline.h: No such file or directory
 #include <readline/readline.h>
                               ^
compilation terminated.
make: *** [src/threads/thread_readline.o] Error 1

**Comment by Levak** [comment]
Hi,

Install deadline dev package for your distribution. Possibly something like libreadline5-dev.
