### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ElezClub** [Levak/warfacebot#95]
Hello, community. I used to use the bot downloaded from here: https://github.com/Levak/warfacebot/releases/download/1.0.9/warfacebot-mingw-1.0.9.zip, but now I can not go to the European server. I fixed the game version to 1.15000.145.36800, but it does not help. Can you help me?

I apologize for the inaccuracies, I use an interpreter.

**Comment by Levak** [comment]
Hi,

The problem affects EU and NA servers, and is under investigation.
Once the problem is fixed, I'll prepare a new binary release during the weekend.

**Comment by ElezClub** [comment]
Many thanks. I use your bots to run on PvE. I wish good luck in solving the problem, Levak!

**Comment by Levak** [comment]
https://github.com/Levak/warfacebot/releases/tag/1.0.10
