### ISSUE TITLE
The CMD# does not carry anything

### ISSUE THREAD

**Issue by PKMadPhantom** [Levak/warfacebot#99]
![sem titulo](https://user-images.githubusercontent.com/30567330/28752030-1b081726-74ec-11e7-830e-8c07d7c71d2b.png)

**Comment by Levak** [comment]
Hi,

At this point, the bot is not yet connected to the server.
It is most probably stuck because the encryption key is outdated.
You can check out https://github.com/Levak/warfacebot/blob/master/cfg/server/na.cfg for an up to date one.
